import {
  ordinaryUnitExpected,
  type TrialFidelityDelta,
  type UnitReferenceSpec,
} from "../unit-reference-schema";

const TRIAL_PROTO_SHA256 = "464520f1ea00b36e1872bf5a59831408c819c205e56f055c7b2e8bdf53719da2";
const GREEK_ASSET_INVENTORY_SHA256 =
  "b87dbdf96d2d020b4f885edff58c96df028064fc00f012124a597495e14b6c34";
const EGYPTIAN_ASSET_INVENTORY_SHA256 =
  "ba7b5c96ff3f7977d28ec97ca699e479b2d38fff9d5f7a605516a2dfe2b62d8e";
const REVIEW_COMMIT = "2a434a8c6d16ea0f51aadd21eb7d6960bb4299da";

function source(
  culture: "greek" | "egyptian",
  unitId: number,
  unitName: string,
  rootAnimation: string,
  trialDeltas: readonly TrialFidelityDelta[] = [],
) {
  return {
    stage: "final",
    culture,
    ruleset: "Age of Mythology Extended Edition / The Titans",
    trialProto: { sha256: TRIAL_PROTO_SHA256, unitId, unitName },
    assetInventory: {
      sha256: culture === "greek" ? GREEK_ASSET_INVENTORY_SHA256 : EGYPTIAN_ASSET_INVENTORY_SHA256,
      rosterName: unitName,
      rootAnimation,
    },
    trialDeltas,
    finalRulesetReview: {
      commit: REVIEW_COMMIT,
      scope:
        "Complete runtime reference, including assignments and fields absent from the Trial proto.",
    },
  } as const;
}

export const GATE_A_UNIT_REFERENCES = [
  {
    family: "ordinary-melee",
    id: 64,
    key: "greek-hoplite",
    source: source("greek", 439, "Hoplite", "hoplite_anim.txt", [
      {
        field: "cost",
        trial: [60, 0, 35, 0],
        final: [50, 0, 40, 0],
        reason:
          "The final pinned ruleset uses 50 Food / 40 Gold; the 2002 Trial uses 60 Food / 35 Gold.",
      },
    ]),
    expected: ordinaryUnitExpected({
      label: "Hoplite",
      culture: 1,
      classes: 54,
      maxHp: 115,
      lineOfSight: 16,
      movementSpeed: 4.2,
      armor: [0.35, 0.15, 0.99],
      attack: {
        kind: "melee",
        damage: [8, 0, 0],
        range: 0.3,
        aggroRange: 16,
        cooldownTicks: 30,
        bonuses: [],
      },
      bodyRadius: 0.49,
      cost: [50, 0, 40, 0],
      buildTicks: 280,
      populationCost: 2,
      requiredAge: 1,
      requiredGod: 255,
      prerequisiteBuildings: [22],
      trainedAt: [{ type: 22, commandSlot: 0 }],
    }),
  },
  {
    family: "ordinary-melee",
    id: 65,
    key: "greek-hypaspist",
    source: source("greek", 440, "Hypaspist", "hypaspist_anim.txt", [
      {
        field: "maxHp",
        trial: 85,
        final: 95,
        reason: "The final pinned ruleset uses 95 HP; the 2002 Trial uses 85 HP.",
      },
    ]),
    expected: ordinaryUnitExpected({
      label: "Hypaspist",
      culture: 1,
      classes: 54,
      maxHp: 95,
      lineOfSight: 16,
      movementSpeed: 4.3,
      armor: [0.35, 0.1, 0.99],
      attack: {
        kind: "melee",
        damage: [5, 0, 0],
        range: 0.3,
        aggroRange: 16,
        cooldownTicks: 30,
        bonuses: [
          { target: { kind: "classes", classes: 4 }, multiplier: 4.25 },
          {
            target: { kind: "classes", classes: 2048, requiredCulture: 3 },
            multiplier: 4.25,
          },
        ],
      },
      bodyRadius: 0.49,
      cost: [60, 0, 25, 0],
      buildTicks: 180,
      populationCost: 2,
      requiredAge: 2,
      requiredGod: 255,
      prerequisiteBuildings: [22],
      trainedAt: [{ type: 22, commandSlot: 1 }],
    }),
  },
  {
    family: "ordinary-melee",
    id: 66,
    key: "greek-hippikon",
    source: source("greek", 441, "Hippikon", "hippikon_anim.txt"),
    expected: ordinaryUnitExpected({
      label: "Hippikon",
      culture: 1,
      classes: 58,
      maxHp: 150,
      lineOfSight: 8,
      movementSpeed: 5.5,
      armor: [0.1, 0.25, 0.99],
      attack: {
        kind: "melee",
        damage: [10, 0, 0],
        range: 0.3,
        aggroRange: 8,
        cooldownTicks: 30,
        bonuses: [{ target: { kind: "classes", classes: 1024 }, multiplier: 1.25 }],
      },
      bodyRadius: 0.7,
      cost: [40, 0, 80, 0],
      buildTicks: 300,
      populationCost: 3,
      requiredAge: 1,
      requiredGod: 255,
      prerequisiteBuildings: [25],
      trainedAt: [{ type: 25, commandSlot: 0 }],
    }),
  },
  {
    family: "ordinary-melee",
    id: 67,
    key: "greek-prodromos",
    source: source("greek", 442, "Prodromos", "prodromos_anim.txt"),
    expected: ordinaryUnitExpected({
      label: "Prodromos",
      culture: 1,
      classes: 58,
      maxHp: 120,
      lineOfSight: 16,
      movementSpeed: 6,
      armor: [0.2, 0.1, 0.99],
      attack: {
        kind: "melee",
        damage: [6, 0, 0],
        range: 0.3,
        aggroRange: 16,
        cooldownTicks: 30,
        bonuses: [{ target: { kind: "classes", classes: 8 }, multiplier: 3 }],
      },
      bodyRadius: 0.7,
      cost: [70, 0, 40, 0],
      buildTicks: 200,
      populationCost: 3,
      requiredAge: 2,
      requiredGod: 255,
      prerequisiteBuildings: [25],
      trainedAt: [{ type: 25, commandSlot: 1 }],
    }),
  },
  {
    family: "ordinary-melee",
    id: 68,
    key: "greek-myrmidon",
    source: source("greek", 450, "Myrmidon", "myrmidon_anim.txt"),
    expected: ordinaryUnitExpected({
      label: "Myrmidon",
      culture: 1,
      classes: 54,
      maxHp: 110,
      lineOfSight: 16,
      movementSpeed: 4,
      armor: [0.45, 0.2, 0.99],
      attack: {
        kind: "melee",
        damage: [10, 0, 0],
        range: 0.3,
        aggroRange: 16,
        cooldownTicks: 30,
        bonuses: [{ target: { kind: "classes", classes: 4096 }, multiplier: 1.5 }],
      },
      bodyRadius: 0.49,
      cost: [70, 0, 50, 0],
      buildTicks: 280,
      populationCost: 2,
      requiredAge: 3,
      requiredGod: 0,
      prerequisiteBuildings: [26],
      trainedAt: [
        { type: 22, commandSlot: 2 },
        { type: 26, commandSlot: 6 },
      ],
    }),
  },
  {
    family: "ordinary-melee",
    id: 84,
    key: "greek-hetairoi",
    source: source("greek", 451, "Hetairoi", "hetairoi_anim.txt"),
    expected: ordinaryUnitExpected({
      label: "Hetairoi",
      culture: 1,
      classes: 58,
      maxHp: 110,
      lineOfSight: 16,
      movementSpeed: 4.8,
      armor: [0.1, 0.4, 0.99],
      attack: {
        kind: "melee",
        damage: [8, 0, 0],
        range: 0.3,
        aggroRange: 16,
        cooldownTicks: 30,
        bonuses: [{ target: { kind: "classes", classes: 64 }, multiplier: 3.5 }],
      },
      bodyRadius: 0.7,
      cost: [60, 0, 100, 0],
      buildTicks: 340,
      populationCost: 3,
      requiredAge: 3,
      requiredGod: 1,
      prerequisiteBuildings: [26],
      trainedAt: [
        { type: 25, commandSlot: 2 },
        { type: 26, commandSlot: 6 },
      ],
    }),
  },
  {
    family: "ordinary-melee",
    id: 69,
    key: "egyptian-spearman",
    source: source("egyptian", 291, "Spearman", "spearman_anim.txt", [
      {
        field: "attack.bonuses",
        trial: [{ target: { kind: "classes", classes: 8 }, multiplier: 1.1 }],
        final: [
          { target: { kind: "classes", classes: 8 }, multiplier: 1.1 },
          { target: { kind: "classes", classes: 512 }, multiplier: 2 },
        ],
        reason:
          "The final pinned ruleset includes the 2x siege bonus in addition to the Trial cavalry bonus.",
      },
    ]),
    expected: ordinaryUnitExpected({
      label: "Spearman",
      culture: 2,
      classes: 4150,
      maxHp: 70,
      lineOfSight: 16,
      movementSpeed: 5,
      armor: [0.4, 0.2, 0.99],
      attack: {
        kind: "melee",
        damage: [7, 0, 0],
        range: 0.3,
        aggroRange: 16,
        cooldownTicks: 30,
        bonuses: [
          { target: { kind: "classes", classes: 8 }, multiplier: 1.1 },
          { target: { kind: "classes", classes: 512 }, multiplier: 2 },
        ],
      },
      bodyRadius: 0.49,
      cost: [50, 0, 20, 0],
      buildTicks: 180,
      populationCost: 2,
      requiredAge: 1,
      requiredGod: 255,
      prerequisiteBuildings: [23],
      trainedAt: [{ type: 23, commandSlot: 0 }],
    }),
  },
  {
    family: "ordinary-melee",
    id: 70,
    key: "egyptian-axeman",
    source: source("egyptian", 292, "Axeman", "axeman_anim.txt"),
    expected: ordinaryUnitExpected({
      label: "Axeman",
      culture: 2,
      classes: 54,
      maxHp: 70,
      lineOfSight: 16,
      movementSpeed: 4.3,
      armor: [0.4, 0.05, 0.99],
      attack: {
        kind: "melee",
        damage: [5, 0, 0],
        range: 0.3,
        aggroRange: 16,
        cooldownTicks: 30,
        bonuses: [
          { target: { kind: "classes", classes: 4 }, multiplier: 4 },
          {
            target: { kind: "classes", classes: 2048, requiredCulture: 3 },
            multiplier: 4,
          },
        ],
      },
      bodyRadius: 0.49,
      cost: [40, 0, 30, 0],
      buildTicks: 200,
      populationCost: 2,
      requiredAge: 1,
      requiredGod: 255,
      prerequisiteBuildings: [23],
      trainedAt: [{ type: 23, commandSlot: 1 }],
    }),
  },
  {
    family: "ordinary-melee",
    id: 71,
    key: "egyptian-camelry",
    source: source("egyptian", 295, "Camelry", "camelry_anim.txt"),
    expected: ordinaryUnitExpected({
      label: "Camelry",
      culture: 2,
      classes: 4154,
      maxHp: 125,
      lineOfSight: 16,
      movementSpeed: 6,
      armor: [0.15, 0.3, 0.99],
      attack: {
        kind: "melee",
        damage: [8, 0, 0],
        range: 0.3,
        aggroRange: 16,
        cooldownTicks: 30,
        bonuses: [{ target: { kind: "classes", classes: 8 }, multiplier: 1.75 }],
      },
      bodyRadius: 0.7,
      cost: [50, 0, 70, 0],
      buildTicks: 180,
      populationCost: 3,
      requiredAge: 2,
      requiredGod: 255,
      prerequisiteBuildings: [30],
      trainedAt: [{ type: 30, commandSlot: 1 }],
    }),
  },
  {
    family: "ordinary-melee",
    id: 72,
    key: "egyptian-war-elephant",
    source: source("egyptian", 553, "War Elephant", "war elephant_anim.txt"),
    expected: ordinaryUnitExpected({
      label: "War Elephant",
      culture: 2,
      classes: 4154,
      maxHp: 450,
      lineOfSight: 16,
      movementSpeed: 2.9,
      armor: [0.1, 0.4, 0.99],
      attack: {
        kind: "melee",
        damage: [12, 0, 0],
        range: 0.3,
        aggroRange: 16,
        cooldownTicks: 30,
        bonuses: [{ target: { kind: "classes", classes: 64 }, multiplier: 3 }],
      },
      bodyRadius: 0.99,
      cost: [180, 0, 70, 0],
      buildTicks: 300,
      populationCost: 5,
      requiredAge: 2,
      requiredGod: 255,
      prerequisiteBuildings: [30],
      trainedAt: [{ type: 30, commandSlot: 2 }],
    }),
  },
] as const satisfies readonly UnitReferenceSpec[];
