import { ordinaryUnitExpected, type UnitReferenceSpec } from "../unit-reference-schema";

const TRIAL_PROTO_SHA256 = "464520f1ea00b36e1872bf5a59831408c819c205e56f055c7b2e8bdf53719da2";
const GREEK_ASSET_INVENTORY_SHA256 =
  "b87dbdf96d2d020b4f885edff58c96df028064fc00f012124a597495e14b6c34";
const EGYPTIAN_ASSET_INVENTORY_SHA256 =
  "ba7b5c96ff3f7977d28ec97ca699e479b2d38fff9d5f7a605516a2dfe2b62d8e";
const TOXOTES_ANIMATION_SHA256 = "1115ec498271c3afd8b18d7056796f578657228e2e4db55f0ddf9e5fa7882483";
const PELTAST_ANIMATION_SHA256 = "1918d258d2ebaf0722a20066ed23afdf71ed066aeee907e8cac0145c37b453b0";
const GASTRAPHETES_ANIMATION_SHA256 =
  "64e2ab0c57b7875ad8c2963bbffb9c411ad46125d46cc6c9761ed8da7b5e8f5a";
const SLINGER_ANIMATION_SHA256 = "6ffb7e300febfab94b3cf1e6e9865fad846feddf76cff1c176de973311974332";
const CHARIOT_ARCHER_ANIMATION_SHA256 =
  "0ecaa55cde2202e4ab3d1683ae05c7e70e8ffe791f087bf4e44740dd83453d60";
const REVIEW_COMMIT = "5614ca84f2407d2c5bea9872950669cc90b82e80";

export const GATE_B_UNIT_REFERENCES = [
  {
    family: "ordinary-projectile",
    id: 81,
    key: "greek-toxotes",
    source: {
      stage: "final",
      culture: "greek",
      ruleset: "Age of Mythology Classic",
      trialProto: {
        sha256: TRIAL_PROTO_SHA256,
        unitId: 444,
        unitName: "Toxotes",
      },
      assetInventory: {
        sha256: GREEK_ASSET_INVENTORY_SHA256,
        rosterName: "Toxotes",
        rootAnimation: "toxotes_anim.txt",
        attackRelease: {
          sha256: TOXOTES_ANIMATION_SHA256,
          action: "RangedAttack",
          tag: "Attack",
          fraction: 0.4,
        },
      },
      trialDeltas: [],
      finalRulesetReview: {
        commit: REVIEW_COMMIT,
        scope:
          "Complete Toxotes runtime reference, including its producer assignment, attack-cycle timing, projectile identity, and fields absent from the Trial proto.",
      },
    },
    expected: ordinaryUnitExpected({
      label: "Toxotes",
      culture: 1,
      classes: 1042,
      maxHp: 60,
      lineOfSight: 19,
      movementSpeed: 4,
      armor: [0.15, 0.15, 0.99],
      attack: {
        kind: "projectile",
        damage: [0, 6.5, 0],
        range: 15,
        aggroRange: 19,
        cooldownTicks: 20,
        bonuses: [{ target: { kind: "unit", key: "norse-raiding-cavalry" }, multiplier: 0.9 }],
        launchDelayTicks: 8,
        accuracy: 0.8,
        accuracyReductionFactor: 1.5,
        aimBonus: 15,
        spreadFactor: 0.25,
        maxSpread: 5,
        trackRating: 5,
        unintentionalDamageMultiplier: 0.3,
        projectile: {
          type: 0,
          speed: 30,
          lifespanTicks: 40,
          collisionRadius: 0.1,
        },
      },
      bodyRadius: 0.49,
      cost: [0, 55, 35, 0],
      buildTicks: 300,
      populationCost: 2,
      requiredAge: 1,
      requiredGod: 255,
      prerequisiteBuildings: [24],
      trainedAt: [{ type: 24, commandSlot: 0 }],
    }),
  },
  {
    family: "ordinary-projectile",
    id: 82,
    key: "greek-peltast",
    source: {
      stage: "final",
      culture: "greek",
      ruleset: "Age of Mythology Classic",
      trialProto: {
        sha256: TRIAL_PROTO_SHA256,
        unitId: 443,
        unitName: "Peltast",
      },
      assetInventory: {
        sha256: GREEK_ASSET_INVENTORY_SHA256,
        rosterName: "Peltast",
        rootAnimation: "peltast_anim.txt",
        attackRelease: {
          sha256: PELTAST_ANIMATION_SHA256,
          action: "RangedAttack",
          tag: "Attack",
          fraction: 0.4,
        },
      },
      trialDeltas: [],
      finalRulesetReview: {
        commit: "427d43ad198d8c8e67d21ab0530e42a8cd4c2945",
        scope:
          "Complete Peltast runtime reference, including exact counter bonuses, javelin identity, producer assignment, attack-cycle timing, and media.",
      },
    },
    expected: ordinaryUnitExpected({
      label: "Peltast",
      culture: 1,
      classes: 1042,
      maxHp: 70,
      lineOfSight: 20,
      movementSpeed: 4,
      armor: [0.15, 0.2, 0.99],
      attack: {
        kind: "projectile",
        damage: [0, 3, 0],
        range: 16,
        aggroRange: 20,
        cooldownTicks: 30,
        bonuses: [
          { target: { kind: "classes", classes: 1024 }, multiplier: 4 },
          { target: { kind: "unit", key: "norse-throwing-axeman" }, multiplier: 2 },
        ],
        launchDelayTicks: 12,
        accuracy: 0.8,
        accuracyReductionFactor: 1.5,
        aimBonus: 15,
        spreadFactor: 0.25,
        maxSpread: 5,
        trackRating: 5,
        unintentionalDamageMultiplier: 0.3,
        projectile: {
          type: 1,
          speed: 30,
          lifespanTicks: 40,
          collisionRadius: 0.1,
        },
      },
      bodyRadius: 0.49,
      cost: [0, 60, 20, 0],
      buildTicks: 180,
      populationCost: 2,
      requiredAge: 2,
      requiredGod: 255,
      prerequisiteBuildings: [24],
      trainedAt: [{ type: 24, commandSlot: 1 }],
    }),
  },
  {
    family: "ordinary-projectile",
    id: 83,
    key: "greek-gastraphetes",
    source: {
      stage: "final",
      culture: "greek",
      ruleset: "Age of Mythology Classic",
      trialProto: {
        sha256: TRIAL_PROTO_SHA256,
        unitId: 594,
        unitName: "Crossbowman",
      },
      assetInventory: {
        sha256: GREEK_ASSET_INVENTORY_SHA256,
        rosterName: "Gastraphetes",
        rootAnimation: "crossbowman_anim.txt",
        attackRelease: {
          sha256: GASTRAPHETES_ANIMATION_SHA256,
          action: "RangedAttack",
          tag: "Attack",
          fraction: 0.16,
        },
      },
      trialDeltas: [
        {
          field: "label",
          trial: "Crossbowman",
          final: "Gastraphetes",
          reason:
            "The Classic proto uses the internal Crossbowman identity; the hashed Greek asset inventory maps the shipped roster name Gastraphetes to crossbowman_anim.txt.",
        },
      ],
      finalRulesetReview: {
        commit: "c2be3174aa3bedbc67edca5152dac9f914ceef44",
        scope:
          "Complete Gastraphetes runtime reference, including its public identity alias, Hades Fortress assignment, arrow identity, attack-cycle timing, and media.",
      },
    },
    expected: ordinaryUnitExpected({
      label: "Gastraphetes",
      culture: 1,
      classes: 1042,
      maxHp: 60,
      lineOfSight: 28,
      movementSpeed: 3.8,
      armor: [0.15, 0.15, 0.99],
      attack: {
        kind: "projectile",
        damage: [0, 8, 6],
        range: 24,
        aggroRange: 28,
        cooldownTicks: 42,
        bonuses: [],
        launchDelayTicks: 7,
        accuracy: 0.6,
        accuracyReductionFactor: 1.5,
        aimBonus: 15,
        spreadFactor: 0.25,
        maxSpread: 5,
        trackRating: 5,
        unintentionalDamageMultiplier: 0.3,
        projectile: {
          type: 0,
          speed: 30,
          lifespanTicks: 40,
          collisionRadius: 0.1,
        },
      },
      bodyRadius: 0.49,
      cost: [0, 120, 80, 0],
      buildTicks: 280,
      populationCost: 3,
      requiredAge: 3,
      requiredGod: 2,
      prerequisiteBuildings: [26],
      trainedAt: [{ type: 26, commandSlot: 6 }],
    }),
  },
  {
    family: "ordinary-projectile",
    id: 128,
    key: "egyptian-slinger",
    source: {
      stage: "final",
      culture: "egyptian",
      ruleset: "Age of Mythology Classic",
      trialProto: {
        sha256: TRIAL_PROTO_SHA256,
        unitId: 293,
        unitName: "Slinger",
      },
      assetInventory: {
        sha256: EGYPTIAN_ASSET_INVENTORY_SHA256,
        rosterName: "Slinger",
        rootAnimation: "slinger_anim.txt",
        attackRelease: {
          sha256: SLINGER_ANIMATION_SHA256,
          action: "RangedAttack",
          tag: "Attack",
          fraction: 0.4,
        },
      },
      trialDeltas: [],
      finalRulesetReview: {
        commit: "9379070420145533202cd4e14787a7af28c4c420",
        scope:
          "Complete Slinger runtime reference, including exact counter bonuses, sling-stone identity, producer assignment, attack-cycle timing, and media.",
      },
    },
    expected: ordinaryUnitExpected({
      label: "Slinger",
      culture: 2,
      classes: 5138,
      maxHp: 65,
      lineOfSight: 20,
      movementSpeed: 4,
      armor: [0.15, 0.2, 0.99],
      attack: {
        kind: "projectile",
        damage: [0, 3, 0],
        range: 16,
        aggroRange: 20,
        cooldownTicks: 20,
        bonuses: [
          { target: { kind: "classes", classes: 1024 }, multiplier: 4 },
          { target: { kind: "unit", key: "norse-throwing-axeman" }, multiplier: 3 },
          { target: { kind: "unit", key: "greek-hypaspist" }, multiplier: 1.25 },
          { target: { kind: "unit", key: "egyptian-axeman" }, multiplier: 1.25 },
        ],
        launchDelayTicks: 8,
        accuracy: 0.8,
        accuracyReductionFactor: 1.5,
        aimBonus: 15,
        spreadFactor: 0.25,
        maxSpread: 5,
        trackRating: 5,
        unintentionalDamageMultiplier: 0.3,
        projectile: {
          type: 2,
          speed: 30,
          lifespanTicks: 40,
          collisionRadius: 0.1,
        },
      },
      bodyRadius: 0.49,
      cost: [0, 60, 24, 0],
      buildTicks: 280,
      populationCost: 2,
      requiredAge: 1,
      requiredGod: 255,
      prerequisiteBuildings: [23],
      trainedAt: [{ type: 23, commandSlot: 2 }],
    }),
  },
  {
    family: "ordinary-projectile",
    id: 129,
    key: "egyptian-chariot-archer",
    source: {
      stage: "final",
      culture: "egyptian",
      ruleset: "Age of Mythology Classic",
      trialProto: {
        sha256: TRIAL_PROTO_SHA256,
        unitId: 449,
        unitName: "Chariot Archer",
      },
      assetInventory: {
        sha256: EGYPTIAN_ASSET_INVENTORY_SHA256,
        rosterName: "Chariot Archer",
        rootAnimation: "chariot archer_anim.txt",
        attackRelease: {
          sha256: CHARIOT_ARCHER_ANIMATION_SHA256,
          action: "RangedAttack",
          tag: "Attack",
          fraction: 0.64,
        },
      },
      trialDeltas: [],
      finalRulesetReview: {
        commit: "e50a87b6835e18ae4ff4593252939b4b6b3c856e",
        scope:
          "Complete Chariot Archer runtime reference, including Classic non-cavalry classification, Migdol assignment, arrow identity, attack-cycle timing, and media.",
      },
    },
    expected: ordinaryUnitExpected({
      label: "Chariot Archer",
      culture: 2,
      classes: 5138,
      maxHp: 90,
      lineOfSight: 24,
      movementSpeed: 5.3,
      armor: [0.3, 0.2, 0.99],
      attack: {
        kind: "projectile",
        damage: [0, 8.5, 0],
        range: 20,
        aggroRange: 24,
        cooldownTicks: 30,
        bonuses: [],
        launchDelayTicks: 19,
        accuracy: 0.8,
        accuracyReductionFactor: 1.5,
        aimBonus: 15,
        spreadFactor: 0.25,
        maxSpread: 5,
        trackRating: 5,
        unintentionalDamageMultiplier: 0.3,
        projectile: {
          type: 0,
          speed: 30,
          lifespanTicks: 40,
          collisionRadius: 0.1,
        },
      },
      bodyRadius: 0.7,
      cost: [0, 100, 40, 0],
      buildTicks: 120,
      populationCost: 3,
      requiredAge: 2,
      requiredGod: 255,
      prerequisiteBuildings: [30],
      trainedAt: [{ type: 30, commandSlot: 0 }],
    }),
  },
] as const satisfies readonly UnitReferenceSpec[];
