import {
  MOVEMENT_DOMAIN_WATER,
  UNIT_CLASS_BUILDING,
  UNIT_CLASS_MILITARY,
  UNIT_CLASS_MELEE,
  UNIT_CLASS_MYTH,
  UNIT_CLASS_RELIC,
  UNIT_CLASS_SHIP,
  UNIT_CLASS_SIEGE,
  UNIT_CLASS_TITAN,
  UNIT_CLASS_TRANSPORT_SHIP,
} from "../unit-type-schema";
import { navalUnitExpected, type UnitReferenceSpec } from "../unit-reference-schema";

const TRIAL_PROTO_SHA256 = "464520f1ea00b36e1872bf5a59831408c819c205e56f055c7b2e8bdf53719da2";
const GREEK_ASSET_INVENTORY_SHA256 =
  "b87dbdf96d2d020b4f885edff58c96df028064fc00f012124a597495e14b6c34";
const EGYPTIAN_ASSET_INVENTORY_SHA256 =
  "ba7b5c96ff3f7977d28ec97ca699e479b2d38fff9d5f7a605516a2dfe2b62d8e";

export const GATE_E_UNIT_REFERENCES = [
  {
    family: "naval",
    id: 88,
    key: "greek-fishing-ship",
    source: {
      stage: "candidate",
      culture: "greek",
      ruleset: "Age of Mythology Classic",
      trialProto: {
        sha256: TRIAL_PROTO_SHA256,
        unitId: 338,
        unitName: "Fishing Ship Greek",
      },
      assetInventory: {
        sha256: GREEK_ASSET_INVENTORY_SHA256,
        rosterName: "Fishing Ship",
        rootAnimation: "fishing ship greek_anim.txt",
      },
      trialDeltas: [
        {
          field: "label",
          trial: "Fishing Ship Greek",
          final: "Fishing Ship",
          reason: "The launch UI omits the culture suffix used by the internal proto.",
        },
      ],
    },
    expected: navalUnitExpected({
      label: "Fishing Ship",
      culture: 1,
      classes: UNIT_CLASS_SHIP,
      maxHp: 120,
      lineOfSight: 20,
      movementSpeed: 4.8,
      movementDomain: MOVEMENT_DOMAIN_WATER,
      workRange: 1,
      gather: { capacity: 25, ratePerSecond: 0.61 },
      armor: [0.6, 0.5, 0.05],
      attack: null,
      bodyRadius: 0.99,
      cost: [0, 50, 0, 0],
      buildTicks: 280,
      populationCost: 1,
      requiredAge: 0,
      requiredGod: 255,
      prerequisiteBuildings: [],
      trainedAt: [{ type: 27, commandSlot: 0 }],
    }),
  },
  {
    family: "naval",
    id: 89,
    key: "greek-transport-ship",
    source: {
      stage: "candidate",
      culture: "greek",
      ruleset: "Age of Mythology Classic",
      trialProto: { sha256: TRIAL_PROTO_SHA256, unitId: 472, unitName: "Transport Ship Greek" },
      assetInventory: {
        sha256: GREEK_ASSET_INVENTORY_SHA256,
        rosterName: "Transport Ship",
        rootAnimation: "transport ship greek_anim.txt",
      },
      trialDeltas: [
        {
          field: "label",
          trial: "Transport Ship Greek",
          final: "Transport Ship",
          reason: "The released UI omits the culture suffix used by the internal proto.",
        },
      ],
    },
    expected: navalUnitExpected({
      label: "Transport Ship",
      culture: 1,
      classes: UNIT_CLASS_SHIP | UNIT_CLASS_TRANSPORT_SHIP,
      maxHp: 180,
      lineOfSight: 14,
      movementSpeed: 5.3,
      movementDomain: MOVEMENT_DOMAIN_WATER,
      workRange: null,
      armor: [0.4, 0.8, 0.05],
      attack: null,
      garrison: {
        capacity: 10,
        enterRange: 4,
        validOccupants: [
          {
            kind: "classes",
            classes: 0,
            excludedClasses:
              UNIT_CLASS_BUILDING | UNIT_CLASS_RELIC | UNIT_CLASS_SHIP | UNIT_CLASS_TITAN,
          },
        ],
        attackMultiplierPerOccupant: 0,
        ejectOnDeath: false,
      },
      bodyRadius: 0.99,
      cost: [0, 120, 0, 0],
      buildTicks: 380,
      populationCost: 2,
      requiredAge: 1,
      requiredGod: 255,
      prerequisiteBuildings: [],
      trainedAt: [{ type: 27, commandSlot: 1 }],
    }),
  },
  {
    family: "naval",
    id: 91,
    key: "greek-pentekonter",
    source: {
      stage: "candidate",
      culture: "greek",
      ruleset: "Age of Mythology Classic",
      trialProto: { sha256: TRIAL_PROTO_SHA256, unitId: 503, unitName: "Ramming Ship Greek" },
      assetInventory: {
        sha256: GREEK_ASSET_INVENTORY_SHA256,
        rosterName: "Pentekonter",
        rootAnimation: "ramming ship greek_anim.txt",
        meleeAttackCycles: [
          {
            sha256: "597c91cd6913d99db41ab0a354c89ad7795717497ff5995025a1514edbf4c80d",
            action: "attack",
            tag: "Attack",
            fraction: 0.08,
            durationTicks: 30,
            modelDurationTicks: 40,
            model: "naval g pentekonter_attacka.glb",
            modelSha256: "8e9de163ab52c76a18d19bbb164c9162c57871a8720e5690dcc2afe4046319fb",
          },
        ],
      },
      trialDeltas: [
        {
          field: "label",
          trial: "Ramming Ship Greek",
          final: "Pentekonter",
          reason: "The released UI uses the culture-specific Pentekonter name.",
        },
        {
          field: "armor",
          trial: [0.3, 0.2, 0.75],
          final: [0.3, 0.15, 0.75],
          reason: "Launch Classic reduced hammer-ship pierce armor from the Trial's 20% to 15%.",
        },
      ],
    },
    expected: navalUnitExpected({
      label: "Pentekonter",
      culture: 1,
      classes: UNIT_CLASS_MILITARY | UNIT_CLASS_MELEE | UNIT_CLASS_SHIP,
      maxHp: 240,
      lineOfSight: 16,
      movementSpeed: 7,
      movementDomain: MOVEMENT_DOMAIN_WATER,
      workRange: null,
      armor: [0.3, 0.15, 0.75],
      attack: {
        kind: "melee",
        damage: [20, 0, 0],
        range: 2,
        aggroRange: 16,
        cooldownTicks: 30,
        bonuses: [],
        cycleVariants: [{ actionTicks: 30, impactDelayTicks: 2 }],
      },
      bodyRadius: 0.7,
      cost: [0, 100, 50, 0],
      buildTicks: 180,
      populationCost: 2,
      requiredAge: 2,
      requiredGod: 255,
      prerequisiteBuildings: [],
      trainedAt: [{ type: 27, commandSlot: 3 }],
    }),
  },
  {
    family: "naval",
    id: 90,
    key: "greek-trireme",
    source: {
      stage: "candidate",
      culture: "greek",
      ruleset: "Age of Mythology Classic",
      trialProto: { sha256: TRIAL_PROTO_SHA256, unitId: 337, unitName: "Trireme" },
      assetInventory: {
        sha256: GREEK_ASSET_INVENTORY_SHA256,
        rosterName: "Trireme",
        rootAnimation: "trireme_anim.txt",
        attackRelease: {
          sha256: "6fc0361799aef176e96eb32881a90b5cecbe67b474bf636efed4b7f8a9709437",
          action: "RangedAttack",
          tag: "Attack",
          fraction: 0.4,
        },
      },
      trialDeltas: [],
    },
    expected: navalUnitExpected({
      label: "Trireme",
      culture: 1,
      classes: UNIT_CLASS_MILITARY | UNIT_CLASS_SHIP,
      maxHp: 290,
      lineOfSight: 24,
      movementSpeed: 6,
      movementDomain: MOVEMENT_DOMAIN_WATER,
      workRange: null,
      armor: [0.3, 0.2, 0.1],
      attack: {
        kind: "projectile",
        damage: [0, 6, 0],
        range: 12,
        aggroRange: 24,
        cooldownTicks: 30,
        bonuses: [
          { target: { kind: "classes", classes: UNIT_CLASS_TRANSPORT_SHIP }, multiplier: 3 },
        ],
        launchDelayTicks: 12,
        accuracy: 0.8,
        accuracyReductionFactor: 2,
        aimBonus: 15,
        spreadFactor: 0.25,
        maxSpread: 5,
        trackRating: 10,
        unintentionalDamageMultiplier: 0.3,
        projectileCount: 3,
        projectile: { type: 0, speed: 30, lifespanTicks: 40, collisionRadius: 0.1 },
      },
      bodyRadius: 0.99,
      cost: [0, 100, 50, 0],
      buildTicks: 280,
      populationCost: 2,
      requiredAge: 1,
      requiredGod: 255,
      prerequisiteBuildings: [],
      trainedAt: [{ type: 27, commandSlot: 2 }],
    }),
  },
  {
    family: "naval",
    id: 92,
    key: "greek-juggernaut",
    source: {
      stage: "candidate",
      culture: "greek",
      ruleset: "Age of Mythology Classic",
      trialProto: { sha256: TRIAL_PROTO_SHA256, unitId: 504, unitName: "Siege Ship Greek" },
      assetInventory: {
        sha256: GREEK_ASSET_INVENTORY_SHA256,
        rosterName: "Juggernaut",
        rootAnimation: "siege ship greek_anim.txt",
        attackRelease: {
          sha256: "576ba124b4cded7be483d2be07141a62d41b0057e6f7f88aa3644fce0dcf0c0b",
          action: "RangedAttack",
          tag: "Attack",
          fraction: 0.4,
          durationTicks: 70,
          modelDurationTicks: 20,
          model: "naval g juggernaut_attacka.glb",
          modelSha256: "3dd402bf4e49399e0bc5102aaef6a366ad2b13970bd07a16aa6cce84ea1f0ebd",
        },
      },
      trialDeltas: [
        {
          field: "label",
          trial: "Siege Ship Greek",
          final: "Juggernaut",
          reason: "The released UI uses the culture-specific Juggernaut name.",
        },
        {
          field: "attack.bonuses",
          trial: [{ target: { kind: "classes", classes: UNIT_CLASS_BUILDING }, multiplier: 0.5 }],
          final: [
            {
              target: {
                kind: "classes",
                classes: UNIT_CLASS_SHIP,
                excludedClasses: UNIT_CLASS_MYTH,
              },
              multiplier: 3.5,
            },
            { target: { kind: "classes", classes: UNIT_CLASS_MYTH }, multiplier: 3.5 },
            { target: { kind: "classes", classes: UNIT_CLASS_BUILDING }, multiplier: 1.75 },
          ],
          reason:
            "Launch Classic applies the released siege-ship counters rather than the Trial action's provisional building modifier.",
        },
      ],
    },
    expected: navalUnitExpected({
      label: "Juggernaut",
      culture: 1,
      classes: UNIT_CLASS_MILITARY | UNIT_CLASS_SHIP | UNIT_CLASS_SIEGE,
      maxHp: 480,
      lineOfSight: 24,
      movementSpeed: 4.8,
      movementDomain: MOVEMENT_DOMAIN_WATER,
      workRange: null,
      armor: [0.1, 0.5, 0.1],
      attack: {
        kind: "projectile",
        damage: [0, 0, 6],
        range: 18,
        aggroRange: 24,
        cooldownTicks: 70,
        bonuses: [
          {
            target: {
              kind: "classes",
              classes: UNIT_CLASS_SHIP,
              excludedClasses: UNIT_CLASS_MYTH,
            },
            multiplier: 3.5,
          },
          { target: { kind: "classes", classes: UNIT_CLASS_MYTH }, multiplier: 3.5 },
          { target: { kind: "classes", classes: UNIT_CLASS_BUILDING }, multiplier: 1.75 },
        ],
        autoAcquireBuildings: true,
        launchDelayTicks: 28,
        accuracy: 0.8,
        accuracyReductionFactor: 2,
        aimBonus: 15,
        spreadFactor: 0.25,
        maxSpread: 5,
        trackRating: 4,
        unintentionalDamageMultiplier: 0.5,
        projectileCount: 4,
        projectile: { type: 8, speed: 30, lifespanTicks: 40, collisionRadius: 0.1 },
      },
      bodyRadius: 0.99,
      cost: [0, 100, 100, 0],
      buildTicks: 340,
      populationCost: 3,
      requiredAge: 2,
      requiredGod: 255,
      prerequisiteBuildings: [],
      trainedAt: [{ type: 27, commandSlot: 4 }],
    }),
  },
  {
    family: "naval",
    id: 135,
    key: "egyptian-fishing-ship",
    source: {
      stage: "candidate",
      culture: "egyptian",
      ruleset: "Age of Mythology Classic",
      trialProto: {
        sha256: TRIAL_PROTO_SHA256,
        unitId: 480,
        unitName: "Fishing Ship Egyptian",
      },
      assetInventory: {
        sha256: EGYPTIAN_ASSET_INVENTORY_SHA256,
        rosterName: "Fishing Ship",
        rootAnimation: "fishing ship egyptian_anim.txt",
      },
      trialDeltas: [
        {
          field: "label",
          trial: "Fishing Ship Egyptian",
          final: "Fishing Ship",
          reason: "The launch UI omits the culture suffix used by the internal proto.",
        },
      ],
    },
    expected: navalUnitExpected({
      label: "Fishing Ship",
      culture: 2,
      classes: UNIT_CLASS_SHIP,
      maxHp: 120,
      lineOfSight: 20,
      movementSpeed: 4.8,
      movementDomain: MOVEMENT_DOMAIN_WATER,
      workRange: 1,
      gather: { capacity: 25, ratePerSecond: 0.54 },
      construction: { range: 4, ratePerSecond: 0.28, baselineRatePerSecond: 0.99 },
      armor: [0.6, 0.5, 0.05],
      attack: null,
      bodyRadius: 0.99,
      cost: [0, 50, 0, 0],
      buildTicks: 280,
      populationCost: 1,
      requiredAge: 0,
      requiredGod: 255,
      prerequisiteBuildings: [],
      trainedAt: [{ type: 32, commandSlot: 0 }],
    }),
  },
  {
    family: "naval",
    id: 137,
    key: "egyptian-kebenit",
    source: {
      stage: "candidate",
      culture: "egyptian",
      ruleset: "Age of Mythology Classic",
      trialProto: { sha256: TRIAL_PROTO_SHA256, unitId: 473, unitName: "Kebenit" },
      assetInventory: {
        sha256: EGYPTIAN_ASSET_INVENTORY_SHA256,
        rosterName: "Kebenit",
        rootAnimation: "kebenit_anim.txt",
        attackRelease: {
          sha256: "22543d280e70ef3182a99d3d72ce540eb43a11fd563bae48f4efa0b0a50044eb",
          action: "RangedAttack",
          tag: "Attack",
          fraction: 0.4,
        },
      },
      trialDeltas: [],
    },
    expected: navalUnitExpected({
      label: "Kebenit",
      culture: 2,
      classes: UNIT_CLASS_MILITARY | UNIT_CLASS_SHIP,
      maxHp: 290,
      lineOfSight: 24,
      movementSpeed: 6,
      movementDomain: MOVEMENT_DOMAIN_WATER,
      workRange: null,
      armor: [0.3, 0.2, 0.1],
      attack: {
        kind: "projectile",
        damage: [0, 6, 0],
        range: 12,
        aggroRange: 24,
        cooldownTicks: 30,
        bonuses: [
          { target: { kind: "classes", classes: UNIT_CLASS_TRANSPORT_SHIP }, multiplier: 3 },
        ],
        launchDelayTicks: 12,
        accuracy: 0.8,
        accuracyReductionFactor: 2,
        aimBonus: 15,
        spreadFactor: 0.25,
        maxSpread: 5,
        trackRating: 10,
        unintentionalDamageMultiplier: 0.3,
        projectileCount: 3,
        projectile: { type: 0, speed: 30, lifespanTicks: 40, collisionRadius: 0.1 },
      },
      bodyRadius: 0.99,
      cost: [0, 100, 50, 0],
      buildTicks: 280,
      populationCost: 2,
      requiredAge: 1,
      requiredGod: 255,
      prerequisiteBuildings: [],
      trainedAt: [{ type: 32, commandSlot: 2 }],
    }),
  },
  {
    family: "naval",
    id: 136,
    key: "egyptian-transport-ship",
    source: {
      stage: "candidate",
      culture: "egyptian",
      ruleset: "Age of Mythology Classic",
      trialProto: {
        sha256: TRIAL_PROTO_SHA256,
        unitId: 481,
        unitName: "Transport Ship Egyptian",
      },
      assetInventory: {
        sha256: EGYPTIAN_ASSET_INVENTORY_SHA256,
        rosterName: "Transport Ship",
        rootAnimation: "transport ship egyptian_anim.txt",
      },
      trialDeltas: [
        {
          field: "label",
          trial: "Transport Ship Egyptian",
          final: "Transport Ship",
          reason: "The released UI omits the culture suffix used by the internal proto.",
        },
      ],
    },
    expected: navalUnitExpected({
      label: "Transport Ship",
      culture: 2,
      classes: UNIT_CLASS_SHIP | UNIT_CLASS_TRANSPORT_SHIP,
      maxHp: 180,
      lineOfSight: 14,
      movementSpeed: 5.3,
      movementDomain: MOVEMENT_DOMAIN_WATER,
      workRange: null,
      armor: [0.4, 0.8, 0.05],
      attack: null,
      garrison: {
        capacity: 10,
        enterRange: 4,
        validOccupants: [
          {
            kind: "classes",
            classes: 0,
            excludedClasses:
              UNIT_CLASS_BUILDING | UNIT_CLASS_RELIC | UNIT_CLASS_SHIP | UNIT_CLASS_TITAN,
          },
        ],
        attackMultiplierPerOccupant: 0,
        ejectOnDeath: false,
      },
      bodyRadius: 0.99,
      cost: [0, 120, 0, 0],
      buildTicks: 380,
      populationCost: 2,
      requiredAge: 1,
      requiredGod: 255,
      prerequisiteBuildings: [],
      trainedAt: [{ type: 32, commandSlot: 1 }],
    }),
  },
  {
    family: "naval",
    id: 138,
    key: "egyptian-ramming-galley",
    source: {
      stage: "candidate",
      culture: "egyptian",
      ruleset: "Age of Mythology Classic",
      trialProto: {
        sha256: TRIAL_PROTO_SHA256,
        unitId: 507,
        unitName: "Ramming Ship Egyptian",
      },
      assetInventory: {
        sha256: EGYPTIAN_ASSET_INVENTORY_SHA256,
        rosterName: "Ramming Galley",
        rootAnimation: "ramming ship egyptian_anim.txt",
        meleeAttackCycles: [
          {
            sha256: "d25193df31882204654ac52bccbda8c031c361bd6115e9939e89bc16eb1e77b7",
            action: "attack",
            tag: "Attack",
            fraction: 0.08,
            durationTicks: 30,
            modelDurationTicks: 40,
            model: "naval e ramming galley_attacka.glb",
            modelSha256: "2071f96d1f92c9eb90bb2e1c2910af5a38f0c319b1c4b6a217c6de72fffa30e2",
          },
        ],
      },
      trialDeltas: [
        {
          field: "label",
          trial: "Ramming Ship Egyptian",
          final: "Ramming Galley",
          reason: "The released UI uses the culture-specific Ramming Galley name.",
        },
        {
          field: "armor",
          trial: [0.3, 0.2, 0.75],
          final: [0.3, 0.15, 0.75],
          reason: "Launch Classic reduced hammer-ship pierce armor from the Trial's 20% to 15%.",
        },
      ],
    },
    expected: navalUnitExpected({
      label: "Ramming Galley",
      culture: 2,
      classes: UNIT_CLASS_MILITARY | UNIT_CLASS_MELEE | UNIT_CLASS_SHIP,
      maxHp: 240,
      lineOfSight: 16,
      movementSpeed: 7,
      movementDomain: MOVEMENT_DOMAIN_WATER,
      workRange: null,
      armor: [0.3, 0.15, 0.75],
      attack: {
        kind: "melee",
        damage: [20, 0, 0],
        range: 2,
        aggroRange: 16,
        cooldownTicks: 30,
        bonuses: [],
        cycleVariants: [{ actionTicks: 30, impactDelayTicks: 2 }],
      },
      bodyRadius: 0.7,
      cost: [0, 100, 50, 0],
      buildTicks: 180,
      populationCost: 2,
      requiredAge: 2,
      requiredGod: 255,
      prerequisiteBuildings: [],
      trainedAt: [{ type: 32, commandSlot: 3 }],
    }),
  },
  {
    family: "naval",
    id: 139,
    key: "egyptian-war-barge",
    source: {
      stage: "candidate",
      culture: "egyptian",
      ruleset: "Age of Mythology Classic",
      trialProto: { sha256: TRIAL_PROTO_SHA256, unitId: 509, unitName: "Siege Ship Egyptian" },
      assetInventory: {
        sha256: EGYPTIAN_ASSET_INVENTORY_SHA256,
        rosterName: "War Barge",
        rootAnimation: "siege ship egyptian_anim.txt",
        attackRelease: {
          sha256: "1a6feed4540378efb328f0e0641f9026e92c5cf4ab005ad012d2b71c95ff1a8f",
          action: "RangedAttack",
          tag: "Attack",
          fraction: 0.4,
          durationTicks: 70,
          modelDurationTicks: 20,
          model: "naval e war barge_attacka.glb",
          modelSha256: "6f8506e231d314e35def51415505b428b628fa1a9318239f5ade886403a5a9e0",
        },
      },
      trialDeltas: [
        {
          field: "label",
          trial: "Siege Ship Egyptian",
          final: "War Barge",
          reason: "The released UI uses the culture-specific War Barge name.",
        },
        {
          field: "attack.damage",
          trial: [0, 0, 6],
          final: [0, 0, 7],
          reason: "The released Classic War Barge deals seven crush DPS per projectile.",
        },
        {
          field: "attack.bonuses",
          trial: [{ target: { kind: "classes", classes: UNIT_CLASS_BUILDING }, multiplier: 0.5 }],
          final: [
            {
              target: {
                kind: "classes",
                classes: UNIT_CLASS_SHIP,
                excludedClasses: UNIT_CLASS_MYTH,
              },
              multiplier: 3.5,
            },
            { target: { kind: "classes", classes: UNIT_CLASS_MYTH }, multiplier: 3.5 },
            { target: { kind: "classes", classes: UNIT_CLASS_BUILDING }, multiplier: 1.75 },
          ],
          reason:
            "Launch Classic applies the released siege-ship counters rather than the Trial action's provisional building modifier.",
        },
      ],
    },
    expected: navalUnitExpected({
      label: "War Barge",
      culture: 2,
      classes: UNIT_CLASS_MILITARY | UNIT_CLASS_SHIP | UNIT_CLASS_SIEGE,
      maxHp: 480,
      lineOfSight: 24,
      movementSpeed: 4.8,
      movementDomain: MOVEMENT_DOMAIN_WATER,
      workRange: null,
      armor: [0.1, 0.5, 0.1],
      attack: {
        kind: "projectile",
        damage: [0, 0, 7],
        range: 18,
        aggroRange: 24,
        cooldownTicks: 70,
        bonuses: [
          {
            target: {
              kind: "classes",
              classes: UNIT_CLASS_SHIP,
              excludedClasses: UNIT_CLASS_MYTH,
            },
            multiplier: 3.5,
          },
          { target: { kind: "classes", classes: UNIT_CLASS_MYTH }, multiplier: 3.5 },
          { target: { kind: "classes", classes: UNIT_CLASS_BUILDING }, multiplier: 1.75 },
        ],
        autoAcquireBuildings: true,
        launchDelayTicks: 28,
        accuracy: 0.8,
        accuracyReductionFactor: 2,
        aimBonus: 15,
        spreadFactor: 0.25,
        maxSpread: 5,
        trackRating: 4,
        unintentionalDamageMultiplier: 0.5,
        projectileCount: 4,
        projectile: { type: 8, speed: 30, lifespanTicks: 40, collisionRadius: 0.1 },
      },
      bodyRadius: 0.99,
      cost: [0, 100, 100, 0],
      buildTicks: 340,
      populationCost: 3,
      requiredAge: 2,
      requiredGod: 255,
      prerequisiteBuildings: [],
      trainedAt: [{ type: 32, commandSlot: 4 }],
    }),
  },
] as const satisfies readonly UnitReferenceSpec[];
