import {
  PROJECTILE_ARROW,
  PROJECTILE_BALLISTA_BOLT,
  PROJECTILE_CATAPULT_STONE,
  PROJECTILE_PETROBOLOS_STONE,
} from "../../ecs/projectiles";
import {
  UNIT_CLASS_ARCHER,
  UNIT_CLASS_CARAVAN,
  UNIT_CLASS_HERO,
  UNIT_CLASS_HUMAN,
  UNIT_CLASS_INFANTRY,
  UNIT_CLASS_MILITARY,
  UNIT_CLASS_MELEE,
  UNIT_CLASS_SHIP,
  UNIT_CLASS_SIEGE,
  UNIT_CLASS_WORKER,
} from "../unit-type-schema";
import {
  economicUnitExpected,
  ordinaryUnitExpected,
  type UnitReferenceSpec,
} from "../unit-reference-schema";

const TRIAL_PROTO_SHA256 = "464520f1ea00b36e1872bf5a59831408c819c205e56f055c7b2e8bdf53719da2";
const GREEK_ASSET_INVENTORY_SHA256 =
  "b87dbdf96d2d020b4f885edff58c96df028064fc00f012124a597495e14b6c34";
const EGYPTIAN_ASSET_INVENTORY_SHA256 =
  "ba7b5c96ff3f7977d28ec97ca699e479b2d38fff9d5f7a605516a2dfe2b62d8e";

export const GATE_D_UNIT_REFERENCES = [
  {
    family: "exceptional-lifecycle",
    attackKind: "melee",
    id: 133,
    key: "egyptian-mercenary",
    source: {
      stage: "candidate",
      culture: "egyptian",
      ruleset: "Age of Mythology Classic",
      trialProto: {
        sha256: TRIAL_PROTO_SHA256,
        unitId: 453,
        unitName: "Mercenary",
      },
      assetInventory: {
        sha256: EGYPTIAN_ASSET_INVENTORY_SHA256,
        rosterName: "Mercenary",
        rootAnimation: "mercenary_anim.txt",
      },
      trialDeltas: [],
    },
    expected: ordinaryUnitExpected({
      label: "Mercenary",
      culture: 2,
      classes: 4150,
      maxHp: 85,
      lineOfSight: 20,
      movementSpeed: 4.3,
      armor: [0.45, 0.3, 0.99],
      attack: {
        kind: "melee",
        damage: [8, 0, 0],
        range: 0.3,
        aggroRange: 20,
        cooldownTicks: 20,
        bonuses: [],
      },
      bodyRadius: 0.49,
      cost: [0, 0, 90, 0],
      buildTicks: 20,
      lifespanTicks: 900,
      populationCost: 0,
      requiredAge: 0,
      requiredGod: 255,
      prerequisiteBuildings: [],
      trainedAt: [{ type: 19, commandSlot: 2 }],
    }),
  },
  {
    family: "exceptional-lifecycle",
    attackKind: "melee",
    id: 157,
    key: "egyptian-mercenary-cavalry",
    source: {
      stage: "candidate",
      culture: "egyptian",
      ruleset: "Age of Mythology Classic",
      trialProto: {
        sha256: TRIAL_PROTO_SHA256,
        unitId: 464,
        unitName: "Mercenary Cavalry",
      },
      assetInventory: {
        sha256: EGYPTIAN_ASSET_INVENTORY_SHA256,
        rosterName: "Mercenary Cavalry",
        rootAnimation: "mercenary cavalry_anim.txt",
        meleeAttackCycles: [
          {
            sha256: "7f67a4fa5c00254ea84d3ec54e59b7e3c3ddc5f0892cdd0aec28f7bbb0e52ccb",
            action: "attack",
            tag: "Attack",
            fraction: 0.5,
            durationTicks: 20,
            model: "cavalry e mercenary_attacka.glb",
            modelSha256: "70d1462501aeafd7e8b44e2158ee5f033384e604e35334932aa2d52a099b142d",
          },
          {
            sha256: "7f67a4fa5c00254ea84d3ec54e59b7e3c3ddc5f0892cdd0aec28f7bbb0e52ccb",
            action: "attack",
            tag: "Attack",
            fraction: 0.71,
            durationTicks: 24,
            model: "cavalry e mercenary_attackb.glb",
            modelSha256: "efca663af64393b517c292b83d9ccbc89a0b24a0d7bddbff47f249fd4ba13952",
          },
          {
            sha256: "7f67a4fa5c00254ea84d3ec54e59b7e3c3ddc5f0892cdd0aec28f7bbb0e52ccb",
            action: "attack",
            tag: "Attack",
            fraction: 0.62,
            durationTicks: 17,
            model: "cavalry e mercenary_attackc.glb",
            modelSha256: "e76a994d769fbf134f71528d2328e629e77d313b5f2a57aeff8b3daf78cf136f",
          },
        ],
      },
      trialDeltas: [],
    },
    expected: ordinaryUnitExpected({
      label: "Mercenary Cavalry",
      culture: 2,
      classes: 4154,
      maxHp: 190,
      lineOfSight: 22,
      movementSpeed: 5.3,
      armor: [0.6, 0.7, 0.99],
      attack: {
        kind: "melee",
        damage: [8, 0, 0],
        range: 0.3,
        aggroRange: 22,
        cooldownTicks: 20,
        bonuses: [],
        cycleVariants: [
          { actionTicks: 20, impactDelayTicks: 10 },
          { actionTicks: 24, impactDelayTicks: 17 },
          { actionTicks: 17, impactDelayTicks: 11 },
        ],
      },
      bodyRadius: 0.7,
      cost: [0, 0, 120, 0],
      buildTicks: 60,
      lifespanTicks: 900,
      populationCost: 0,
      requiredAge: 2,
      requiredGod: 255,
      prerequisiteBuildings: [],
      trainedAt: [{ type: 19, commandSlot: 3 }],
    }),
  },
  {
    family: "exceptional-lifecycle",
    attackKind: "melee",
    id: 1,
    key: "militia",
    source: {
      stage: "candidate",
      culture: "greek",
      ruleset: "Age of Mythology Classic",
      trialProto: {
        sha256: TRIAL_PROTO_SHA256,
        unitId: 564,
        unitName: "Militia",
      },
      assetInventory: {
        sha256: GREEK_ASSET_INVENTORY_SHA256,
        rosterName: "Militia",
        rootAnimation: "militia_anim.txt",
      },
      trialDeltas: [],
    },
    expected: ordinaryUnitExpected({
      label: "Militia",
      culture: 1,
      classes: 54,
      maxHp: 100,
      lineOfSight: 20,
      movementSpeed: 4.8,
      armor: [0.3, 0.2, 0.99],
      attack: {
        kind: "melee",
        damage: [7, 0, 0],
        range: 0.3,
        aggroRange: 20,
        cooldownTicks: 20,
        bonuses: [],
      },
      bodyRadius: 0.49,
      cost: [0, 0, 0, 0],
      buildTicks: 0,
      populationCost: 1,
      requiredAge: 0,
      requiredGod: 1,
      prerequisiteBuildings: [],
      trainedAt: [],
    }),
  },
  {
    family: "exceptional-lifecycle",
    attackKind: "melee",
    id: 80,
    key: "greek-kataskopos",
    source: {
      stage: "candidate",
      culture: "greek",
      ruleset: "Age of Mythology Classic",
      trialProto: {
        sha256: TRIAL_PROTO_SHA256,
        unitId: 380,
        unitName: "Scout",
      },
      assetInventory: {
        sha256: GREEK_ASSET_INVENTORY_SHA256,
        rosterName: "Kataskopos",
        rootAnimation: "scout_anim.txt",
        meleeAttackCycles: [
          {
            sha256: "97b86acd4ec58924fab5f4ed8dafeecb4b571a9621c6c1e4aee7211b198f88fb",
            action: "attack",
            tag: "Attack",
            fraction: 0.5,
            durationTicks: 20,
            model: "cavalry g scout_attacka.glb",
            modelSha256: "54797f5af4b110f6b1383fc65d2b5b060e1535d1fef9a9875b3090894eb84403",
          },
          {
            sha256: "97b86acd4ec58924fab5f4ed8dafeecb4b571a9621c6c1e4aee7211b198f88fb",
            action: "attack",
            tag: "Attack",
            fraction: 0.66,
            durationTicks: 24,
            model: "cavalry g scout_attackb.glb",
            modelSha256: "c24dd2f84ada05aea3aeb46252ab59f2fa329c56e079390f5d939af94d2e7c7b",
          },
        ],
      },
      trialDeltas: [
        {
          field: "label",
          trial: "Scout",
          final: "Kataskopos",
          reason: "The runtime uses the localized Classic display name rather than the proto key.",
        },
      ],
    },
    expected: ordinaryUnitExpected({
      label: "Kataskopos",
      culture: 1,
      classes: 32818,
      maxHp: 70,
      lineOfSight: 14,
      movementSpeed: 5.5,
      armor: [0.1, 0.7, 0.99],
      attack: {
        kind: "melee",
        damage: [2, 0, 0],
        range: 0.1,
        aggroRange: 14,
        cooldownTicks: 20,
        bonuses: [],
        autoAcquire: false,
        cycleVariants: [
          { actionTicks: 20, impactDelayTicks: 10 },
          { actionTicks: 24, impactDelayTicks: 16 },
        ],
      },
      bodyRadius: 0.7,
      cost: [75, 0, 0, 0],
      buildTicks: 0,
      populationCost: 2,
      requiredAge: 0,
      requiredGod: 255,
      prerequisiteBuildings: [],
      trainedAt: [],
    }),
  },
  {
    family: "siege",
    attackKind: "projectile",
    id: 86,
    key: "greek-helepolis",
    source: {
      stage: "candidate",
      culture: "greek",
      ruleset: "Age of Mythology Classic",
      trialProto: {
        sha256: TRIAL_PROTO_SHA256,
        unitId: 446,
        unitName: "Helepolis",
      },
      assetInventory: {
        sha256: GREEK_ASSET_INVENTORY_SHA256,
        rosterName: "Helepolis",
        rootAnimation: "helepolis_anim.txt",
        attackRelease: {
          sha256: "b632f2171fc975edd1bc40bda613393fb813a41039110eb4617c545d44b3c591",
          action: "RangedAttack",
          tag: "Attack",
          fraction: 0.4,
          durationTicks: 40,
          model: "siege g helepolis_attacka.glb",
          modelSha256: "abfcabed4e2dcec0e87e3d3683c090217cfb61aaea88cb1b2aad18ddee118c6f",
          modelDurationTicks: 40,
        },
      },
      trialDeltas: [],
    },
    expected: ordinaryUnitExpected({
      label: "Helepolis",
      culture: 1,
      classes: 528,
      maxHp: 700,
      lineOfSight: 18,
      movementSpeed: 2.9,
      armor: [0.2, 0.96, 0.5],
      attack: {
        kind: "projectile",
        damage: [0, 5, 17],
        range: 10,
        aggroRange: 18,
        cooldownTicks: 40,
        bonuses: [],
        autoAcquireBuildings: true,
        launchDelayTicks: 16,
        accuracy: 0.8,
        accuracyReductionFactor: 1.5,
        aimBonus: 15,
        spreadFactor: 0.1,
        maxSpread: 5,
        trackRating: 2,
        unintentionalDamageMultiplier: 0.3,
        projectileCount: 3,
        projectile: {
          type: PROJECTILE_BALLISTA_BOLT,
          speed: 30,
          lifespanTicks: 40,
          collisionRadius: 0.1,
        },
      },
      garrison: {
        capacity: 5,
        enterRange: 4,
        validOccupants: [
          { kind: "classes", classes: UNIT_CLASS_WORKER },
          { kind: "classes", classes: UNIT_CLASS_HERO },
          { kind: "classes", classes: UNIT_CLASS_HUMAN | UNIT_CLASS_INFANTRY },
          { kind: "classes", classes: UNIT_CLASS_HUMAN | UNIT_CLASS_ARCHER },
          { kind: "unit", key: "egyptian-pharaoh" },
          { kind: "unit", key: "egyptian-priest" },
          { kind: "unit", key: "egyptian-son-of-osiris" },
        ],
        attackMultiplierPerOccupant: 0.05,
        ejectOnDeath: true,
      },
      bodyRadius: 0.99,
      cost: [0, 300, 200, 0],
      buildTicks: 480,
      populationCost: 4,
      requiredAge: 3,
      requiredGod: 255,
      prerequisiteBuildings: [26],
      trainedAt: [{ type: 26, commandSlot: 5 }],
    }),
  },
  {
    family: "siege",
    attackKind: "projectile",
    id: 85,
    key: "greek-petrobolos",
    source: {
      stage: "candidate",
      culture: "greek",
      ruleset: "Age of Mythology Classic",
      trialProto: {
        sha256: TRIAL_PROTO_SHA256,
        unitId: 445,
        unitName: "Petrobolos",
      },
      assetInventory: {
        sha256: GREEK_ASSET_INVENTORY_SHA256,
        rosterName: "Petrobolos",
        rootAnimation: "petrobolos_anim.txt",
        attackRelease: {
          sha256: "cb5160d91e3d7f713bd9fce0975f66080ecb8caf027c1c81158ba761ee38e7bd",
          action: "RangedAttack",
          tag: "Attack",
          fraction: 0.03,
          durationTicks: 80,
          model: "siege g petrobolos_attacka.glb",
          modelSha256: "a9911987932f1d556b80f6315e82caada800bc9bf6a9d9edeae97b35e59a4d57",
          modelDurationTicks: 166,
        },
      },
      trialDeltas: [],
    },
    expected: ordinaryUnitExpected({
      label: "Petrobolos",
      culture: 1,
      classes: 528,
      maxHp: 110,
      lineOfSight: 40,
      movementSpeed: 2.4,
      armor: [0.3, 0.9, 0.9],
      attack: {
        kind: "projectile",
        damage: [0, 5, 11],
        range: 28,
        minimumRange: 10,
        aggroRange: 40,
        cooldownTicks: 80,
        bonuses: [{ target: { kind: "classes", classes: UNIT_CLASS_SHIP }, multiplier: 2.5 }],
        autoAcquireBuildings: true,
        launchDelayTicks: 2,
        accuracy: 0.9,
        accuracyReductionFactor: 3,
        aimBonus: 15,
        spreadFactor: 0.1,
        maxSpread: 5,
        trackRating: 2,
        unintentionalDamageMultiplier: 0.5,
        projectileCount: 3,
        projectile: {
          type: PROJECTILE_PETROBOLOS_STONE,
          speed: 20,
          lifespanTicks: 40,
          collisionRadius: 0.1,
        },
      },
      bodyRadius: 0.99,
      cost: [0, 150, 200, 0],
      buildTicks: 380,
      populationCost: 3,
      requiredAge: 2,
      requiredGod: 255,
      prerequisiteBuildings: [26],
      trainedAt: [{ type: 26, commandSlot: 4 }],
    }),
  },
  {
    family: "siege",
    attackKind: "projectile",
    id: 132,
    key: "egyptian-catapult",
    source: {
      stage: "candidate",
      culture: "egyptian",
      ruleset: "Age of Mythology Classic",
      trialProto: {
        sha256: TRIAL_PROTO_SHA256,
        unitId: 328,
        unitName: "Catapult",
      },
      assetInventory: {
        sha256: EGYPTIAN_ASSET_INVENTORY_SHA256,
        rosterName: "Catapult",
        rootAnimation: "catapult_anim.txt",
        attackRelease: {
          sha256: "d920c86a1d34a6376a49cf1af8372d974e718ba3f8065263134f850cef1b75d9",
          action: "RangedAttack",
          tag: "Attack",
          fraction: 0.07,
          durationTicks: 80,
          model: "siege e catapult_attacka.glb",
          modelSha256: "22e9311d6599b3130471d3fed02d5614c7d802178da1c4e03156def7c00a2da9",
          modelDurationTicks: 200,
        },
      },
      trialDeltas: [],
    },
    expected: ordinaryUnitExpected({
      label: "Catapult",
      culture: 2,
      classes: 528,
      maxHp: 115,
      lineOfSight: 40,
      movementSpeed: 2.4,
      armor: [0.3, 0.9, 0.9],
      attack: {
        kind: "projectile",
        damage: [0, 10, 50],
        range: 28,
        minimumRange: 10,
        aggroRange: 40,
        cooldownTicks: 80,
        bonuses: [{ target: { kind: "classes", classes: UNIT_CLASS_SHIP }, multiplier: 2.5 }],
        autoAcquireBuildings: true,
        launchDelayTicks: 6,
        accuracy: 0.9,
        accuracyReductionFactor: 3,
        aimBonus: 15,
        spreadFactor: 0.1,
        maxSpread: 5,
        trackRating: 2,
        unintentionalDamageMultiplier: 0.5,
        projectile: {
          type: PROJECTILE_CATAPULT_STONE,
          speed: 20,
          lifespanTicks: 40,
          collisionRadius: 0.1,
        },
      },
      bodyRadius: 0.99,
      cost: [0, 200, 200, 0],
      buildTicks: 480,
      populationCost: 3,
      requiredAge: 3,
      requiredGod: 255,
      prerequisiteBuildings: [31],
      trainedAt: [{ type: 31, commandSlot: 1 }],
    }),
  },
  {
    family: "trade",
    id: 87,
    key: "greek-caravan",
    source: {
      stage: "candidate",
      culture: "greek",
      ruleset: "Age of Mythology Classic",
      trialProto: {
        sha256: TRIAL_PROTO_SHA256,
        unitId: 493,
        unitName: "Caravan Greek",
      },
      assetInventory: {
        sha256: GREEK_ASSET_INVENTORY_SHA256,
        rosterName: "Donkey Caravan",
        rootAnimation: "caravan greek_anim.txt",
      },
      trialDeltas: [
        {
          field: "label",
          trial: "Caravan Greek",
          final: "Donkey Caravan",
          reason: "The launch UI localizes the Greek proto as Donkey Caravan.",
        },
      ],
    },
    expected: economicUnitExpected({
      label: "Donkey Caravan",
      culture: 1,
      classes: UNIT_CLASS_CARAVAN,
      maxHp: 115,
      lineOfSight: 16,
      movementSpeed: 3.8,
      armor: [0.4, 0.4, 0.99],
      attack: null,
      trade: {
        capacity: 1000,
        interactionRange: 2,
        townCenterWorkRate: 0.511,
        townCenterMinimumRate: 0.066,
        incomeMultiplier: 1,
      },
      bodyRadius: 0.7,
      cost: [100, 0, 0, 0],
      buildTicks: 300,
      populationCost: 1,
      requiredAge: 2,
      requiredGod: 255,
      prerequisiteBuildings: [],
      trainedAt: [{ type: 28, commandSlot: 0 }],
    }),
  },
  {
    family: "trade",
    id: 134,
    key: "egyptian-caravan",
    source: {
      stage: "candidate",
      culture: "egyptian",
      ruleset: "Age of Mythology Classic",
      trialProto: {
        sha256: TRIAL_PROTO_SHA256,
        unitId: 494,
        unitName: "Caravan Egyptian",
      },
      assetInventory: {
        sha256: EGYPTIAN_ASSET_INVENTORY_SHA256,
        rosterName: "Camel Caravan",
        rootAnimation: "caravan egyptian_anim.txt",
      },
      trialDeltas: [
        {
          field: "label",
          trial: "Caravan Egyptian",
          final: "Camel Caravan",
          reason: "The launch UI localizes the Egyptian proto as Camel Caravan.",
        },
        {
          field: "trade.incomeMultiplier",
          trial: 1,
          final: 0.9,
          reason:
            "The released Egyptian culture drops off 10% less Caravan gold than the Greek baseline.",
        },
      ],
    },
    expected: economicUnitExpected({
      label: "Camel Caravan",
      culture: 2,
      classes: UNIT_CLASS_CARAVAN,
      maxHp: 115,
      lineOfSight: 16,
      movementSpeed: 3.8,
      armor: [0.4, 0.4, 0.99],
      attack: null,
      trade: {
        capacity: 1000,
        interactionRange: 2,
        townCenterWorkRate: 0.511,
        townCenterMinimumRate: 0.066,
        incomeMultiplier: 0.9,
      },
      bodyRadius: 0.7,
      cost: [100, 0, 0, 0],
      buildTicks: 300,
      populationCost: 1,
      requiredAge: 2,
      requiredGod: 255,
      prerequisiteBuildings: [],
      trainedAt: [{ type: 33, commandSlot: 0 }],
    }),
  },
  {
    family: "siege",
    attackKind: "projectile",
    id: 131,
    key: "egyptian-siege-tower",
    source: {
      stage: "candidate",
      culture: "egyptian",
      ruleset: "Age of Mythology Classic",
      trialProto: {
        sha256: TRIAL_PROTO_SHA256,
        unitId: 316,
        unitName: "Siege Tower",
      },
      assetInventory: {
        sha256: EGYPTIAN_ASSET_INVENTORY_SHA256,
        rosterName: "Siege Tower",
        rootAnimation: "siege tower_anim.txt",
        attackRelease: {
          sha256: "3c1b6db1641d52739878ca7aa7db49a5a7e62808ffeae63e9702bbb624593936",
          action: "RangedAttack",
          tag: "Attack",
          fraction: 0.4,
        },
        secondaryMeleeAttackCycles: [
          {
            sha256: "3c1b6db1641d52739878ca7aa7db49a5a7e62808ffeae63e9702bbb624593936",
            action: "attack",
            tag: "Attack",
            fraction: 0.5,
            durationTicks: 80,
            model: "siege e tower_attacka.glb",
            modelSha256: "b3f645538825d0e70965189478ff2719848e2cf07cce2a3daa13bf00dc49aa96",
            modelDurationTicks: 40,
          },
        ],
      },
      trialDeltas: [
        {
          field: "attack.damage",
          trial: [0, 3, 0],
          final: [0, 5, 0],
          reason:
            "The Trial row predates the original release's five-pierce arrow volley; the launch ruleset is pinned here.",
        },
        {
          field: "buildTicks",
          trial: 19 * 20,
          final: 22 * 20,
          reason:
            "The Trial row trains in 19 seconds; the original Classic release trains the Siege Tower in 22 seconds.",
        },
      ],
    },
    expected: ordinaryUnitExpected({
      label: "Siege Tower",
      culture: 2,
      classes: UNIT_CLASS_MILITARY | UNIT_CLASS_SIEGE | UNIT_CLASS_MELEE,
      maxHp: 350,
      lineOfSight: 20,
      movementSpeed: 2.9,
      armor: [0.05, 0.96, 0.9],
      attack: {
        kind: "projectile",
        damage: [0, 5, 0],
        range: 12,
        aggroRange: 20,
        cooldownTicks: 20,
        bonuses: [],
        autoAcquireBuildings: true,
        launchDelayTicks: 8,
        accuracy: 0.8,
        accuracyReductionFactor: 1.5,
        aimBonus: 15,
        spreadFactor: 0.1,
        maxSpread: 50,
        trackRating: 5,
        unintentionalDamageMultiplier: 0.3,
        projectileCount: 3,
        projectile: {
          type: PROJECTILE_ARROW,
          speed: 30,
          lifespanTicks: 40,
          collisionRadius: 0.1,
        },
      },
      buildingAttack: {
        kind: "melee",
        damage: [0, 0, 50],
        range: 3,
        aggroRange: 20,
        cooldownTicks: 80,
        bonuses: [],
        cycleVariants: [{ actionTicks: 80, impactDelayTicks: 40 }],
      },
      garrison: {
        capacity: 5,
        enterRange: 4,
        validOccupants: [
          { kind: "classes", classes: UNIT_CLASS_WORKER },
          { kind: "classes", classes: UNIT_CLASS_HERO },
          { kind: "classes", classes: UNIT_CLASS_HUMAN | UNIT_CLASS_INFANTRY },
          { kind: "classes", classes: UNIT_CLASS_HUMAN | UNIT_CLASS_ARCHER },
          { kind: "unit", key: "egyptian-pharaoh" },
          { kind: "unit", key: "egyptian-priest" },
          { kind: "unit", key: "egyptian-son-of-osiris" },
        ],
        attackMultiplierPerOccupant: 0.05,
        speedMultiplierPerOccupant: 0.05,
        ejectOnDeath: true,
      },
      bodyRadius: 0.99,
      cost: [0, 200, 100, 0],
      buildTicks: 22 * 20,
      populationCost: 3,
      requiredAge: 2,
      requiredGod: 255,
      prerequisiteBuildings: [31],
      trainedAt: [{ type: 31, commandSlot: 0 }],
    }),
  },
] as const satisfies readonly UnitReferenceSpec[];
