aom_web:
    common: {}
    dev:
        VITE_RELAY_URL: ENC[AES256_GCM,data:vYzogC3W8KBtFyl+vs5Lfa9ucMrSGQ==,iv:QN62/CqOsgERLYCUPz7Kb8r6/m+1H57SUjD3ooOvlq8=,tag:wFkNGmyoeUfSgOP4KG/8YQ==,type:str]
    staging:
        VITE_RELAY_URL: ENC[AES256_GCM,data:ztdftv/GAVI8OQ==,iv:TFDXv4i8g5MA/8FoHJD1XBUZbSfV//JX3wl0lnDjw2E=,tag:VfJ5im5gl60OPZYHRqpkXw==,type:str]
    prod:
        VITE_RELAY_URL: ENC[AES256_GCM,data:96vCbRs39K35iQ==,iv:/6bhZxCFm5YivVRIj8y3G1aLI1WUReWZjPm4lRkY294=,tag:N4Kk6ynSGLgxFvLaXqfGBw==,type:str]
aom_relay:
    common: {}
    dev:
        ENVIRONMENT: ENC[AES256_GCM,data:twwcuHTuXNxC0/M=,iv:QwFlFOPZBqGIZ7NzWer4ExYT9hkFA64SwYUchk3QF+I=,tag:cNr49l27EalxQ641+o2KGA==,type:str]
        ALLOWED_ORIGIN: ENC[AES256_GCM,data:7hMpc8VEl6N2oMyA+VNEQTSguiHs,iv:J/gdJyOBI5QPUhdWb15QFU63N6x4Y/jmBSW3wptGhTA=,tag:iMDARFlNZSddbF/DcSRRiQ==,type:str]
    staging:
        ENVIRONMENT: ENC[AES256_GCM,data:YuGn22wEAw==,iv:qWe4NpbankjMPLl8VHMDcaBgeAN7SKssf/vNi0yzyrk=,tag:GBFMnmJ9ZlL8HMVmOtMnCg==,type:str]
        ALLOWED_ORIGIN: ENC[AES256_GCM,data:dA9Q/8B/+KAYSQ==,iv:06sZO5DxdiKSdGe/mRc+r+vRVmpnOXkeJ4pytDxgh1w=,tag:7ylFn66yQZkY7fiYXxLeGA==,type:str]
    prod:
        ENVIRONMENT: ENC[AES256_GCM,data:SCyEHxwvGpsy4A==,iv:PVzkI8DQJJqa3p9mSG06DH5VUHvAYpe9jhAICjnEPIE=,tag:fLLyUMEo5w7Bj4fZ/AW1Dw==,type:str]
        ALLOWED_ORIGIN: ENC[AES256_GCM,data:ddPSaqqVS78Dug==,iv:lOLbs1w6waA3xDyPAcY/9GZhlVJyapqcy1Fm1RcZWKE=,tag:uO6lv43KdQLlppJZVowvTg==,type:str]
aom_infra:
    common:
        CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:AIt6yETPWUELDw==,iv:0gFOTiSnI52R/RFP1TFgloRsY+ZLLG4eSso2+vN1wks=,tag:zhfQEOtoDlsh/cT2FMEGKQ==,type:str]
    dev: {}
    staging: {}
    prod: {}
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3QlVYN0ZFd2J5MDdWWENz
            dEJyVlBaQTB4UXQwaS9UNHBva28zZkJwZVRrCmdBVSs2cmFHbEtXZHpXRmRUbkc5
            eXQ5WVB3K1lNT2FNTnFkRWpTejJxWlUKLS0tIEI3cUxIY3hwemlESzBOMm1pSnFo
            amlTcHpMUGJDYThCUGpYV0RraXNRZjAKEWRMz8xQNQrxVeaK2thIXjx6Pj83peK7
            MKBz152+0LgsdW+wckvgQUn5lgzHFxCPoRhw/FfEpCGDzZ3RzfYQUw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ztvv62hgjnupzkjp03mfhhtz73l5uumjvu0ppmjce0udhdxy8v7q6zvwq3
    lastmodified: "2026-07-17T22:42:22Z"
    mac: ENC[AES256_GCM,data:tRD2IIOqxrVFowagdY5qq4LYoBPDStwjQ71c7GyWr8I2jTSmdga0qWXsBjZEqmgNnzqiRyO2OUDqvtAHf7zNFNtDseeDJgcYPILzEnx0K+0HcDiQyFxp/1qL20MKOF4jl7KG0uMT725ChTwuwefqMrY3P4t+D0OD2f0R6qycwpg=,iv:cpYbr8pTkbq3QWoUHtpoN3H0R1ZBG3UdhrOX3WMiFWM=,tag:W2YoDScQIC6qP6Xwg7ikHQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
