aom_web:
  common: {}
  dev:
    VITE_RELAY_URL: ws://localhost:3002/ws
  staging:
    VITE_RELAY_URL: REPLACE_ME
  prod:
    VITE_RELAY_URL: REPLACE_ME

aom_relay:
  common: {}
  dev:
    ENVIRONMENT: development
    ALLOWED_ORIGIN: http://localhost:3001
  staging:
    ENVIRONMENT: staging
    ALLOWED_ORIGIN: REPLACE_ME
  prod:
    ENVIRONMENT: production
    ALLOWED_ORIGIN: REPLACE_ME

aom_infra:
  common:
    CLOUDFLARE_API_TOKEN: REPLACE_ME
  dev: {}
  staging: {}
  prod: {}
