import {
  GOD_ANUBIS,
  GOD_BAST,
  GOD_HATHOR,
  GOD_HORUS,
  GOD_NEPHTHYS,
  GOD_OSIRIS,
  GOD_PTAH,
  GOD_SEKHMET,
  GOD_THOTH,
  NO_GOD,
} from "../../ecs/progression";
import { blockedUnitLane, type UnitRosterEntry } from "../unit-roster-schema";
import {
  TYPE_ANUBITE,
  TYPE_AVENGER,
  TYPE_CATAPULT,
  TYPE_EGYPTIAN_CARAVAN,
  TYPE_EGYPTIAN_DOCK,
  TYPE_EGYPTIAN_FISHING_SHIP,
  TYPE_EGYPTIAN_MARKET,
  TYPE_EGYPTIAN_SIEGE_WORKS,
  TYPE_EGYPTIAN_TEMPLE,
  TYPE_EGYPTIAN_TITAN,
  TYPE_EGYPTIAN_TOWN_CENTER,
  TYPE_EGYPTIAN_TRANSPORT_SHIP,
  TYPE_KEBENIT,
  TYPE_LEVIATHAN,
  TYPE_MERCENARY,
  TYPE_MERCENARY_CAVALRY,
  TYPE_MUMMY,
  TYPE_PETSUCHOS,
  TYPE_PHARAOH,
  TYPE_PHOENIX,
  TYPE_PRIEST,
  TYPE_RAMMING_GALLEY,
  TYPE_ROC,
  TYPE_SCARAB,
  TYPE_SCORPION_MAN,
  TYPE_SIEGE_TOWER,
  TYPE_SON_OF_OSIRIS,
  TYPE_SPHINX,
  TYPE_WADJET,
  TYPE_WAR_BARGE,
  TYPE_WAR_TURTLE,
} from "../unit-type-ids";
import { CULTURE_EGYPTIAN } from "../unit-type-schema";

const PROJECTILE_FOUNDATION = "serial-projectile-foundation";
const HERO_FOUNDATION = "serial-egyptian-hero-lifecycle";
const MYTH_FOUNDATION = "serial-myth-unit-lifecycle";
const SPECIAL_ACTION_FOUNDATION = "serial-special-actions";
const SIEGE_FOUNDATION = "serial-siege-units";
const AREA_MINIMUM_RANGE_FOUNDATION = "serial-projectile-area-minimum-range";
const TRADE_FOUNDATION = "serial-trade-routes";
const WATER_FOUNDATION = "serial-water-navigation";
const NAVAL_COMBAT_FOUNDATION = "serial-naval-combat";
const TRANSPORT_FOUNDATION = "serial-transport";
const FLIGHT_FOUNDATION = "serial-air-navigation";

function egyptianTempleMyth(
  id: number,
  key: string,
  label: string,
  requiredGod: number,
  commandSlot: number,
  gates: readonly ("B" | "C" | "D" | "E")[],
  foundationLanes: readonly string[],
  blocker: string,
): UnitRosterEntry {
  return blockedUnitLane({
    id,
    key,
    label,
    culture: CULTURE_EGYPTIAN,
    family: "myth",
    gates,
    foundationLanes,
    requiredGod,
    trainedAt: [{ type: TYPE_EGYPTIAN_TEMPLE, commandSlot }],
    blocker,
  });
}

export const EGYPTIAN_FUTURE_ROSTER = [
  blockedUnitLane({
    id: TYPE_SIEGE_TOWER,
    key: "egyptian-siege-tower",
    label: "Siege Tower",
    culture: CULTURE_EGYPTIAN,
    family: "siege",
    gates: ["B", "D"],
    foundationLanes: [PROJECTILE_FOUNDATION, SIEGE_FOUNDATION, TRANSPORT_FOUNDATION],
    requiredGod: NO_GOD,
    trainedAt: [{ type: TYPE_EGYPTIAN_SIEGE_WORKS, commandSlot: 0 }],
    blocker:
      "Mixed melee/projectile siege attacks, siege targeting/collision, and faithful enter/garrison behavior.",
  }),
  blockedUnitLane({
    id: TYPE_CATAPULT,
    key: "egyptian-catapult",
    label: "Catapult",
    culture: CULTURE_EGYPTIAN,
    family: "siege",
    gates: ["B", "D"],
    foundationLanes: [AREA_MINIMUM_RANGE_FOUNDATION, SIEGE_FOUNDATION],
    requiredGod: NO_GOD,
    trainedAt: [{ type: TYPE_EGYPTIAN_SIEGE_WORKS, commandSlot: 1 }],
    blocker:
      "Projectile impact-area and minimum-range behavior plus siege targeting, collision, and presentation.",
  }),
  blockedUnitLane({
    id: TYPE_MERCENARY,
    key: "egyptian-mercenary",
    label: "Mercenary",
    culture: CULTURE_EGYPTIAN,
    family: "exceptional-lifecycle",
    gates: ["D"],
    foundationLanes: ["serial-temporary-units"],
    requiredGod: NO_GOD,
    trainedAt: [{ type: TYPE_EGYPTIAN_TOWN_CENTER, commandSlot: 2 }],
    blocker: "Deterministic 45-second lifetime, zero-time training, and exceptional removal rules.",
  }),
  blockedUnitLane({
    id: TYPE_EGYPTIAN_CARAVAN,
    key: "egyptian-caravan",
    label: "Camel Caravan",
    culture: CULTURE_EGYPTIAN,
    family: "trade",
    gates: ["D"],
    foundationLanes: [TRADE_FOUNDATION],
    requiredGod: NO_GOD,
    trainedAt: [{ type: TYPE_EGYPTIAN_MARKET, commandSlot: 0 }],
    blocker: "Trade-route targeting, market-distance income, round trips, and hashed cargo state.",
  }),
  blockedUnitLane({
    id: TYPE_EGYPTIAN_FISHING_SHIP,
    key: "egyptian-fishing-ship",
    label: "Egyptian Fishing Ship",
    culture: CULTURE_EGYPTIAN,
    family: "naval",
    gates: ["E"],
    foundationLanes: [WATER_FOUNDATION, "serial-naval-gathering"],
    requiredGod: NO_GOD,
    trainedAt: [{ type: TYPE_EGYPTIAN_DOCK, commandSlot: 0 }],
    blocker: "Water navigation, shoreline fishing, dock returns, occupancy, and naval visibility.",
  }),
  blockedUnitLane({
    id: TYPE_EGYPTIAN_TRANSPORT_SHIP,
    key: "egyptian-transport-ship",
    label: "Egyptian Transport Ship",
    culture: CULTURE_EGYPTIAN,
    family: "naval",
    gates: ["E"],
    foundationLanes: [WATER_FOUNDATION, TRANSPORT_FOUNDATION],
    requiredGod: NO_GOD,
    trainedAt: [{ type: TYPE_EGYPTIAN_DOCK, commandSlot: 1 }],
    blocker: "Water navigation, embark/disembark, capacity, cargo state, and destruction handling.",
  }),
  blockedUnitLane({
    id: TYPE_KEBENIT,
    key: "egyptian-kebenit",
    label: "Kebenit",
    culture: CULTURE_EGYPTIAN,
    family: "naval",
    gates: ["B", "E"],
    foundationLanes: [PROJECTILE_FOUNDATION, WATER_FOUNDATION, NAVAL_COMBAT_FOUNDATION],
    requiredGod: NO_GOD,
    trainedAt: [{ type: TYPE_EGYPTIAN_DOCK, commandSlot: 2 }],
    blocker: "Water navigation, naval acquisition/collision, and projectile combat over water.",
  }),
  blockedUnitLane({
    id: TYPE_RAMMING_GALLEY,
    key: "egyptian-ramming-galley",
    label: "Ramming Galley",
    culture: CULTURE_EGYPTIAN,
    family: "naval",
    gates: ["D", "E"],
    foundationLanes: ["serial-ram-attacks", WATER_FOUNDATION, NAVAL_COMBAT_FOUNDATION],
    requiredGod: NO_GOD,
    trainedAt: [{ type: TYPE_EGYPTIAN_DOCK, commandSlot: 3 }],
    blocker: "Water navigation, naval collision, and deterministic ram attack behavior.",
  }),
  blockedUnitLane({
    id: TYPE_WAR_BARGE,
    key: "egyptian-war-barge",
    label: "War Barge",
    culture: CULTURE_EGYPTIAN,
    family: "naval",
    gates: ["B", "D", "E"],
    foundationLanes: [
      AREA_MINIMUM_RANGE_FOUNDATION,
      SIEGE_FOUNDATION,
      WATER_FOUNDATION,
      NAVAL_COMBAT_FOUNDATION,
    ],
    requiredGod: NO_GOD,
    trainedAt: [{ type: TYPE_EGYPTIAN_DOCK, commandSlot: 4 }],
    blocker:
      "Water navigation plus naval projectile-siege area, range, collision, and targeting rules.",
  }),
  blockedUnitLane({
    id: TYPE_PHARAOH,
    key: "egyptian-pharaoh",
    label: "Pharaoh",
    culture: CULTURE_EGYPTIAN,
    family: "hero",
    gates: ["B", "C", "D"],
    foundationLanes: [PROJECTILE_FOUNDATION, HERO_FOUNDATION, SPECIAL_ACTION_FOUNDATION],
    requiredGod: NO_GOD,
    trainedAt: [],
    blocker:
      "Singular Pharaoh creation/automatic return, myth counters, ranged combat, healing, empowerment, and lifecycle hashing.",
  }),
  blockedUnitLane({
    id: TYPE_PRIEST,
    key: "egyptian-priest",
    label: "Priest",
    culture: CULTURE_EGYPTIAN,
    family: "hero",
    gates: ["B", "C", "D"],
    foundationLanes: [PROJECTILE_FOUNDATION, HERO_FOUNDATION, SPECIAL_ACTION_FOUNDATION],
    requiredGod: NO_GOD,
    trainedAt: [
      { type: TYPE_EGYPTIAN_TEMPLE, commandSlot: 0 },
      { type: TYPE_EGYPTIAN_TOWN_CENTER, commandSlot: 1 },
    ],
    blocker:
      "Egyptian hero/myth counters and ranged combat plus healing, empowerment, conversion, and construction rules.",
  }),
  blockedUnitLane({
    id: TYPE_SON_OF_OSIRIS,
    key: "egyptian-son-of-osiris",
    label: "Son of Osiris",
    culture: CULTURE_EGYPTIAN,
    family: "hero",
    gates: ["C", "D"],
    foundationLanes: [HERO_FOUNDATION, "serial-god-power-transformations"],
    requiredGod: GOD_OSIRIS,
    trainedAt: [],
    blocker:
      "God-power Pharaoh transformation, ownership/lifecycle replacement, chain attack, healing, and empowerment rules.",
  }),

  egyptianTempleMyth(
    TYPE_ANUBITE,
    "egyptian-anubite",
    "Anubite",
    GOD_ANUBIS,
    1,
    ["C", "D"],
    [MYTH_FOUNDATION, SPECIAL_ACTION_FOUNDATION],
    "Myth-unit favor/lifecycle and hero counters plus deterministic jump attack behavior.",
  ),
  egyptianTempleMyth(
    TYPE_SPHINX,
    "egyptian-sphinx",
    "Sphinx",
    GOD_BAST,
    1,
    ["C", "D"],
    [MYTH_FOUNDATION, SPECIAL_ACTION_FOUNDATION],
    "Myth-unit rules plus deterministic area whirlwind targeting, movement, and recharge.",
  ),
  egyptianTempleMyth(
    TYPE_WADJET,
    "egyptian-wadjet",
    "Wadjet",
    GOD_PTAH,
    1,
    ["B", "C", "D"],
    [PROJECTILE_FOUNDATION, MYTH_FOUNDATION, "serial-unit-regeneration"],
    "Myth-unit and projectile rules plus faithful regeneration state, timing, and hashing.",
  ),
  egyptianTempleMyth(
    TYPE_PETSUCHOS,
    "egyptian-petsuchos",
    "Petsuchos",
    GOD_HATHOR,
    2,
    ["B", "C", "D"],
    [PROJECTILE_FOUNDATION, MYTH_FOUNDATION, SPECIAL_ACTION_FOUNDATION],
    "Myth-unit rules plus continuous lightning targeting, damage timing, and presentation.",
  ),
  egyptianTempleMyth(
    TYPE_ROC,
    "egyptian-roc",
    "Roc",
    GOD_HATHOR,
    3,
    ["C", "E"],
    [MYTH_FOUNDATION, FLIGHT_FOUNDATION, TRANSPORT_FOUNDATION],
    "Myth-unit rules plus air navigation, embark/disembark, capacity, cargo, and visibility.",
  ),
  egyptianTempleMyth(
    TYPE_SCARAB,
    "egyptian-scarab",
    "Scarab",
    GOD_SEKHMET,
    2,
    ["C", "D"],
    [MYTH_FOUNDATION, SIEGE_FOUNDATION],
    "Myth-unit rules plus siege-specific building acquisition, damage, collision, and presentation.",
  ),
  egyptianTempleMyth(
    TYPE_MUMMY,
    "egyptian-mummy",
    "Mummy",
    GOD_OSIRIS,
    4,
    ["B", "C", "D"],
    [PROJECTILE_FOUNDATION, MYTH_FOUNDATION, "serial-conversion-and-minion-spawn"],
    "Myth/projectile rules plus conversion attacks, immunity, minion creation, and lifecycle state.",
  ),
  egyptianTempleMyth(
    TYPE_PHOENIX,
    "egyptian-phoenix",
    "Phoenix",
    GOD_THOTH,
    4,
    ["C", "D", "E"],
    [MYTH_FOUNDATION, "serial-phoenix-egg-rebirth", FLIGHT_FOUNDATION],
    "Myth and air rules plus deterministic egg replacement, rebirth, targeting, and death state.",
  ),
  egyptianTempleMyth(
    TYPE_AVENGER,
    "egyptian-avenger",
    "Avenger",
    GOD_HORUS,
    4,
    ["C", "D"],
    [MYTH_FOUNDATION, SPECIAL_ACTION_FOUNDATION],
    "Myth-unit rules plus deterministic area whirlwind targeting, movement, and recharge.",
  ),
  egyptianTempleMyth(
    TYPE_SCORPION_MAN,
    "egyptian-scorpion-man",
    "Scorpion Man",
    GOD_NEPHTHYS,
    2,
    ["C", "D"],
    [MYTH_FOUNDATION, SPECIAL_ACTION_FOUNDATION],
    "Myth-unit rules plus deterministic area attack targeting, damage timing, and recharge.",
  ),
  blockedUnitLane({
    id: TYPE_LEVIATHAN,
    key: "egyptian-leviathan",
    label: "Leviathan",
    culture: CULTURE_EGYPTIAN,
    family: "myth",
    gates: ["C", "E"],
    foundationLanes: [
      MYTH_FOUNDATION,
      WATER_FOUNDATION,
      NAVAL_COMBAT_FOUNDATION,
      TRANSPORT_FOUNDATION,
    ],
    requiredGod: GOD_NEPHTHYS,
    trainedAt: [{ type: TYPE_EGYPTIAN_DOCK, commandSlot: 5 }],
    blocker:
      "Aquatic myth lifecycle, water navigation/combat, embark/disembark, capacity, and cargo state.",
  }),
  blockedUnitLane({
    id: TYPE_WAR_TURTLE,
    key: "egyptian-war-turtle",
    label: "War Turtle",
    culture: CULTURE_EGYPTIAN,
    family: "myth",
    gates: ["C", "D", "E"],
    foundationLanes: [
      MYTH_FOUNDATION,
      SPECIAL_ACTION_FOUNDATION,
      WATER_FOUNDATION,
      NAVAL_COMBAT_FOUNDATION,
    ],
    requiredGod: GOD_THOTH,
    trainedAt: [{ type: TYPE_EGYPTIAN_DOCK, commandSlot: 6 }],
    blocker: "Aquatic myth rules plus deterministic buck attack, naval targeting, and recharge.",
  }),
  blockedUnitLane({
    id: TYPE_EGYPTIAN_TITAN,
    key: "egyptian-titan",
    label: "Egyptian Titan",
    culture: CULTURE_EGYPTIAN,
    family: "myth",
    gates: ["C", "D"],
    foundationLanes: [MYTH_FOUNDATION, "serial-titan-gate-awakening"],
    requiredGod: NO_GOD,
    trainedAt: [],
    blocker:
      "Titan Gate research/construction, one-Titan limits, awakening, giant occupancy, and Titan combat rules.",
  }),
  blockedUnitLane({
    id: TYPE_MERCENARY_CAVALRY,
    key: "egyptian-mercenary-cavalry",
    label: "Mercenary Cavalry",
    culture: CULTURE_EGYPTIAN,
    family: "exceptional-lifecycle",
    gates: ["D"],
    foundationLanes: ["serial-temporary-units"],
    requiredGod: NO_GOD,
    trainedAt: [{ type: TYPE_EGYPTIAN_TOWN_CENTER, commandSlot: 3 }],
    blocker: "Deterministic 45-second lifetime, zero-time training, and exceptional removal rules.",
  }),
] as const satisfies readonly UnitRosterEntry[];
