import {
  GOD_ANUBIS,
  GOD_BAST,
  GOD_HATHOR,
  GOD_HORUS,
  GOD_NEPHTHYS,
  GOD_OSIRIS,
  GOD_PTAH,
  GOD_SEKHMET,
  GOD_THOTH,
  NO_GOD,
} from "../../ecs/progression";
import { blockedUnitLane, defineUnitLane, type UnitRosterEntry } from "../unit-roster-schema";
import {
  TYPE_ANUBITE,
  TYPE_AVENGER,
  TYPE_CATAPULT,
  TYPE_EGYPTIAN_CARAVAN,
  TYPE_EGYPTIAN_DOCK,
  TYPE_EGYPTIAN_FISHING_SHIP,
  TYPE_EGYPTIAN_MARKET,
  TYPE_EGYPTIAN_SIEGE_WORKS,
  TYPE_EGYPTIAN_TEMPLE,
  TYPE_EGYPTIAN_TITAN,
  TYPE_EGYPTIAN_TOWN_CENTER,
  TYPE_EGYPTIAN_TRANSPORT_SHIP,
  TYPE_KEBENIT,
  TYPE_LEVIATHAN,
  TYPE_MERCENARY,
  TYPE_MERCENARY_CAVALRY,
  TYPE_MUMMY,
  TYPE_PETSUCHOS,
  TYPE_PHARAOH,
  TYPE_PHOENIX,
  TYPE_PHOENIX_EGG,
  TYPE_PRIEST,
  TYPE_RAMMING_GALLEY,
  TYPE_ROC,
  TYPE_SCARAB,
  TYPE_SCORPION_MAN,
  TYPE_SIEGE_TOWER,
  TYPE_SON_OF_OSIRIS,
  TYPE_SPHINX,
  TYPE_WADJET,
  TYPE_WAR_BARGE,
  TYPE_WAR_TURTLE,
} from "../unit-type-ids";
import { CULTURE_EGYPTIAN } from "../unit-type-schema";

const PROJECTILE_FOUNDATION = "serial-projectile-foundation";
const HERO_FOUNDATION = "serial-egyptian-hero-lifecycle";
const MYTH_FOUNDATION = "serial-myth-unit-lifecycle";
const JUMP_ATTACK_FOUNDATION = "serial-jump-special";
const AREA_WHIRLWIND_FOUNDATION = "serial-area-whirlwind-special";
const CONTINUOUS_LIGHTNING_FOUNDATION = "serial-continuous-lightning-attack";
const SIEGE_FOUNDATION = "serial-siege-units";
const AREA_MINIMUM_RANGE_FOUNDATION = "serial-projectile-area-minimum-range";
const TRADE_FOUNDATION = "serial-trade-routes";
const WATER_FOUNDATION = "serial-water-navigation";
const NAVAL_COMBAT_FOUNDATION = "serial-naval-combat";
const TRANSPORT_FOUNDATION = "serial-transport";
const FLIGHT_FOUNDATION = "serial-air-navigation";

export const EGYPTIAN_FUTURE_ROSTER = [
  defineUnitLane({
    id: TYPE_SIEGE_TOWER,
    key: "egyptian-siege-tower",
    label: "Siege Tower",
    culture: CULTURE_EGYPTIAN,
    family: "siege",
    gates: ["B", "D"],
    foundationLanes: [PROJECTILE_FOUNDATION, SIEGE_FOUNDATION, TRANSPORT_FOUNDATION],
    requiredGod: NO_GOD,
    trainedAt: [{ type: TYPE_EGYPTIAN_SIEGE_WORKS, commandSlot: 0 }],
    status: "ready",
    blocker: null,
  }),
  defineUnitLane({
    id: TYPE_CATAPULT,
    key: "egyptian-catapult",
    label: "Catapult",
    culture: CULTURE_EGYPTIAN,
    family: "siege",
    gates: ["B", "D"],
    foundationLanes: [AREA_MINIMUM_RANGE_FOUNDATION, SIEGE_FOUNDATION],
    requiredGod: NO_GOD,
    trainedAt: [{ type: TYPE_EGYPTIAN_SIEGE_WORKS, commandSlot: 1 }],
    status: "ready",
    blocker: null,
  }),
  defineUnitLane({
    id: TYPE_MERCENARY,
    key: "egyptian-mercenary",
    label: "Mercenary",
    culture: CULTURE_EGYPTIAN,
    family: "exceptional-lifecycle",
    gates: ["D"],
    foundationLanes: ["serial-temporary-units"],
    requiredGod: NO_GOD,
    trainedAt: [{ type: TYPE_EGYPTIAN_TOWN_CENTER, commandSlot: 2 }],
    status: "ready",
    blocker: null,
  }),
  defineUnitLane({
    id: TYPE_EGYPTIAN_CARAVAN,
    key: "egyptian-caravan",
    label: "Camel Caravan",
    culture: CULTURE_EGYPTIAN,
    family: "trade",
    gates: ["D"],
    foundationLanes: [TRADE_FOUNDATION],
    requiredGod: NO_GOD,
    trainedAt: [{ type: TYPE_EGYPTIAN_MARKET, commandSlot: 0 }],
    status: "ready",
    blocker: null,
  }),
  defineUnitLane({
    id: TYPE_EGYPTIAN_FISHING_SHIP,
    key: "egyptian-fishing-ship",
    label: "Fishing Ship",
    culture: CULTURE_EGYPTIAN,
    family: "naval",
    gates: ["E"],
    foundationLanes: [WATER_FOUNDATION, "serial-naval-gathering"],
    requiredGod: NO_GOD,
    trainedAt: [{ type: TYPE_EGYPTIAN_DOCK, commandSlot: 0 }],
    status: "ready",
    blocker: null,
  }),
  defineUnitLane({
    id: TYPE_EGYPTIAN_TRANSPORT_SHIP,
    key: "egyptian-transport-ship",
    label: "Transport Ship",
    culture: CULTURE_EGYPTIAN,
    family: "naval",
    gates: ["E"],
    foundationLanes: [WATER_FOUNDATION, TRANSPORT_FOUNDATION],
    requiredGod: NO_GOD,
    trainedAt: [{ type: TYPE_EGYPTIAN_DOCK, commandSlot: 1 }],
    status: "ready",
    blocker: null,
  }),
  defineUnitLane({
    id: TYPE_KEBENIT,
    key: "egyptian-kebenit",
    label: "Kebenit",
    culture: CULTURE_EGYPTIAN,
    family: "naval",
    gates: ["B", "E"],
    foundationLanes: [PROJECTILE_FOUNDATION, WATER_FOUNDATION, NAVAL_COMBAT_FOUNDATION],
    requiredGod: NO_GOD,
    trainedAt: [{ type: TYPE_EGYPTIAN_DOCK, commandSlot: 2 }],
    status: "ready",
    blocker: null,
  }),
  defineUnitLane({
    id: TYPE_RAMMING_GALLEY,
    key: "egyptian-ramming-galley",
    label: "Ramming Galley",
    culture: CULTURE_EGYPTIAN,
    family: "naval",
    gates: ["D", "E"],
    foundationLanes: ["serial-ram-attacks", WATER_FOUNDATION, NAVAL_COMBAT_FOUNDATION],
    requiredGod: NO_GOD,
    trainedAt: [{ type: TYPE_EGYPTIAN_DOCK, commandSlot: 3 }],
    status: "ready",
    blocker: null,
  }),
  defineUnitLane({
    id: TYPE_WAR_BARGE,
    key: "egyptian-war-barge",
    label: "War Barge",
    culture: CULTURE_EGYPTIAN,
    family: "naval",
    gates: ["B", "D", "E"],
    foundationLanes: [
      AREA_MINIMUM_RANGE_FOUNDATION,
      SIEGE_FOUNDATION,
      WATER_FOUNDATION,
      NAVAL_COMBAT_FOUNDATION,
    ],
    requiredGod: NO_GOD,
    trainedAt: [{ type: TYPE_EGYPTIAN_DOCK, commandSlot: 4 }],
    status: "ready",
    blocker: null,
  }),
  defineUnitLane({
    id: TYPE_PHARAOH,
    key: "egyptian-pharaoh",
    label: "Pharaoh",
    culture: CULTURE_EGYPTIAN,
    family: "hero",
    gates: ["B", "C", "D"],
    foundationLanes: [
      PROJECTILE_FOUNDATION,
      HERO_FOUNDATION,
      "serial-egyptian-pharaoh-lifecycle",
      "serial-egyptian-support-actions",
    ],
    requiredGod: NO_GOD,
    trainedAt: [],
    status: "ready",
    blocker: null,
  }),
  defineUnitLane({
    id: TYPE_PRIEST,
    key: "egyptian-priest",
    label: "Priest",
    culture: CULTURE_EGYPTIAN,
    family: "hero",
    gates: ["B", "C", "D"],
    foundationLanes: [
      PROJECTILE_FOUNDATION,
      HERO_FOUNDATION,
      "serial-egyptian-support-actions",
      "serial-conversion-actions",
    ],
    requiredGod: NO_GOD,
    trainedAt: [
      { type: TYPE_EGYPTIAN_TEMPLE, commandSlot: 0 },
      { type: TYPE_EGYPTIAN_TOWN_CENTER, commandSlot: 1 },
    ],
    status: "ready",
    blocker: null,
  }),
  defineUnitLane({
    id: TYPE_SON_OF_OSIRIS,
    key: "egyptian-son-of-osiris",
    label: "Son of Osiris",
    culture: CULTURE_EGYPTIAN,
    family: "hero",
    gates: ["C", "D"],
    foundationLanes: [HERO_FOUNDATION, "serial-god-power-transformations"],
    requiredGod: GOD_OSIRIS,
    trainedAt: [],
    status: "ready",
    blocker: null,
  }),

  defineUnitLane({
    id: TYPE_ANUBITE,
    key: "egyptian-anubite",
    label: "Anubite",
    culture: CULTURE_EGYPTIAN,
    family: "myth",
    gates: ["C", "D"],
    foundationLanes: [MYTH_FOUNDATION, JUMP_ATTACK_FOUNDATION],
    requiredGod: GOD_ANUBIS,
    trainedAt: [{ type: TYPE_EGYPTIAN_TEMPLE, commandSlot: 1 }],
    status: "ready",
    blocker: null,
  }),
  defineUnitLane({
    id: TYPE_SPHINX,
    key: "egyptian-sphinx",
    label: "Sphinx",
    culture: CULTURE_EGYPTIAN,
    family: "myth",
    gates: ["C", "D"],
    foundationLanes: [MYTH_FOUNDATION, AREA_WHIRLWIND_FOUNDATION],
    requiredGod: GOD_BAST,
    trainedAt: [{ type: TYPE_EGYPTIAN_TEMPLE, commandSlot: 1 }],
    status: "ready",
    blocker: null,
  }),
  defineUnitLane({
    id: TYPE_WADJET,
    key: "egyptian-wadjet",
    label: "Wadjet",
    culture: CULTURE_EGYPTIAN,
    family: "myth",
    gates: ["B", "C", "D"],
    foundationLanes: [PROJECTILE_FOUNDATION, MYTH_FOUNDATION, "serial-unit-regeneration"],
    requiredGod: GOD_PTAH,
    trainedAt: [{ type: TYPE_EGYPTIAN_TEMPLE, commandSlot: 1 }],
    status: "ready",
    blocker: null,
  }),
  defineUnitLane({
    id: TYPE_PETSUCHOS,
    key: "egyptian-petsuchos",
    label: "Petsuchos",
    culture: CULTURE_EGYPTIAN,
    family: "myth",
    gates: ["B", "C", "D"],
    foundationLanes: [MYTH_FOUNDATION, CONTINUOUS_LIGHTNING_FOUNDATION],
    requiredGod: GOD_HATHOR,
    trainedAt: [{ type: TYPE_EGYPTIAN_TEMPLE, commandSlot: 2 }],
    status: "ready",
    blocker: null,
  }),
  defineUnitLane({
    id: TYPE_ROC,
    key: "egyptian-roc",
    label: "Roc",
    culture: CULTURE_EGYPTIAN,
    family: "myth",
    gates: ["C", "E"],
    foundationLanes: [MYTH_FOUNDATION, FLIGHT_FOUNDATION, TRANSPORT_FOUNDATION],
    requiredGod: GOD_HATHOR,
    trainedAt: [{ type: TYPE_EGYPTIAN_TEMPLE, commandSlot: 3 }],
    status: "ready",
    blocker: null,
  }),
  defineUnitLane({
    id: TYPE_SCARAB,
    key: "egyptian-scarab",
    label: "Scarab",
    culture: CULTURE_EGYPTIAN,
    family: "myth",
    gates: ["C", "D"],
    foundationLanes: [MYTH_FOUNDATION, "serial-death-area-attacks"],
    requiredGod: GOD_SEKHMET,
    trainedAt: [{ type: TYPE_EGYPTIAN_TEMPLE, commandSlot: 2 }],
    status: "ready",
    blocker: null,
  }),
  defineUnitLane({
    id: TYPE_MUMMY,
    key: "egyptian-mummy",
    label: "Mummy",
    culture: CULTURE_EGYPTIAN,
    family: "myth",
    gates: ["B", "C", "D"],
    foundationLanes: [PROJECTILE_FOUNDATION, MYTH_FOUNDATION, "serial-conversion-and-minion-spawn"],
    requiredGod: GOD_OSIRIS,
    trainedAt: [{ type: TYPE_EGYPTIAN_TEMPLE, commandSlot: 4 }],
    status: "ready",
    blocker: null,
  }),
  defineUnitLane({
    id: TYPE_PHOENIX,
    key: "egyptian-phoenix",
    label: "Phoenix",
    culture: CULTURE_EGYPTIAN,
    family: "myth",
    gates: ["C", "D", "E"],
    foundationLanes: [MYTH_FOUNDATION, "serial-phoenix-egg-rebirth", FLIGHT_FOUNDATION],
    requiredGod: GOD_THOTH,
    trainedAt: [
      { type: TYPE_EGYPTIAN_TEMPLE, commandSlot: 4 },
      { type: TYPE_PHOENIX_EGG, commandSlot: 0 },
    ],
    status: "ready",
    blocker: null,
  }),
  defineUnitLane({
    id: TYPE_AVENGER,
    key: "egyptian-avenger",
    label: "Avenger",
    culture: CULTURE_EGYPTIAN,
    family: "myth",
    gates: ["C", "D"],
    foundationLanes: [MYTH_FOUNDATION, AREA_WHIRLWIND_FOUNDATION],
    requiredGod: GOD_HORUS,
    trainedAt: [{ type: TYPE_EGYPTIAN_TEMPLE, commandSlot: 4 }],
    status: "ready",
    blocker: null,
  }),
  defineUnitLane({
    id: TYPE_SCORPION_MAN,
    key: "egyptian-scorpion-man",
    label: "Scorpion Man",
    culture: CULTURE_EGYPTIAN,
    family: "myth",
    gates: ["C", "D"],
    foundationLanes: [MYTH_FOUNDATION, AREA_WHIRLWIND_FOUNDATION],
    requiredGod: GOD_NEPHTHYS,
    trainedAt: [{ type: TYPE_EGYPTIAN_TEMPLE, commandSlot: 2 }],
    status: "ready",
    blocker: null,
  }),
  defineUnitLane({
    id: TYPE_LEVIATHAN,
    key: "egyptian-leviathan",
    label: "Leviathan",
    culture: CULTURE_EGYPTIAN,
    family: "myth",
    gates: ["C", "E"],
    foundationLanes: [
      MYTH_FOUNDATION,
      WATER_FOUNDATION,
      NAVAL_COMBAT_FOUNDATION,
      TRANSPORT_FOUNDATION,
    ],
    requiredGod: GOD_NEPHTHYS,
    trainedAt: [{ type: TYPE_EGYPTIAN_DOCK, commandSlot: 5 }],
    status: "ready",
    blocker: null,
  }),
  defineUnitLane({
    id: TYPE_WAR_TURTLE,
    key: "egyptian-war-turtle",
    label: "War Turtle",
    culture: CULTURE_EGYPTIAN,
    family: "myth",
    gates: ["C", "D", "E"],
    foundationLanes: [
      MYTH_FOUNDATION,
      "serial-buck-special",
      WATER_FOUNDATION,
      NAVAL_COMBAT_FOUNDATION,
    ],
    requiredGod: GOD_THOTH,
    trainedAt: [{ type: TYPE_EGYPTIAN_DOCK, commandSlot: 6 }],
    status: "ready",
    blocker: null,
  }),
  blockedUnitLane({
    id: TYPE_EGYPTIAN_TITAN,
    key: "egyptian-titan",
    label: "Egyptian Titan",
    culture: CULTURE_EGYPTIAN,
    family: "myth",
    gates: ["C", "D"],
    foundationLanes: [MYTH_FOUNDATION, "serial-titan-gate-awakening"],
    requiredGod: NO_GOD,
    trainedAt: [],
    blocker:
      "Titan Gate research/construction, one-Titan limits, awakening, giant occupancy, and Titan combat rules.",
  }),
  defineUnitLane({
    id: TYPE_MERCENARY_CAVALRY,
    key: "egyptian-mercenary-cavalry",
    label: "Mercenary Cavalry",
    culture: CULTURE_EGYPTIAN,
    family: "exceptional-lifecycle",
    gates: ["D"],
    foundationLanes: ["serial-temporary-units"],
    requiredGod: NO_GOD,
    trainedAt: [{ type: TYPE_EGYPTIAN_TOWN_CENTER, commandSlot: 3 }],
    status: "ready",
    blocker: null,
  }),
] as const satisfies readonly UnitRosterEntry[];
