import {
  GOD_APHRODITE,
  GOD_APOLLO,
  GOD_ARES,
  GOD_ARTEMIS,
  GOD_ATHENA,
  GOD_DIONYSUS,
  GOD_HADES,
  GOD_HEPHAESTUS,
  GOD_HERA,
  GOD_HERMES,
  GOD_POSEIDON,
  GOD_ZEUS,
  NO_GOD,
} from "../../ecs/progression";
import { blockedUnitLane, type UnitGate, type UnitRosterEntry } from "../unit-roster-schema";
import {
  TYPE_ACHILLES,
  TYPE_AJAX,
  TYPE_ATALANTA,
  TYPE_BELLEROPHON,
  TYPE_CARCINOS,
  TYPE_CENTAUR,
  TYPE_CHIMERA,
  TYPE_CHIRON,
  TYPE_COLOSSUS,
  TYPE_CYCLOPS,
  TYPE_GREEK_CARAVAN,
  TYPE_GREEK_DOCK,
  TYPE_GREEK_FISHING_SHIP,
  TYPE_GREEK_FORTRESS,
  TYPE_GREEK_MARKET,
  TYPE_GREEK_TEMPLE,
  TYPE_GREEK_TITAN,
  TYPE_GREEK_TOWN_CENTER,
  TYPE_GREEK_TRANSPORT_SHIP,
  TYPE_HELEPOLIS,
  TYPE_HERACLES,
  TYPE_HIPPOLYTA,
  TYPE_HYDRA,
  TYPE_JASON,
  TYPE_JUGGERNAUT,
  TYPE_KATASKOPOS,
  TYPE_MANTICORE,
  TYPE_MEDUSA,
  TYPE_MILITIA,
  TYPE_MINOTAUR,
  TYPE_NEMEAN_LION,
  TYPE_ODYSSEUS,
  TYPE_PEGASUS,
  TYPE_PENTEKONTER,
  TYPE_PERSEUS,
  TYPE_PETROBOLOS,
  TYPE_POLYPHEMUS,
  TYPE_SCYLLA,
  TYPE_THESEUS,
  TYPE_TRIREME,
} from "../unit-type-ids";
import { CULTURE_GREEK } from "../unit-type-schema";

const PROJECTILE_FOUNDATION = "serial-projectile-foundation";
const HERO_FOUNDATION = "serial-greek-hero-lifecycle";
const MYTH_FOUNDATION = "serial-myth-unit-lifecycle";
const SPECIAL_ACTION_FOUNDATION = "serial-special-actions";
const SIEGE_FOUNDATION = "serial-siege-units";
const AREA_MINIMUM_RANGE_FOUNDATION = "serial-projectile-area-minimum-range";
const TRADE_FOUNDATION = "serial-trade-routes";
const WATER_FOUNDATION = "serial-water-navigation";
const NAVAL_COMBAT_FOUNDATION = "serial-naval-combat";
const TRANSPORT_FOUNDATION = "serial-transport";
const FLIGHT_FOUNDATION = "serial-air-navigation";

function greekHero(
  id: number,
  key: string,
  label: string,
  requiredGod: number,
  townCenterSlot: number,
  fortressSlot: number,
  gates: readonly UnitGate[],
  foundationLanes: readonly string[],
  blocker: string,
): UnitRosterEntry {
  return blockedUnitLane({
    id,
    key,
    label,
    culture: CULTURE_GREEK,
    family: "hero",
    gates,
    foundationLanes,
    requiredGod,
    trainedAt: [
      { type: TYPE_GREEK_TOWN_CENTER, commandSlot: townCenterSlot },
      { type: TYPE_GREEK_FORTRESS, commandSlot: fortressSlot },
    ],
    blocker,
  });
}

function greekTempleMyth(
  id: number,
  key: string,
  label: string,
  requiredGod: number,
  commandSlot: number,
  gates: readonly UnitGate[],
  foundationLanes: readonly string[],
  blocker: string,
): UnitRosterEntry {
  return blockedUnitLane({
    id,
    key,
    label,
    culture: CULTURE_GREEK,
    family: "myth",
    gates,
    foundationLanes,
    requiredGod,
    trainedAt: [{ type: TYPE_GREEK_TEMPLE, commandSlot }],
    blocker,
  });
}

const heroBlocker =
  "Greek hero uniqueness and retraining, myth-unit counter damage, relic carrying, lifecycle hashing, and the representative hero vertical slice.";

export const GREEK_FUTURE_ROSTER = [
  blockedUnitLane({
    id: TYPE_MILITIA,
    key: "militia",
    label: "Militia",
    culture: CULTURE_GREEK,
    family: "exceptional-lifecycle",
    gates: ["D"],
    foundationLanes: ["serial-death-spawn-units"],
    requiredGod: GOD_POSEIDON,
    trainedAt: [],
    blocker: "Poseidon building-destruction spawn and exceptional creation rules.",
  }),
  blockedUnitLane({
    id: TYPE_KATASKOPOS,
    key: "greek-kataskopos",
    label: "Kataskopos",
    culture: CULTURE_GREEK,
    family: "exceptional-lifecycle",
    gates: ["D"],
    foundationLanes: ["serial-starting-units"],
    requiredGod: NO_GOD,
    trainedAt: [],
    blocker: "Starting-only creation; Classic players cannot train replacements.",
  }),
  blockedUnitLane({
    id: TYPE_PETROBOLOS,
    key: "greek-petrobolos",
    label: "Petrobolos",
    culture: CULTURE_GREEK,
    family: "siege",
    gates: ["B", "D"],
    foundationLanes: [AREA_MINIMUM_RANGE_FOUNDATION, SIEGE_FOUNDATION],
    requiredGod: NO_GOD,
    trainedAt: [{ type: TYPE_GREEK_FORTRESS, commandSlot: 4 }],
    blocker:
      "Projectile impact-area and minimum-range behavior plus siege targeting, collision, and presentation.",
  }),
  blockedUnitLane({
    id: TYPE_HELEPOLIS,
    key: "greek-helepolis",
    label: "Helepolis",
    culture: CULTURE_GREEK,
    family: "siege",
    gates: ["B", "D"],
    foundationLanes: [PROJECTILE_FOUNDATION, SIEGE_FOUNDATION, TRANSPORT_FOUNDATION],
    requiredGod: NO_GOD,
    trainedAt: [{ type: TYPE_GREEK_FORTRESS, commandSlot: 5 }],
    blocker:
      "Multi-projectile siege attacks, siege targeting/collision, and faithful enter/garrison behavior.",
  }),
  blockedUnitLane({
    id: TYPE_GREEK_CARAVAN,
    key: "greek-caravan",
    label: "Donkey Caravan",
    culture: CULTURE_GREEK,
    family: "trade",
    gates: ["D"],
    foundationLanes: [TRADE_FOUNDATION],
    requiredGod: NO_GOD,
    trainedAt: [{ type: TYPE_GREEK_MARKET, commandSlot: 0 }],
    blocker: "Trade-route targeting, market-distance income, round trips, and hashed cargo state.",
  }),
  blockedUnitLane({
    id: TYPE_GREEK_FISHING_SHIP,
    key: "greek-fishing-ship",
    label: "Greek Fishing Ship",
    culture: CULTURE_GREEK,
    family: "naval",
    gates: ["E"],
    foundationLanes: [WATER_FOUNDATION, "serial-naval-gathering"],
    requiredGod: NO_GOD,
    trainedAt: [{ type: TYPE_GREEK_DOCK, commandSlot: 0 }],
    blocker: "Water navigation, shoreline fishing, dock returns, occupancy, and naval visibility.",
  }),
  blockedUnitLane({
    id: TYPE_GREEK_TRANSPORT_SHIP,
    key: "greek-transport-ship",
    label: "Greek Transport Ship",
    culture: CULTURE_GREEK,
    family: "naval",
    gates: ["E"],
    foundationLanes: [WATER_FOUNDATION, TRANSPORT_FOUNDATION],
    requiredGod: NO_GOD,
    trainedAt: [{ type: TYPE_GREEK_DOCK, commandSlot: 1 }],
    blocker: "Water navigation, embark/disembark, capacity, cargo state, and destruction handling.",
  }),
  blockedUnitLane({
    id: TYPE_TRIREME,
    key: "greek-trireme",
    label: "Trireme",
    culture: CULTURE_GREEK,
    family: "naval",
    gates: ["B", "E"],
    foundationLanes: [PROJECTILE_FOUNDATION, WATER_FOUNDATION, NAVAL_COMBAT_FOUNDATION],
    requiredGod: NO_GOD,
    trainedAt: [{ type: TYPE_GREEK_DOCK, commandSlot: 2 }],
    blocker: "Water navigation, naval acquisition/collision, and projectile combat over water.",
  }),
  blockedUnitLane({
    id: TYPE_PENTEKONTER,
    key: "greek-pentekonter",
    label: "Pentekonter",
    culture: CULTURE_GREEK,
    family: "naval",
    gates: ["D", "E"],
    foundationLanes: ["serial-ram-attacks", WATER_FOUNDATION, NAVAL_COMBAT_FOUNDATION],
    requiredGod: NO_GOD,
    trainedAt: [{ type: TYPE_GREEK_DOCK, commandSlot: 3 }],
    blocker: "Water navigation, naval collision, and deterministic ram attack behavior.",
  }),
  blockedUnitLane({
    id: TYPE_JUGGERNAUT,
    key: "greek-juggernaut",
    label: "Juggernaut",
    culture: CULTURE_GREEK,
    family: "naval",
    gates: ["B", "D", "E"],
    foundationLanes: [
      AREA_MINIMUM_RANGE_FOUNDATION,
      SIEGE_FOUNDATION,
      WATER_FOUNDATION,
      NAVAL_COMBAT_FOUNDATION,
    ],
    requiredGod: NO_GOD,
    trainedAt: [{ type: TYPE_GREEK_DOCK, commandSlot: 4 }],
    blocker:
      "Water navigation plus naval projectile-siege area, range, collision, and targeting rules.",
  }),

  greekHero(
    TYPE_JASON,
    "greek-jason",
    "Jason",
    GOD_ZEUS,
    1,
    0,
    ["C"],
    [HERO_FOUNDATION],
    heroBlocker,
  ),
  greekHero(
    TYPE_ODYSSEUS,
    "greek-odysseus",
    "Odysseus",
    GOD_ZEUS,
    2,
    1,
    ["B", "C"],
    [PROJECTILE_FOUNDATION, HERO_FOUNDATION],
    `${heroBlocker} His ranged hero attack must use the projectile contract.`,
  ),
  greekHero(
    TYPE_HERACLES,
    "greek-heracles",
    "Heracles",
    GOD_ZEUS,
    3,
    2,
    ["C"],
    [HERO_FOUNDATION],
    heroBlocker,
  ),
  greekHero(
    TYPE_BELLEROPHON,
    "greek-bellerophon",
    "Bellerophon",
    GOD_ZEUS,
    4,
    3,
    ["C", "D"],
    [HERO_FOUNDATION, SPECIAL_ACTION_FOUNDATION],
    `${heroBlocker} His deterministic jump attack needs command, state, hash, and presentation support.`,
  ),
  greekHero(
    TYPE_THESEUS,
    "greek-theseus",
    "Theseus",
    GOD_POSEIDON,
    1,
    0,
    ["C"],
    [HERO_FOUNDATION],
    heroBlocker,
  ),
  greekHero(
    TYPE_HIPPOLYTA,
    "greek-hippolyta",
    "Hippolyta",
    GOD_POSEIDON,
    2,
    1,
    ["B", "C"],
    [PROJECTILE_FOUNDATION, HERO_FOUNDATION],
    `${heroBlocker} Her ranged hero attack must use the projectile contract.`,
  ),
  greekHero(
    TYPE_ATALANTA,
    "greek-atalanta",
    "Atalanta",
    GOD_POSEIDON,
    3,
    2,
    ["C"],
    [HERO_FOUNDATION],
    heroBlocker,
  ),
  greekHero(
    TYPE_POLYPHEMUS,
    "greek-polyphemus",
    "Polyphemus",
    GOD_POSEIDON,
    4,
    3,
    ["C", "D"],
    [HERO_FOUNDATION, SPECIAL_ACTION_FOUNDATION],
    `${heroBlocker} His deterministic gore attack needs special-action state and presentation.`,
  ),
  greekHero(
    TYPE_AJAX,
    "greek-ajax",
    "Ajax",
    GOD_HADES,
    1,
    0,
    ["C"],
    [HERO_FOUNDATION],
    heroBlocker,
  ),
  greekHero(
    TYPE_CHIRON,
    "greek-chiron",
    "Chiron",
    GOD_HADES,
    2,
    1,
    ["B", "C"],
    [PROJECTILE_FOUNDATION, HERO_FOUNDATION],
    `${heroBlocker} His ranged hero attack must use the projectile contract.`,
  ),
  greekHero(
    TYPE_ACHILLES,
    "greek-achilles",
    "Achilles",
    GOD_HADES,
    3,
    2,
    ["C"],
    [HERO_FOUNDATION],
    heroBlocker,
  ),
  greekHero(
    TYPE_PERSEUS,
    "greek-perseus",
    "Perseus",
    GOD_HADES,
    4,
    3,
    ["C", "D"],
    [HERO_FOUNDATION, SPECIAL_ACTION_FOUNDATION],
    `${heroBlocker} His instant-kill petrification needs faithful target rules, state, and presentation.`,
  ),

  greekTempleMyth(
    TYPE_PEGASUS,
    "greek-pegasus",
    "Pegasus",
    NO_GOD,
    0,
    ["C", "E"],
    [MYTH_FOUNDATION, FLIGHT_FOUNDATION],
    "Myth-unit favor/lifecycle rules plus air navigation, occupancy, scouting, and visibility.",
  ),
  greekTempleMyth(
    TYPE_MINOTAUR,
    "greek-minotaur",
    "Minotaur",
    GOD_ATHENA,
    1,
    ["C", "D"],
    [MYTH_FOUNDATION, SPECIAL_ACTION_FOUNDATION],
    "Myth-unit favor/lifecycle and hero counters plus deterministic gore attack behavior.",
  ),
  greekTempleMyth(
    TYPE_CENTAUR,
    "greek-centaur",
    "Centaur",
    GOD_HERMES,
    1,
    ["B", "C", "D"],
    [PROJECTILE_FOUNDATION, MYTH_FOUNDATION, SPECIAL_ACTION_FOUNDATION],
    "Myth-unit rules plus ordinary and charged ranged attacks with faithful recharge state.",
  ),
  greekTempleMyth(
    TYPE_CYCLOPS,
    "greek-cyclops",
    "Cyclops",
    GOD_ARES,
    1,
    ["C", "D"],
    [MYTH_FOUNDATION, SPECIAL_ACTION_FOUNDATION],
    "Myth-unit rules plus deterministic unit pickup, throw flight, impact, and immunity rules.",
  ),
  greekTempleMyth(
    TYPE_NEMEAN_LION,
    "greek-nemean-lion",
    "Nemean Lion",
    GOD_APHRODITE,
    2,
    ["C", "D"],
    [MYTH_FOUNDATION, SPECIAL_ACTION_FOUNDATION],
    "Myth-unit rules plus deterministic area roar/whirlwind targeting and recharge.",
  ),
  greekTempleMyth(
    TYPE_MANTICORE,
    "greek-manticore",
    "Manticore",
    GOD_APOLLO,
    2,
    ["B", "C", "D"],
    [PROJECTILE_FOUNDATION, MYTH_FOUNDATION, SPECIAL_ACTION_FOUNDATION],
    "Myth-unit rules plus ordinary and charged multi-projectile ranged attacks.",
  ),
  greekTempleMyth(
    TYPE_HYDRA,
    "greek-hydra",
    "Hydra",
    GOD_DIONYSUS,
    2,
    ["C", "D"],
    [MYTH_FOUNDATION, "serial-hydra-head-growth"],
    "Myth-unit rules plus kill-driven head growth, derived attacks, death copying, and hashing.",
  ),
  blockedUnitLane({
    id: TYPE_SCYLLA,
    key: "greek-scylla",
    label: "Scylla",
    culture: CULTURE_GREEK,
    family: "myth",
    gates: ["C", "E"],
    foundationLanes: [MYTH_FOUNDATION, WATER_FOUNDATION, NAVAL_COMBAT_FOUNDATION],
    requiredGod: GOD_DIONYSUS,
    trainedAt: [{ type: TYPE_GREEK_DOCK, commandSlot: 5 }],
    blocker: "Aquatic myth-unit lifecycle, water navigation, naval targeting, and collision rules.",
  }),
  greekTempleMyth(
    TYPE_MEDUSA,
    "greek-medusa",
    "Medusa",
    GOD_HERA,
    3,
    ["B", "C", "D"],
    [PROJECTILE_FOUNDATION, MYTH_FOUNDATION, SPECIAL_ACTION_FOUNDATION],
    "Myth-unit and projectile rules plus faithful petrification targeting, immunity, and recharge.",
  ),
  greekTempleMyth(
    TYPE_COLOSSUS,
    "greek-colossus",
    "Colossus",
    GOD_HEPHAESTUS,
    3,
    ["C", "D"],
    [MYTH_FOUNDATION, "serial-resource-eating-regeneration"],
    "Myth/siege counters plus resource-eating regeneration and its command and hash state.",
  ),
  greekTempleMyth(
    TYPE_CHIMERA,
    "greek-chimera",
    "Chimera",
    GOD_ARTEMIS,
    4,
    ["B", "C", "D"],
    [PROJECTILE_FOUNDATION, MYTH_FOUNDATION, SPECIAL_ACTION_FOUNDATION],
    "Myth-unit rules plus charged fire-breath projectile/area behavior and recharge state.",
  ),
  blockedUnitLane({
    id: TYPE_CARCINOS,
    key: "greek-carcinos",
    label: "Carcinos",
    culture: CULTURE_GREEK,
    family: "myth",
    gates: ["C", "E"],
    foundationLanes: [MYTH_FOUNDATION, WATER_FOUNDATION, NAVAL_COMBAT_FOUNDATION],
    requiredGod: GOD_HERA,
    trainedAt: [{ type: TYPE_GREEK_DOCK, commandSlot: 6 }],
    blocker: "Aquatic myth-unit lifecycle, water navigation, naval targeting, and collision rules.",
  }),
  blockedUnitLane({
    id: TYPE_GREEK_TITAN,
    key: "greek-titan",
    label: "Greek Titan",
    culture: CULTURE_GREEK,
    family: "myth",
    gates: ["C", "D"],
    foundationLanes: [MYTH_FOUNDATION, "serial-titan-gate-awakening"],
    requiredGod: NO_GOD,
    trainedAt: [],
    blocker:
      "Titan Gate research/construction, one-Titan limits, awakening, giant occupancy, and Titan combat rules.",
  }),
] as const satisfies readonly UnitRosterEntry[];
