import { AGE_ARCHAIC, NO_GOD } from "../../../ecs/progression";
import { TYPE_FISH_PERCH } from "../../unit-type-ids";
import {
  CULTURE_SHARED,
  FOOD,
  MOVEMENT_DOMAIN_WATER,
  NO_PREREQUISITE_BUILDINGS,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_RESOURCE,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_FISH_PERCH,
  key: "fish-perch",
  label: "Perch",
  culture: CULTURE_SHARED,
  classes: UNIT_CLASS_RESOURCE,
  maxHp: 1_000,
  lineOfSight: 0,
  movementSpeed: 3,
  movementDomain: MOVEMENT_DOMAIN_WATER,
  resourceGathererDomain: MOVEMENT_DOMAIN_WATER,
  armor: [0.2, 0.2, 0.99],
  attack: null,
  isStatic: false,
  resource: FOOD,
  bodyRadius: 3,
  collidesWithProjectiles: false,
  footprint: 0,
  costFood: 0,
  costWood: 0,
  costGold: 0,
  costFavor: 0,
  buildTicks: 0,
  populationCost: 0,
  popBonus: 0,
  trainExitOffset: 0,
  isDropsite: false,
  requiredAge: AGE_ARCHAIC,
  requiredGod: NO_GOD,
  prerequisiteBuildings: NO_PREREQUISITE_BUILDINGS,
  trainedAt: NO_TYPE_RELATIONSHIPS,
  builtBy: NO_TYPE_RELATIONSHIPS,
} as const satisfies UnitTypeStats;
