import { AGE_HEROIC, GOD_HADES } from "../../../ecs/progression";
import {
  TYPE_ACHILLES,
  TYPE_GREEK_FORTRESS,
  TYPE_GREEK_TEMPLE,
  TYPE_GREEK_TOWN_CENTER,
} from "../../unit-type-ids";
import {
  CULTURE_GREEK,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_HERO,
  UNIT_CLASS_MELEE,
  UNIT_CLASS_MILITARY,
  UNIT_CLASS_MYTH,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_ACHILLES,
  key: "greek-achilles",
  label: "Achilles",
  culture: CULTURE_GREEK,
  classes: UNIT_CLASS_HERO | UNIT_CLASS_MILITARY | UNIT_CLASS_MELEE,
  hero: {
    trainLimit: 1,
    relicCapacity: 1,
    relicPickupRange: 1,
    relicDropOffRange: 1,
  },
  maxHp: 340,
  lineOfSight: 16,
  movementSpeed: 5.5,
  armor: [0.4, 0.45, 0.99],
  attack: {
    kind: "melee",
    damage: [9, 0, 0],
    range: 0.1,
    aggroRange: 16,
    cooldownTicks: 20,
    bonuses: [{ target: { kind: "classes", classes: UNIT_CLASS_MYTH }, multiplier: 7 }],
    cycleVariants: [
      { actionTicks: 20, impactDelayTicks: 9 },
      { actionTicks: 24, impactDelayTicks: 17 },
      { actionTicks: 17, impactDelayTicks: 11 },
    ],
  },
  isStatic: false,
  resource: -1,
  bodyRadius: 0.7,
  collidesWithProjectiles: true,
  footprint: 0,
  costFood: 350,
  costWood: 0,
  costGold: 0,
  costFavor: 4,
  buildTicks: 23 * 20,
  populationCost: 3,
  popBonus: 0,
  trainExitOffset: 0,
  isDropsite: false,
  requiredAge: AGE_HEROIC,
  requiredGod: GOD_HADES,
  prerequisiteBuildings: [TYPE_GREEK_TEMPLE],
  trainedAt: [
    { type: TYPE_GREEK_TOWN_CENTER, commandSlot: 3 },
    { type: TYPE_GREEK_FORTRESS, commandSlot: 2 },
  ],
  builtBy: NO_TYPE_RELATIONSHIPS,
} as const satisfies UnitTypeStats;
