import { AGE_MYTHIC, GOD_ZEUS } from "../../../ecs/progression";
import {
  TYPE_BELLEROPHON,
  TYPE_GREEK_FORTRESS,
  TYPE_GREEK_TEMPLE,
  TYPE_GREEK_TOWN_CENTER,
} from "../../unit-type-ids";
import {
  CULTURE_GREEK,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_AIR,
  UNIT_CLASS_HERO,
  UNIT_CLASS_HUMAN,
  UNIT_CLASS_MELEE,
  UNIT_CLASS_MILITARY,
  UNIT_CLASS_MYTH,
  UNIT_CLASS_SET_ANIMAL,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_BELLEROPHON,
  key: "greek-bellerophon",
  label: "Bellerophon",
  culture: CULTURE_GREEK,
  classes: UNIT_CLASS_HERO | UNIT_CLASS_MILITARY | UNIT_CLASS_MELEE,
  hero: {
    trainLimit: 1,
    relicCapacity: 1,
    relicPickupRange: 1,
    relicDropOffRange: 1,
  },
  maxHp: 400,
  lineOfSight: 16,
  movementSpeed: 6,
  armor: [0.2, 0.4, 0.99],
  attack: {
    kind: "melee",
    damage: [20, 0, 0],
    range: 0.1,
    aggroRange: 16,
    cooldownTicks: 20,
    bonuses: [
      { target: { kind: "classes", classes: UNIT_CLASS_MYTH }, multiplier: 5 },
      { target: { kind: "classes", classes: UNIT_CLASS_SET_ANIMAL }, multiplier: 3 },
    ],
    cycleVariants: [{ actionTicks: 25, impactDelayTicks: 13 }],
  },
  specialAttack: {
    kind: "charged-jump",
    delivery: "target",
    damage: [100, 0, 0],
    minimumRange: 4,
    range: 14,
    bonuses: [{ target: { kind: "classes", classes: UNIT_CLASS_MYTH }, multiplier: 7 }],
    rechargeTicks: 5 * 20,
    takeoffTicks: 0,
    flightTicks: 26,
    landingTicks: 0,
    actionTicks: 26,
    impactDelayTicks: 26,
    // The original single-cycle BRG contains the vertical leap in its morph
    // animation; simulation only drives the source-to-target translation.
    jumpHeight: 0,
    validTargets: [
      { kind: "classes", classes: UNIT_CLASS_HUMAN, excludedClasses: UNIT_CLASS_AIR },
      { kind: "classes", classes: UNIT_CLASS_MYTH, excludedClasses: UNIT_CLASS_AIR },
      { kind: "classes", classes: UNIT_CLASS_HERO, excludedClasses: UNIT_CLASS_AIR },
    ],
  },
  isStatic: false,
  resource: -1,
  bodyRadius: 0.7,
  collidesWithProjectiles: true,
  footprint: 0,
  costFood: 0,
  costWood: 0,
  costGold: 400,
  costFavor: 6,
  buildTicks: 27 * 20,
  populationCost: 4,
  popBonus: 0,
  trainExitOffset: 0,
  isDropsite: false,
  requiredAge: AGE_MYTHIC,
  requiredGod: GOD_ZEUS,
  prerequisiteBuildings: [TYPE_GREEK_TEMPLE],
  trainedAt: [
    { type: TYPE_GREEK_TOWN_CENTER, commandSlot: 4 },
    { type: TYPE_GREEK_FORTRESS, commandSlot: 3 },
  ],
  builtBy: NO_TYPE_RELATIONSHIPS,
} as const satisfies UnitTypeStats;
