import { TICK_HZ } from "../../../clock";
import { AGE_MYTHIC, GOD_HERA } from "../../../ecs/progression";
import { TYPE_CARCINOS, TYPE_GREEK_DOCK } from "../../unit-type-ids";
import {
  AREA_DAMAGE_ENEMIES,
  CULTURE_GREEK,
  MOVEMENT_DOMAIN_WATER,
  NO_DAMAGE_BONUSES,
  NO_PREREQUISITE_BUILDINGS,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_MELEE,
  UNIT_CLASS_MILITARY,
  UNIT_CLASS_MYTH,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_CARCINOS,
  key: "greek-carcinos",
  label: "Carcinos",
  culture: CULTURE_GREEK,
  classes: UNIT_CLASS_MYTH | UNIT_CLASS_MILITARY | UNIT_CLASS_MELEE,
  maxHp: 720,
  lineOfSight: 16,
  movementSpeed: 4.3,
  movementDomain: MOVEMENT_DOMAIN_WATER,
  armor: [0.7, 0.6, 0.8],
  attack: {
    kind: "melee",
    damage: [20, 0, 12],
    range: 0.3,
    aggroRange: 16,
    cooldownTicks: TICK_HZ,
    bonuses: NO_DAMAGE_BONUSES,
    cycleVariants: [
      { actionTicks: 22, impactDelayTicks: 10 },
      { actionTicks: 24, impactDelayTicks: 11 },
    ],
  },
  deathAreaAttack: {
    damage: [300, 0, 0],
    radius: 7.5,
    falloff: "constant",
    damageRelations: AREA_DAMAGE_ENEMIES,
    bonuses: NO_DAMAGE_BONUSES,
  },
  isStatic: false,
  resource: -1,
  bodyRadius: 0.99,
  collidesWithProjectiles: true,
  footprint: 0,
  costFood: 0,
  costWood: 200,
  costGold: 0,
  costFavor: 20,
  buildTicks: 180,
  populationCost: 4,
  popBonus: 0,
  trainExitOffset: 0,
  isDropsite: false,
  requiredAge: AGE_MYTHIC,
  requiredGod: GOD_HERA,
  prerequisiteBuildings: NO_PREREQUISITE_BUILDINGS,
  trainedAt: [{ type: TYPE_GREEK_DOCK, commandSlot: 6 }],
  builtBy: NO_TYPE_RELATIONSHIPS,
} as const satisfies UnitTypeStats;
