import { AGE_CLASSICAL, GOD_HERMES } from "../../../ecs/progression";
import { PROJECTILE_ARROW } from "../../../ecs/projectiles";
import { TYPE_CENTAUR, TYPE_GREEK_TEMPLE } from "../../unit-type-ids";
import {
  CULTURE_GREEK,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_ARCHER,
  UNIT_CLASS_HERO,
  UNIT_CLASS_HUMAN,
  UNIT_CLASS_MILITARY,
  UNIT_CLASS_MYTH,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_CENTAUR,
  key: "greek-centaur",
  label: "Centaur",
  culture: CULTURE_GREEK,
  classes: UNIT_CLASS_MYTH | UNIT_CLASS_ARCHER | UNIT_CLASS_MILITARY,
  maxHp: 220,
  lineOfSight: 20,
  movementSpeed: 5,
  armor: [0.3, 0.35, 0.8],
  attack: {
    kind: "projectile",
    damage: [0, 12, 0],
    range: 12,
    aggroRange: 20,
    cooldownTicks: 20,
    bonuses: [
      { target: { kind: "classes", classes: UNIT_CLASS_MYTH }, multiplier: 2 },
      { target: { kind: "classes", classes: UNIT_CLASS_HERO }, multiplier: 0.25 },
    ],
    launchDelayTicks: 12,
    accuracy: 0.8,
    accuracyReductionFactor: 0,
    aimBonus: 15,
    spreadFactor: 0.25,
    maxSpread: 5,
    trackRating: 5,
    unintentionalDamageMultiplier: 0.3,
    projectile: {
      type: PROJECTILE_ARROW,
      speed: 30,
      lifespanTicks: 40,
      collisionRadius: 0.1,
    },
  },
  specialAttack: {
    kind: "charged-projectile",
    damage: [0, 50, 0],
    range: 12,
    bonuses: [{ target: { kind: "classes", classes: UNIT_CLASS_MYTH }, multiplier: 3 }],
    rechargeTicks: 15 * 20,
    actionTicks: 50,
    impactDelayTicks: 40,
    validTargets: [
      { kind: "classes", classes: UNIT_CLASS_HUMAN },
      { kind: "classes", classes: UNIT_CLASS_MYTH },
    ],
    accuracy: 1,
    accuracyReductionFactor: 0,
    aimBonus: 0,
    spreadFactor: 0,
    maxSpread: 0,
    trackRating: 10,
    unintentionalDamageMultiplier: 1,
    projectile: {
      type: PROJECTILE_ARROW,
      speed: 30,
      lifespanTicks: 40,
      collisionRadius: 0.1,
    },
  },
  isStatic: false,
  resource: -1,
  bodyRadius: 0.99,
  collidesWithProjectiles: true,
  footprint: 0,
  costFood: 0,
  costWood: 200,
  costGold: 0,
  costFavor: 12,
  buildTicks: 19 * 20,
  populationCost: 3,
  popBonus: 0,
  trainExitOffset: 0,
  isDropsite: false,
  requiredAge: AGE_CLASSICAL,
  requiredGod: GOD_HERMES,
  prerequisiteBuildings: [TYPE_GREEK_TEMPLE],
  trainedAt: [{ type: TYPE_GREEK_TEMPLE, commandSlot: 1 }],
  builtBy: NO_TYPE_RELATIONSHIPS,
} as const satisfies UnitTypeStats;
