import { AGE_MYTHIC, GOD_ARTEMIS } from "../../../ecs/progression";
import { PROJECTILE_CHIMERA_FIRE } from "../../../ecs/projectiles";
import { TYPE_CHIMERA, TYPE_GREEK_TEMPLE } from "../../unit-type-ids";
import {
  AREA_DAMAGE_ENEMIES,
  AREA_DAMAGE_NEUTRAL_UNITS,
  CULTURE_GREEK,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_CAVALRY,
  UNIT_CLASS_HERO,
  UNIT_CLASS_HUMAN,
  UNIT_CLASS_MELEE,
  UNIT_CLASS_MILITARY,
  UNIT_CLASS_MYTH,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_CHIMERA,
  key: "greek-chimera",
  label: "Chimera",
  culture: CULTURE_GREEK,
  classes: UNIT_CLASS_MYTH | UNIT_CLASS_CAVALRY | UNIT_CLASS_MILITARY | UNIT_CLASS_MELEE,
  maxHp: 800,
  lineOfSight: 16,
  movementSpeed: 5.3,
  armor: [0.6, 0.6, 0.8],
  attack: {
    kind: "melee",
    damage: [20, 0, 0],
    range: 0.1,
    aggroRange: 16,
    cooldownTicks: 20,
    bonuses: [
      { target: { kind: "classes", classes: UNIT_CLASS_MYTH }, multiplier: 3 },
      { target: { kind: "classes", classes: UNIT_CLASS_HERO }, multiplier: 0.5 },
    ],
    cycleVariants: [{ actionTicks: 20, impactDelayTicks: 9 }],
  },
  specialAttack: {
    kind: "charged-projectile",
    damage: [28, 0, 0],
    range: 8,
    bonuses: [
      { target: { kind: "classes", classes: UNIT_CLASS_MYTH }, multiplier: 3 },
      { target: { kind: "classes", classes: UNIT_CLASS_HERO }, multiplier: 0.25 },
    ],
    rechargeTicks: 20 * 20,
    actionTicks: 40,
    impactDelayTicks: 28,
    validTargets: [
      { kind: "classes", classes: UNIT_CLASS_HUMAN },
      { kind: "classes", classes: UNIT_CLASS_MYTH },
    ],
    accuracy: 1,
    accuracyReductionFactor: 0,
    aimBonus: 0,
    spreadFactor: 0,
    maxSpread: 0,
    trackRating: 6,
    unintentionalDamageMultiplier: 1,
    projectileCount: 3,
    impactArea: {
      radius: 5,
      falloff: "linear",
      damageRelations: AREA_DAMAGE_ENEMIES | AREA_DAMAGE_NEUTRAL_UNITS,
    },
    projectile: {
      type: PROJECTILE_CHIMERA_FIRE,
      speed: 50,
      lifespanTicks: 40,
      collisionRadius: 1,
    },
  },
  isStatic: false,
  resource: -1,
  bodyRadius: 0.99,
  collidesWithProjectiles: true,
  footprint: 0,
  costFood: 0,
  costWood: 0,
  costGold: 300,
  costFavor: 30,
  buildTicks: 20 * 20,
  populationCost: 4,
  popBonus: 0,
  trainExitOffset: 0,
  isDropsite: false,
  requiredAge: AGE_MYTHIC,
  requiredGod: GOD_ARTEMIS,
  prerequisiteBuildings: [TYPE_GREEK_TEMPLE],
  trainedAt: [{ type: TYPE_GREEK_TEMPLE, commandSlot: 4 }],
  builtBy: NO_TYPE_RELATIONSHIPS,
} as const satisfies UnitTypeStats;
