import { AGE_CLASSICAL, GOD_HADES } from "../../../ecs/progression";
import { PROJECTILE_ARROW } from "../../../ecs/projectiles";
import {
  TYPE_CHIRON,
  TYPE_GREEK_FORTRESS,
  TYPE_GREEK_TEMPLE,
  TYPE_GREEK_TOWN_CENTER,
} from "../../unit-type-ids";
import {
  CULTURE_GREEK,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_HERO,
  UNIT_CLASS_MILITARY,
  UNIT_CLASS_MYTH,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_CHIRON,
  key: "greek-chiron",
  label: "Chiron",
  culture: CULTURE_GREEK,
  classes: UNIT_CLASS_HERO | UNIT_CLASS_MILITARY,
  hero: {
    trainLimit: 1,
    relicCapacity: 1,
    relicPickupRange: 1,
    relicDropOffRange: 1,
  },
  maxHp: 300,
  lineOfSight: 20,
  movementSpeed: 5.3,
  armor: [0.2, 0.2, 0.99],
  attack: {
    kind: "projectile",
    damage: [0, 7, 0],
    range: 14,
    aggroRange: 20,
    cooldownTicks: 30,
    bonuses: [{ target: { kind: "classes", classes: UNIT_CLASS_MYTH }, multiplier: 7 }],
    launchDelayTicks: 18,
    accuracy: 0.9,
    accuracyReductionFactor: 1.5,
    aimBonus: 15,
    spreadFactor: 0.25,
    maxSpread: 5,
    trackRating: 5,
    unintentionalDamageMultiplier: 0.3,
    projectile: {
      type: PROJECTILE_ARROW,
      speed: 30,
      lifespanTicks: 2 * 20,
      collisionRadius: 0.1,
    },
  },
  isStatic: false,
  resource: -1,
  bodyRadius: 0.7,
  collidesWithProjectiles: true,
  footprint: 0,
  costFood: 0,
  costWood: 200,
  costGold: 0,
  costFavor: 2,
  buildTicks: 17 * 20,
  populationCost: 2,
  popBonus: 0,
  trainExitOffset: 0,
  isDropsite: false,
  requiredAge: AGE_CLASSICAL,
  requiredGod: GOD_HADES,
  prerequisiteBuildings: [TYPE_GREEK_TEMPLE],
  trainedAt: [
    { type: TYPE_GREEK_TOWN_CENTER, commandSlot: 2 },
    { type: TYPE_GREEK_FORTRESS, commandSlot: 1 },
  ],
  builtBy: NO_TYPE_RELATIONSHIPS,
} as const satisfies UnitTypeStats;
