import { AGE_MYTHIC, GOD_HEPHAESTUS } from "../../../ecs/progression";
import { TYPE_COLOSSUS, TYPE_GREEK_TEMPLE } from "../../unit-type-ids";
import {
  CULTURE_GREEK,
  GOLD,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_HERO,
  UNIT_CLASS_MELEE,
  UNIT_CLASS_MILITARY,
  UNIT_CLASS_MYTH,
  UNIT_CLASS_SIEGE,
  WOOD,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_COLOSSUS,
  key: "greek-colossus",
  label: "Colossus",
  culture: CULTURE_GREEK,
  classes: UNIT_CLASS_MYTH | UNIT_CLASS_SIEGE | UNIT_CLASS_MILITARY | UNIT_CLASS_MELEE,
  maxHp: 1100,
  lineOfSight: 16,
  movementSpeed: 2.4,
  armor: [0.5, 0.8, 0.8],
  attack: {
    kind: "melee",
    damage: [20, 0, 50],
    range: 0.1,
    aggroRange: 16,
    cooldownTicks: 20,
    bonuses: [
      { target: { kind: "classes", classes: UNIT_CLASS_MYTH }, multiplier: 3 },
      { target: { kind: "classes", classes: UNIT_CLASS_HERO }, multiplier: 0.8 },
    ],
    cycleVariants: [
      { actionTicks: 26, impactDelayTicks: 14 },
      { actionTicks: 26, impactDelayTicks: 12 },
    ],
  },
  resourceEat: {
    range: 0.1,
    resourceTypes: [GOLD, WOOD],
    consumePerSecond: 30,
    healPerSecond: 15,
  },
  isStatic: false,
  resource: -1,
  bodyRadius: 0.99,
  collidesWithProjectiles: true,
  footprint: 0,
  costFood: 0,
  costWood: 0,
  costGold: 300,
  costFavor: 40,
  buildTicks: 24 * 20,
  populationCost: 5,
  popBonus: 0,
  trainExitOffset: 0,
  isDropsite: false,
  requiredAge: AGE_MYTHIC,
  requiredGod: GOD_HEPHAESTUS,
  prerequisiteBuildings: [TYPE_GREEK_TEMPLE],
  trainedAt: [{ type: TYPE_GREEK_TEMPLE, commandSlot: 3 }],
  builtBy: NO_TYPE_RELATIONSHIPS,
} as const satisfies UnitTypeStats;
