import { AGE_CLASSICAL, GOD_ARES } from "../../../ecs/progression";
import { TYPE_CYCLOPS, TYPE_GREEK_TEMPLE } from "../../unit-type-ids";
import {
  AREA_DAMAGE_ENEMIES,
  AREA_DAMAGE_NEUTRAL_UNITS,
  CULTURE_GREEK,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_HERO,
  UNIT_CLASS_HUMAN,
  UNIT_CLASS_INFANTRY,
  UNIT_CLASS_MELEE,
  UNIT_CLASS_MILITARY,
  UNIT_CLASS_MYTH,
  UNIT_CLASS_WORKER,
  UNIT_CONDITION_FROZEN,
  UNIT_CONDITION_STONE,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_CYCLOPS,
  key: "greek-cyclops",
  label: "Cyclops",
  culture: CULTURE_GREEK,
  classes: UNIT_CLASS_MYTH | UNIT_CLASS_INFANTRY | UNIT_CLASS_MILITARY | UNIT_CLASS_MELEE,
  maxHp: 500,
  lineOfSight: 16,
  movementSpeed: 3.2,
  armor: [0.4, 0.5, 0.8],
  attack: {
    kind: "melee",
    damage: [15, 0, 12],
    range: 0.1,
    aggroRange: 16,
    cooldownTicks: 20,
    bonuses: [{ target: { kind: "classes", classes: UNIT_CLASS_MYTH }, multiplier: 3 }],
    cycleVariants: [
      { actionTicks: 24, impactDelayTicks: 13 },
      { actionTicks: 32, impactDelayTicks: 20 },
    ],
  },
  specialAttack: {
    kind: "charged-pickup-throw",
    damage: [30, 0, 0],
    range: 0.1,
    bonuses: [],
    rechargeTicks: 15 * 20,
    actionTicks: 5 * 20,
    impactDelayTicks: 69,
    pickupDelayTicks: 23,
    throwDelayTicks: 69,
    validTargets: [
      { kind: "classes", classes: UNIT_CLASS_WORKER, excludedClasses: UNIT_CLASS_HERO },
      {
        kind: "classes",
        classes: UNIT_CLASS_HUMAN | UNIT_CLASS_MILITARY,
        excludedClasses: UNIT_CLASS_HERO,
      },
    ],
    invalidTargetConditions: UNIT_CONDITION_FROZEN | UNIT_CONDITION_STONE,
    radius: 10,
    falloff: "constant",
    damageRelations: AREA_DAMAGE_ENEMIES | AREA_DAMAGE_NEUTRAL_UNITS,
  },
  isStatic: false,
  resource: -1,
  bodyRadius: 0.99,
  collidesWithProjectiles: true,
  footprint: 0,
  costFood: 250,
  costWood: 0,
  costGold: 0,
  costFavor: 22,
  buildTicks: 20 * 20,
  populationCost: 4,
  popBonus: 0,
  trainExitOffset: 0,
  isDropsite: false,
  requiredAge: AGE_CLASSICAL,
  requiredGod: GOD_ARES,
  prerequisiteBuildings: [TYPE_GREEK_TEMPLE],
  trainedAt: [{ type: TYPE_GREEK_TEMPLE, commandSlot: 1 }],
  builtBy: NO_TYPE_RELATIONSHIPS,
} as const satisfies UnitTypeStats;
