import { AGE_CLASSICAL, NO_GOD } from "../../../ecs/progression";
import { poseidonMilitiaDeathSpawn } from "../../death-spawns";
import { TYPE_GREEK_FARM, TYPE_GREEK_VILLAGER } from "../../unit-type-ids";
import {
  CULTURE_GREEK,
  FOOD,
  NO_PREREQUISITE_BUILDINGS,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_BUILDING,
  UNIT_CLASS_RESOURCE,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_GREEK_FARM,
  key: "greek-farm",
  label: "Farm",
  culture: CULTURE_GREEK,
  classes: UNIT_CLASS_BUILDING | UNIT_CLASS_RESOURCE,
  maxHp: 150,
  lineOfSight: 6,
  movementSpeed: 0,
  armor: [0.3, 0.8, 0.05],
  attack: null,
  deathSpawn: poseidonMilitiaDeathSpawn(2),
  isStatic: true,
  resource: FOOD,
  unlimitedResourceSupply: true,
  singleGatherer: true,
  bodyRadius: 3,
  collidesWithUnits: false,
  collidesWithProjectiles: true,
  footprint: 3,
  costFood: 0,
  costWood: 75,
  costGold: 0,
  costFavor: 0,
  buildTicks: 10 * 20,
  populationCost: 0,
  popBonus: 0,
  trainExitOffset: 0,
  isDropsite: false,
  requiredAge: AGE_CLASSICAL,
  requiredGod: NO_GOD,
  prerequisiteBuildings: NO_PREREQUISITE_BUILDINGS,
  trainedAt: NO_TYPE_RELATIONSHIPS,
  builtBy: [{ type: TYPE_GREEK_VILLAGER, commandSlot: 11 }],
} as const satisfies UnitTypeStats;
