import { AGE_MYTHIC, NO_GOD } from "../../../ecs/progression";
import { PROJECTILE_BALLISTA_BOLT } from "../../../ecs/projectiles";
import { TYPE_GREEK_FORTRESS, TYPE_HELEPOLIS } from "../../unit-type-ids";
import {
  CULTURE_GREEK,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_ARCHER,
  UNIT_CLASS_HERO,
  UNIT_CLASS_HUMAN,
  UNIT_CLASS_INFANTRY,
  UNIT_CLASS_MILITARY,
  UNIT_CLASS_SIEGE,
  UNIT_CLASS_WORKER,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_HELEPOLIS,
  key: "greek-helepolis",
  label: "Helepolis",
  culture: CULTURE_GREEK,
  classes: UNIT_CLASS_MILITARY | UNIT_CLASS_SIEGE,
  maxHp: 700,
  lineOfSight: 18,
  movementSpeed: 2.9,
  armor: [0.2, 0.96, 0.5],
  attack: {
    kind: "projectile",
    damage: [0, 5, 17],
    range: 10,
    aggroRange: 18,
    cooldownTicks: 2 * 20,
    bonuses: [],
    autoAcquireBuildings: true,
    launchDelayTicks: 16,
    accuracy: 0.8,
    accuracyReductionFactor: 1.5,
    aimBonus: 15,
    spreadFactor: 0.1,
    maxSpread: 5,
    trackRating: 2,
    unintentionalDamageMultiplier: 0.3,
    projectileCount: 3,
    projectile: {
      type: PROJECTILE_BALLISTA_BOLT,
      speed: 30,
      lifespanTicks: 2 * 20,
      collisionRadius: 0.1,
    },
  },
  garrison: {
    capacity: 5,
    enterRange: 4,
    validOccupants: [
      { kind: "classes", classes: UNIT_CLASS_WORKER },
      { kind: "classes", classes: UNIT_CLASS_HERO },
      { kind: "classes", classes: UNIT_CLASS_HUMAN | UNIT_CLASS_INFANTRY },
      { kind: "classes", classes: UNIT_CLASS_HUMAN | UNIT_CLASS_ARCHER },
      { kind: "unit", key: "egyptian-pharaoh" },
      { kind: "unit", key: "egyptian-priest" },
      { kind: "unit", key: "egyptian-son-of-osiris" },
    ],
    attackMultiplierPerOccupant: 0.05,
    ejectOnDeath: true,
  },
  isStatic: false,
  resource: -1,
  bodyRadius: 0.99,
  collidesWithProjectiles: true,
  footprint: 0,
  costFood: 0,
  costWood: 300,
  costGold: 200,
  costFavor: 0,
  buildTicks: 24 * 20,
  populationCost: 4,
  popBonus: 0,
  trainExitOffset: 0,
  isDropsite: false,
  requiredAge: AGE_MYTHIC,
  requiredGod: NO_GOD,
  prerequisiteBuildings: [TYPE_GREEK_FORTRESS],
  trainedAt: [{ type: TYPE_GREEK_FORTRESS, commandSlot: 5 }],
  builtBy: NO_TYPE_RELATIONSHIPS,
} as const satisfies UnitTypeStats;
