import { AGE_CLASSICAL, NO_GOD } from "../../../ecs/progression";
import { TYPE_GREEK_STABLE, TYPE_HIPPIKON } from "../../unit-type-ids";
import {
  CULTURE_GREEK,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_ARCHER,
  UNIT_CLASS_CAVALRY,
  UNIT_CLASS_HUMAN,
  UNIT_CLASS_MELEE,
  UNIT_CLASS_MILITARY,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_HIPPIKON,
  key: "greek-hippikon",
  label: "Hippikon",
  culture: CULTURE_GREEK,
  classes: UNIT_CLASS_HUMAN | UNIT_CLASS_CAVALRY | UNIT_CLASS_MILITARY | UNIT_CLASS_MELEE,
  maxHp: 150,
  lineOfSight: 8,
  movementSpeed: 5.5,
  armor: [0.1, 0.25, 0.99],
  attack: {
    kind: "melee",
    damage: [10, 0, 0],
    range: 0.3,
    aggroRange: 8,
    cooldownTicks: 30,
    bonuses: [{ target: { kind: "classes", classes: UNIT_CLASS_ARCHER }, multiplier: 1.25 }],
  },
  isStatic: false,
  resource: -1,
  bodyRadius: 0.7,
  collidesWithProjectiles: true,
  footprint: 0,
  costFood: 40,
  costWood: 0,
  costGold: 80,
  costFavor: 0,
  buildTicks: 15 * 20,
  populationCost: 3,
  popBonus: 0,
  trainExitOffset: 0,
  isDropsite: false,
  requiredAge: AGE_CLASSICAL,
  requiredGod: NO_GOD,
  prerequisiteBuildings: [TYPE_GREEK_STABLE],
  trainedAt: [{ type: TYPE_GREEK_STABLE, commandSlot: 0 }],
  builtBy: NO_TYPE_RELATIONSHIPS,
} as const satisfies UnitTypeStats;
