import { AGE_CLASSICAL, NO_GOD } from "../../../ecs/progression";
import { TYPE_GREEK_MILITARY_ACADEMY, TYPE_HOPLITE } from "../../unit-type-ids";
import {
  CULTURE_GREEK,
  NO_DAMAGE_BONUSES,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_HUMAN,
  UNIT_CLASS_INFANTRY,
  UNIT_CLASS_MELEE,
  UNIT_CLASS_MILITARY,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_HOPLITE,
  key: "greek-hoplite",
  label: "Hoplite",
  culture: CULTURE_GREEK,
  classes: UNIT_CLASS_HUMAN | UNIT_CLASS_INFANTRY | UNIT_CLASS_MILITARY | UNIT_CLASS_MELEE,
  maxHp: 115,
  lineOfSight: 16,
  movementSpeed: 4.2,
  armor: [0.35, 0.15, 0.99],
  attack: {
    kind: "melee",
    damage: [8, 0, 0],
    range: 0.3,
    aggroRange: 16,
    cooldownTicks: 30,
    bonuses: NO_DAMAGE_BONUSES,
  },
  isStatic: false,
  resource: -1,
  bodyRadius: 0.49,
  collidesWithProjectiles: true,
  footprint: 0,
  costFood: 50,
  costWood: 0,
  costGold: 40,
  costFavor: 0,
  buildTicks: 14 * 20,
  populationCost: 2,
  popBonus: 0,
  trainExitOffset: 0,
  isDropsite: false,
  requiredAge: AGE_CLASSICAL,
  requiredGod: NO_GOD,
  prerequisiteBuildings: [TYPE_GREEK_MILITARY_ACADEMY],
  trainedAt: [{ type: TYPE_GREEK_MILITARY_ACADEMY, commandSlot: 0 }],
  builtBy: NO_TYPE_RELATIONSHIPS,
} as const satisfies UnitTypeStats;
