import { AGE_HEROIC, NO_GOD } from "../../../ecs/progression";
import { PROJECTILE_BALLISTA_BOLT } from "../../../ecs/projectiles";
import { TYPE_GREEK_DOCK, TYPE_JUGGERNAUT } from "../../unit-type-ids";
import {
  CULTURE_GREEK,
  MOVEMENT_DOMAIN_WATER,
  NO_PREREQUISITE_BUILDINGS,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_BUILDING,
  UNIT_CLASS_MILITARY,
  UNIT_CLASS_MYTH,
  UNIT_CLASS_SHIP,
  UNIT_CLASS_SIEGE,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_JUGGERNAUT,
  key: "greek-juggernaut",
  label: "Juggernaut",
  culture: CULTURE_GREEK,
  classes: UNIT_CLASS_MILITARY | UNIT_CLASS_SHIP | UNIT_CLASS_SIEGE,
  maxHp: 480,
  lineOfSight: 24,
  movementSpeed: 4.8,
  movementDomain: MOVEMENT_DOMAIN_WATER,
  armor: [0.1, 0.5, 0.1],
  attack: {
    kind: "projectile",
    damage: [0, 0, 6],
    range: 18,
    aggroRange: 24,
    cooldownTicks: 70,
    bonuses: [
      {
        target: { kind: "classes", classes: UNIT_CLASS_SHIP, excludedClasses: UNIT_CLASS_MYTH },
        multiplier: 3.5,
      },
      { target: { kind: "classes", classes: UNIT_CLASS_MYTH }, multiplier: 3.5 },
      { target: { kind: "classes", classes: UNIT_CLASS_BUILDING }, multiplier: 1.75 },
    ],
    autoAcquireBuildings: true,
    launchDelayTicks: 28,
    accuracy: 0.8,
    accuracyReductionFactor: 2,
    aimBonus: 15,
    spreadFactor: 0.25,
    maxSpread: 5,
    trackRating: 4,
    unintentionalDamageMultiplier: 0.5,
    projectileCount: 4,
    projectile: {
      type: PROJECTILE_BALLISTA_BOLT,
      speed: 30,
      lifespanTicks: 40,
      collisionRadius: 0.1,
    },
  },
  isStatic: false,
  resource: -1,
  bodyRadius: 0.99,
  collidesWithProjectiles: true,
  footprint: 0,
  costFood: 0,
  costWood: 100,
  costGold: 100,
  costFavor: 0,
  buildTicks: 340,
  populationCost: 3,
  popBonus: 0,
  trainExitOffset: 0,
  isDropsite: false,
  requiredAge: AGE_HEROIC,
  requiredGod: NO_GOD,
  prerequisiteBuildings: NO_PREREQUISITE_BUILDINGS,
  trainedAt: [{ type: TYPE_GREEK_DOCK, commandSlot: 4 }],
  builtBy: NO_TYPE_RELATIONSHIPS,
} as const satisfies UnitTypeStats;
