import { AGE_ARCHAIC, NO_GOD } from "../../../ecs/progression";
import { TYPE_KATASKOPOS } from "../../unit-type-ids";
import {
  CULTURE_GREEK,
  NO_DAMAGE_BONUSES,
  NO_PREREQUISITE_BUILDINGS,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_HUMAN,
  UNIT_CLASS_MELEE,
  UNIT_CLASS_MILITARY,
  UNIT_CLASS_SCOUT,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_KATASKOPOS,
  key: "greek-kataskopos",
  label: "Kataskopos",
  culture: CULTURE_GREEK,
  classes: UNIT_CLASS_HUMAN | UNIT_CLASS_MILITARY | UNIT_CLASS_MELEE | UNIT_CLASS_SCOUT,
  maxHp: 70,
  lineOfSight: 14,
  movementSpeed: 5.5,
  armor: [0.1, 0.7, 0.99],
  attack: {
    kind: "melee",
    damage: [2, 0, 0],
    range: 0.1,
    aggroRange: 14,
    cooldownTicks: 20,
    bonuses: NO_DAMAGE_BONUSES,
    autoAcquire: false,
    cycleVariants: [
      { actionTicks: 20, impactDelayTicks: 10 },
      { actionTicks: 24, impactDelayTicks: 16 },
    ],
  },
  isStatic: false,
  resource: -1,
  bodyRadius: 0.7,
  collidesWithProjectiles: true,
  footprint: 0,
  costFood: 75,
  costWood: 0,
  costGold: 0,
  costFavor: 0,
  buildTicks: 0,
  populationCost: 2,
  popBonus: 0,
  trainExitOffset: 0,
  isDropsite: false,
  requiredAge: AGE_ARCHAIC,
  requiredGod: NO_GOD,
  prerequisiteBuildings: NO_PREREQUISITE_BUILDINGS,
  trainedAt: NO_TYPE_RELATIONSHIPS,
  builtBy: NO_TYPE_RELATIONSHIPS,
} as const satisfies UnitTypeStats;
