import { AGE_HEROIC, GOD_APOLLO } from "../../../ecs/progression";
import { PROJECTILE_MANTICORE_BARB } from "../../../ecs/projectiles";
import { TYPE_GREEK_TEMPLE, TYPE_MANTICORE } from "../../unit-type-ids";
import {
  AREA_DAMAGE_ENEMIES,
  CULTURE_GREEK,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_ARCHER,
  UNIT_CLASS_HERO,
  UNIT_CLASS_HUMAN,
  UNIT_CLASS_MILITARY,
  UNIT_CLASS_MYTH,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_MANTICORE,
  key: "greek-manticore",
  label: "Manticore",
  culture: CULTURE_GREEK,
  classes: UNIT_CLASS_MYTH | UNIT_CLASS_ARCHER | UNIT_CLASS_MILITARY,
  maxHp: 420,
  lineOfSight: 20,
  movementSpeed: 4.3,
  armor: [0.3, 0.6, 0.8],
  attack: {
    kind: "projectile",
    damage: [0, 11, 0],
    range: 16,
    aggroRange: 20,
    cooldownTicks: 20,
    bonuses: [
      { target: { kind: "classes", classes: UNIT_CLASS_MYTH }, multiplier: 2 },
      { target: { kind: "classes", classes: UNIT_CLASS_HERO }, multiplier: 0.1 },
    ],
    launchDelayTicks: 11,
    accuracy: 0.9,
    accuracyReductionFactor: 2,
    aimBonus: 15,
    spreadFactor: 0.3,
    maxSpread: 8,
    trackRating: 5,
    unintentionalDamageMultiplier: 1,
    projectileCount: 3,
    projectile: {
      type: PROJECTILE_MANTICORE_BARB,
      speed: 30,
      lifespanTicks: 40,
      collisionRadius: 0.1,
    },
  },
  specialAttack: {
    kind: "charged-projectile",
    damage: [0, 15, 0],
    range: 16,
    bonuses: [{ target: { kind: "classes", classes: UNIT_CLASS_HERO }, multiplier: 0.01 }],
    rechargeTicks: 15 * 20,
    actionTicks: 19,
    impactDelayTicks: 11,
    validTargets: [
      { kind: "classes", classes: UNIT_CLASS_HUMAN },
      { kind: "classes", classes: UNIT_CLASS_MYTH },
    ],
    accuracy: 0.9,
    accuracyReductionFactor: 2,
    aimBonus: 15,
    spreadFactor: 0.25,
    maxSpread: 5,
    trackRating: 5,
    unintentionalDamageMultiplier: 1,
    projectileCount: 6,
    impactArea: {
      radius: 4,
      falloff: "linear",
      damageRelations: AREA_DAMAGE_ENEMIES,
    },
    projectile: {
      type: PROJECTILE_MANTICORE_BARB,
      speed: 30,
      lifespanTicks: 40,
      collisionRadius: 0.1,
    },
  },
  isStatic: false,
  resource: -1,
  bodyRadius: 0.99,
  collidesWithProjectiles: true,
  footprint: 0,
  costFood: 0,
  costWood: 300,
  costGold: 0,
  costFavor: 28,
  buildTicks: 17 * 20,
  populationCost: 5,
  popBonus: 0,
  trainExitOffset: 0,
  isDropsite: false,
  requiredAge: AGE_HEROIC,
  requiredGod: GOD_APOLLO,
  prerequisiteBuildings: [TYPE_GREEK_TEMPLE],
  trainedAt: [{ type: TYPE_GREEK_TEMPLE, commandSlot: 2 }],
  builtBy: NO_TYPE_RELATIONSHIPS,
} as const satisfies UnitTypeStats;
