import { AGE_MYTHIC, GOD_HERA } from "../../../ecs/progression";
import { PROJECTILE_ARROW } from "../../../ecs/projectiles";
import { TYPE_GREEK_TEMPLE, TYPE_MEDUSA } from "../../unit-type-ids";
import {
  CULTURE_GREEK,
  NO_DAMAGE_BONUSES,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_AIR,
  UNIT_CLASS_ARCHER,
  UNIT_CLASS_HERO,
  UNIT_CLASS_HUMAN,
  UNIT_CLASS_HUNTABLE,
  UNIT_CLASS_MILITARY,
  UNIT_CLASS_MYTH,
  UNIT_CLASS_SET_ANIMAL,
  UNIT_CONDITION_FROZEN,
  UNIT_CONDITION_STONE,
  type UnitTypeStats,
} from "../../unit-type-schema";

const terminalTargetExclusions = UNIT_CLASS_HERO | UNIT_CLASS_AIR;

export const definition = {
  id: TYPE_MEDUSA,
  key: "greek-medusa",
  label: "Medusa",
  culture: CULTURE_GREEK,
  classes: UNIT_CLASS_MYTH | UNIT_CLASS_ARCHER | UNIT_CLASS_MILITARY,
  maxHp: 360,
  lineOfSight: 18,
  movementSpeed: 4.3,
  armor: [0.6, 0.7, 0.8],
  attack: {
    kind: "projectile",
    damage: [0, 15, 12.5],
    range: 10,
    aggroRange: 18,
    cooldownTicks: 20,
    bonuses: NO_DAMAGE_BONUSES,
    launchDelayTicks: 13,
    accuracy: 0.8,
    accuracyReductionFactor: 1.5,
    aimBonus: 15,
    spreadFactor: 0.25,
    maxSpread: 5,
    trackRating: 5,
    unintentionalDamageMultiplier: 0.3,
    projectile: {
      type: PROJECTILE_ARROW,
      speed: 30,
      lifespanTicks: 40,
      collisionRadius: 0.1,
    },
  },
  specialAttack: {
    kind: "charged-terminal",
    effect: "petrify-kill",
    damage: [0, 0, 0],
    range: 10,
    bonuses: NO_DAMAGE_BONUSES,
    rechargeTicks: 20 * 20,
    actionTicks: 40,
    impactDelayTicks: 24,
    validTargets: [
      {
        kind: "classes",
        classes: UNIT_CLASS_HUMAN,
        excludedClasses: terminalTargetExclusions,
      },
      {
        kind: "classes",
        classes: UNIT_CLASS_HUNTABLE,
        excludedClasses: terminalTargetExclusions,
      },
      {
        kind: "classes",
        classes: UNIT_CLASS_MYTH,
        excludedClasses: terminalTargetExclusions,
      },
      {
        kind: "classes",
        classes: UNIT_CLASS_SET_ANIMAL,
        excludedClasses: terminalTargetExclusions,
      },
    ],
    invalidTargetConditions: UNIT_CONDITION_FROZEN | UNIT_CONDITION_STONE,
  },
  isStatic: false,
  resource: -1,
  bodyRadius: 0.99,
  collidesWithProjectiles: true,
  footprint: 0,
  costFood: 0,
  costWood: 0,
  costGold: 250,
  costFavor: 40,
  buildTicks: 20 * 20,
  populationCost: 5,
  popBonus: 0,
  trainExitOffset: 0,
  isDropsite: false,
  requiredAge: AGE_MYTHIC,
  requiredGod: GOD_HERA,
  prerequisiteBuildings: [TYPE_GREEK_TEMPLE],
  trainedAt: [{ type: TYPE_GREEK_TEMPLE, commandSlot: 3 }],
  builtBy: NO_TYPE_RELATIONSHIPS,
} as const satisfies UnitTypeStats;
