import { AGE_ARCHAIC, GOD_POSEIDON } from "../../../ecs/progression";
import { TYPE_MILITIA } from "../../unit-type-ids";
import {
  CULTURE_GREEK,
  NO_DAMAGE_BONUSES,
  NO_PREREQUISITE_BUILDINGS,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_HUMAN,
  UNIT_CLASS_INFANTRY,
  UNIT_CLASS_MELEE,
  UNIT_CLASS_MILITARY,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_MILITIA,
  key: "militia",
  label: "Militia",
  culture: CULTURE_GREEK,
  classes: UNIT_CLASS_HUMAN | UNIT_CLASS_INFANTRY | UNIT_CLASS_MILITARY | UNIT_CLASS_MELEE,
  maxHp: 100,
  lineOfSight: 20,
  movementSpeed: 4.8,
  armor: [0.3, 0.2, 0.99],
  attack: {
    kind: "melee",
    damage: [7, 0, 0],
    range: 0.3,
    aggroRange: 20,
    cooldownTicks: 20,
    bonuses: NO_DAMAGE_BONUSES,
  },
  isStatic: false,
  resource: -1,
  bodyRadius: 0.49,
  collidesWithProjectiles: true,
  footprint: 0,
  costFood: 0,
  costWood: 0,
  costGold: 0,
  costFavor: 0,
  buildTicks: 0,
  populationCost: 1,
  popBonus: 0,
  trainExitOffset: 0,
  isDropsite: false,
  requiredAge: AGE_ARCHAIC,
  requiredGod: GOD_POSEIDON,
  prerequisiteBuildings: NO_PREREQUISITE_BUILDINGS,
  trainedAt: NO_TYPE_RELATIONSHIPS,
  builtBy: NO_TYPE_RELATIONSHIPS,
} as const satisfies UnitTypeStats;
