import { AGE_CLASSICAL, GOD_POSEIDON } from "../../../ecs/progression";
import { TYPE_MILITIA } from "../../unit-type-ids";
import {
  CULTURE_GREEK,
  NO_ARMOR,
  NO_DAMAGE_BONUSES,
  NO_PREREQUISITE_BUILDINGS,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_HUMAN,
  UNIT_CLASS_INFANTRY,
  UNIT_CLASS_MELEE,
  UNIT_CLASS_MILITARY,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_MILITIA,
  key: "militia",
  label: "Militia",
  culture: CULTURE_GREEK,
  classes: UNIT_CLASS_HUMAN | UNIT_CLASS_INFANTRY | UNIT_CLASS_MILITARY | UNIT_CLASS_MELEE,
  maxHp: 40,
  lineOfSight: 10,
  movementSpeed: 3,
  armor: NO_ARMOR,
  meleeAttack: {
    damage: [5, 0, 0],
    range: 1.2,
    aggroRange: 10,
    cooldownTicks: 20,
    bonuses: NO_DAMAGE_BONUSES,
  },
  isStatic: false,
  resource: -1,
  bodyRadius: 0.3,
  footprint: 0,
  costFood: 0,
  costWood: 0,
  costGold: 0,
  costFavor: 0,
  buildTicks: 0,
  populationCost: 1,
  popBonus: 0,
  trainExitOffset: 0,
  isDropsite: false,
  requiredAge: AGE_CLASSICAL,
  requiredGod: GOD_POSEIDON,
  prerequisiteBuildings: NO_PREREQUISITE_BUILDINGS,
  trainedAt: NO_TYPE_RELATIONSHIPS,
  builtBy: NO_TYPE_RELATIONSHIPS,
} as const satisfies UnitTypeStats;
