import { AGE_CLASSICAL, GOD_ATHENA } from "../../../ecs/progression";
import { TYPE_GREEK_TEMPLE, TYPE_MINOTAUR } from "../../unit-type-ids";
import {
  CULTURE_GREEK,
  NO_DAMAGE_BONUSES,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_HUMAN,
  UNIT_CLASS_INFANTRY,
  UNIT_CLASS_MELEE,
  UNIT_CLASS_MILITARY,
  UNIT_CLASS_MYTH,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_MINOTAUR,
  key: "greek-minotaur",
  label: "Minotaur",
  culture: CULTURE_GREEK,
  classes: UNIT_CLASS_MYTH | UNIT_CLASS_INFANTRY | UNIT_CLASS_MILITARY | UNIT_CLASS_MELEE,
  maxHp: 300,
  lineOfSight: 20,
  movementSpeed: 4,
  armor: [0.6, 0.5, 0.8],
  attack: {
    kind: "melee",
    damage: [15, 0, 10],
    range: 0.1,
    aggroRange: 20,
    cooldownTicks: 20,
    bonuses: [{ target: { kind: "classes", classes: UNIT_CLASS_MYTH }, multiplier: 3 }],
  },
  specialAttack: {
    kind: "charged-melee",
    damage: [60, 0, 0],
    range: 0.1,
    bonuses: NO_DAMAGE_BONUSES,
    rechargeTicks: 15 * 20,
    actionTicks: 2 * 20,
    impactDelayTicks: 19,
    validTargets: [
      { kind: "classes", classes: UNIT_CLASS_HUMAN },
      { kind: "classes", classes: UNIT_CLASS_MYTH | UNIT_CLASS_INFANTRY },
    ],
    targetReaction: {
      kind: "thrown",
      distanceBase: 8,
      distanceRandomRange: 2,
      maxVelocityBase: 12,
      maxVelocityRandomRange: 4,
      maxHeightBase: 6,
      maxHeightRandomRange: 2,
      bounceBase: 1,
      bounceRandomRange: 2,
    },
  },
  isStatic: false,
  resource: -1,
  bodyRadius: 0.99,
  collidesWithProjectiles: true,
  footprint: 0,
  costFood: 200,
  costWood: 0,
  costGold: 0,
  costFavor: 16,
  buildTicks: 20 * 20,
  populationCost: 4,
  popBonus: 0,
  trainExitOffset: 0,
  isDropsite: false,
  requiredAge: AGE_CLASSICAL,
  requiredGod: GOD_ATHENA,
  prerequisiteBuildings: [TYPE_GREEK_TEMPLE],
  trainedAt: [{ type: TYPE_GREEK_TEMPLE, commandSlot: 1 }],
  builtBy: NO_TYPE_RELATIONSHIPS,
} as const satisfies UnitTypeStats;
