import { AGE_HEROIC, GOD_APHRODITE } from "../../../ecs/progression";
import { TYPE_GREEK_TEMPLE, TYPE_NEMEAN_LION } from "../../unit-type-ids";
import {
  AREA_DAMAGE_ENEMIES,
  AREA_DAMAGE_NEUTRAL_UNITS,
  CULTURE_GREEK,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_CAVALRY,
  UNIT_CLASS_HERO,
  UNIT_CLASS_HUMAN,
  UNIT_CLASS_MELEE,
  UNIT_CLASS_MILITARY,
  UNIT_CLASS_MYTH,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_NEMEAN_LION,
  key: "greek-nemean-lion",
  label: "Nemean Lion",
  culture: CULTURE_GREEK,
  classes: UNIT_CLASS_MYTH | UNIT_CLASS_CAVALRY | UNIT_CLASS_MILITARY | UNIT_CLASS_MELEE,
  maxHp: 660,
  lineOfSight: 16,
  movementSpeed: 4.8,
  armor: [0.3, 0.6, 0.8],
  attack: {
    kind: "melee",
    // Classic stores ordinary attack damage as DPS. The selected source clip
    // scales the landed hit by its duration relative to this one-second rate.
    damage: [20, 0, 10],
    range: 0.1,
    aggroRange: 16,
    cooldownTicks: 20,
    bonuses: [
      { target: { kind: "classes", classes: UNIT_CLASS_MYTH }, multiplier: 2 },
      { target: { kind: "classes", classes: UNIT_CLASS_HERO }, multiplier: 0.5 },
    ],
    cycleVariants: [
      { actionTicks: 24, impactDelayTicks: 11 },
      { actionTicks: 18, impactDelayTicks: 8 },
    ],
  },
  specialAttack: {
    kind: "charged-area-pulse",
    damage: [12, 0, 0],
    range: 0.1,
    radius: 10,
    falloff: "linear",
    damageRelations: AREA_DAMAGE_ENEMIES | AREA_DAMAGE_NEUTRAL_UNITS,
    bonuses: [{ target: { kind: "classes", classes: UNIT_CLASS_HERO }, multiplier: 0.01 }],
    rechargeTicks: 20 * 20,
    actionTicks: 3 * 20,
    impactDelayTicks: 24,
    validTargets: [
      { kind: "classes", classes: UNIT_CLASS_HUMAN },
      { kind: "classes", classes: UNIT_CLASS_MYTH },
    ],
  },
  isStatic: false,
  resource: -1,
  bodyRadius: 0.99,
  collidesWithProjectiles: true,
  footprint: 0,
  costFood: 0,
  costWood: 0,
  costGold: 250,
  costFavor: 22,
  buildTicks: 20 * 20,
  populationCost: 4,
  popBonus: 0,
  trainExitOffset: 0,
  isDropsite: false,
  requiredAge: AGE_HEROIC,
  requiredGod: GOD_APHRODITE,
  prerequisiteBuildings: [TYPE_GREEK_TEMPLE],
  trainedAt: [{ type: TYPE_GREEK_TEMPLE, commandSlot: 2 }],
  builtBy: NO_TYPE_RELATIONSHIPS,
} as const satisfies UnitTypeStats;
