import { AGE_HEROIC, NO_GOD } from "../../../ecs/progression";
import { PROJECTILE_SPEAR } from "../../../ecs/projectiles";
import { TYPE_GREEK_ARCHERY_RANGE, TYPE_PELTAST } from "../../unit-type-ids";
import {
  CULTURE_GREEK,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_ARCHER,
  UNIT_CLASS_HUMAN,
  UNIT_CLASS_MILITARY,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_PELTAST,
  key: "greek-peltast",
  label: "Peltast",
  culture: CULTURE_GREEK,
  classes: UNIT_CLASS_HUMAN | UNIT_CLASS_MILITARY | UNIT_CLASS_ARCHER,
  maxHp: 70,
  lineOfSight: 20,
  movementSpeed: 4,
  armor: [0.15, 0.2, 0.99],
  attack: {
    kind: "projectile",
    damage: [0, 3, 0],
    range: 16,
    aggroRange: 20,
    cooldownTicks: 30,
    bonuses: [
      { target: { kind: "classes", classes: UNIT_CLASS_ARCHER }, multiplier: 4 },
      { target: { kind: "unit", key: "norse-throwing-axeman" }, multiplier: 2 },
    ],
    launchDelayTicks: 12,
    accuracy: 0.8,
    accuracyReductionFactor: 1.5,
    aimBonus: 15,
    spreadFactor: 0.25,
    maxSpread: 5,
    trackRating: 5,
    unintentionalDamageMultiplier: 0.3,
    projectile: {
      type: PROJECTILE_SPEAR,
      speed: 30,
      lifespanTicks: 2 * 20,
      collisionRadius: 0.1,
    },
  },
  isStatic: false,
  resource: -1,
  bodyRadius: 0.49,
  collidesWithProjectiles: true,
  footprint: 0,
  costFood: 0,
  costWood: 60,
  costGold: 20,
  costFavor: 0,
  buildTicks: 9 * 20,
  populationCost: 2,
  popBonus: 0,
  trainExitOffset: 0,
  isDropsite: false,
  requiredAge: AGE_HEROIC,
  requiredGod: NO_GOD,
  prerequisiteBuildings: [TYPE_GREEK_ARCHERY_RANGE],
  trainedAt: [{ type: TYPE_GREEK_ARCHERY_RANGE, commandSlot: 1 }],
  builtBy: NO_TYPE_RELATIONSHIPS,
} as const satisfies UnitTypeStats;
