import { AGE_MYTHIC, GOD_HADES } from "../../../ecs/progression";
import {
  TYPE_GREEK_FORTRESS,
  TYPE_GREEK_TEMPLE,
  TYPE_GREEK_TOWN_CENTER,
  TYPE_PERSEUS,
} from "../../unit-type-ids";
import {
  CULTURE_GREEK,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_AIR,
  UNIT_CLASS_HERO,
  UNIT_CLASS_MELEE,
  UNIT_CLASS_MILITARY,
  UNIT_CLASS_MYTH,
  UNIT_CLASS_SET_ANIMAL,
  UNIT_CONDITION_FROZEN,
  UNIT_CONDITION_STONE,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_PERSEUS,
  key: "greek-perseus",
  label: "Perseus",
  culture: CULTURE_GREEK,
  classes: UNIT_CLASS_HERO | UNIT_CLASS_MILITARY | UNIT_CLASS_MELEE,
  hero: {
    trainLimit: 1,
    relicCapacity: 1,
    relicPickupRange: 1,
    relicDropOffRange: 1,
  },
  maxHp: 360,
  lineOfSight: 16,
  movementSpeed: 4.3,
  armor: [0.2, 0.4, 0.99],
  attack: {
    kind: "melee",
    damage: [7, 0, 0],
    range: 0.1,
    aggroRange: 16,
    cooldownTicks: 20,
    bonuses: [
      { target: { kind: "classes", classes: UNIT_CLASS_MYTH }, multiplier: 10 },
      { target: { kind: "classes", classes: UNIT_CLASS_SET_ANIMAL }, multiplier: 3 },
    ],
    cycleVariants: [{ actionTicks: 30, impactDelayTicks: 16 }],
  },
  specialAttack: {
    kind: "charged-terminal",
    effect: "petrify-kill",
    damage: [0, 0, 0],
    range: 5,
    bonuses: [],
    rechargeTicks: 24 * 20,
    actionTicks: 60,
    impactDelayTicks: 24,
    validTargets: [
      { kind: "classes", classes: UNIT_CLASS_MYTH, excludedClasses: UNIT_CLASS_AIR },
      { kind: "classes", classes: UNIT_CLASS_SET_ANIMAL, excludedClasses: UNIT_CLASS_AIR },
    ],
    invalidTargetConditions: UNIT_CONDITION_FROZEN | UNIT_CONDITION_STONE,
  },
  isStatic: false,
  resource: -1,
  bodyRadius: 0.7,
  collidesWithProjectiles: true,
  footprint: 0,
  costFood: 0,
  costWood: 0,
  costGold: 400,
  costFavor: 6,
  buildTicks: 27 * 20,
  populationCost: 4,
  popBonus: 0,
  trainExitOffset: 0,
  isDropsite: false,
  requiredAge: AGE_MYTHIC,
  requiredGod: GOD_HADES,
  prerequisiteBuildings: [TYPE_GREEK_TEMPLE],
  trainedAt: [
    { type: TYPE_GREEK_TOWN_CENTER, commandSlot: 4 },
    { type: TYPE_GREEK_FORTRESS, commandSlot: 3 },
  ],
  builtBy: NO_TYPE_RELATIONSHIPS,
} as const satisfies UnitTypeStats;
