import { AGE_HEROIC, NO_GOD } from "../../../ecs/progression";
import { PROJECTILE_PETROBOLOS_STONE } from "../../../ecs/projectiles";
import { TYPE_GREEK_FORTRESS, TYPE_PETROBOLOS } from "../../unit-type-ids";
import {
  CULTURE_GREEK,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_MILITARY,
  UNIT_CLASS_SHIP,
  UNIT_CLASS_SIEGE,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_PETROBOLOS,
  key: "greek-petrobolos",
  label: "Petrobolos",
  culture: CULTURE_GREEK,
  classes: UNIT_CLASS_MILITARY | UNIT_CLASS_SIEGE,
  maxHp: 110,
  lineOfSight: 40,
  movementSpeed: 2.4,
  armor: [0.3, 0.9, 0.9],
  attack: {
    kind: "projectile",
    damage: [0, 5, 11],
    range: 28,
    minimumRange: 10,
    aggroRange: 40,
    cooldownTicks: 4 * 20,
    bonuses: [{ target: { kind: "classes", classes: UNIT_CLASS_SHIP }, multiplier: 2.5 }],
    autoAcquireBuildings: true,
    launchDelayTicks: 2,
    accuracy: 0.9,
    accuracyReductionFactor: 3,
    aimBonus: 15,
    spreadFactor: 0.1,
    maxSpread: 5,
    trackRating: 2,
    unintentionalDamageMultiplier: 0.5,
    projectileCount: 3,
    projectile: {
      type: PROJECTILE_PETROBOLOS_STONE,
      speed: 20,
      lifespanTicks: 2 * 20,
      collisionRadius: 0.1,
    },
  },
  isStatic: false,
  resource: -1,
  bodyRadius: 0.99,
  collidesWithProjectiles: true,
  footprint: 0,
  costFood: 0,
  costWood: 150,
  costGold: 200,
  costFavor: 0,
  buildTicks: 19 * 20,
  populationCost: 3,
  popBonus: 0,
  trainExitOffset: 0,
  isDropsite: false,
  requiredAge: AGE_HEROIC,
  requiredGod: NO_GOD,
  prerequisiteBuildings: [TYPE_GREEK_FORTRESS],
  trainedAt: [{ type: TYPE_GREEK_FORTRESS, commandSlot: 4 }],
  builtBy: NO_TYPE_RELATIONSHIPS,
} as const satisfies UnitTypeStats;
