import { AGE_MYTHIC, GOD_POSEIDON } from "../../../ecs/progression";
import {
  TYPE_GREEK_FORTRESS,
  TYPE_GREEK_TEMPLE,
  TYPE_GREEK_TOWN_CENTER,
  TYPE_POLYPHEMUS,
} from "../../unit-type-ids";
import {
  CULTURE_GREEK,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_HERO,
  UNIT_CLASS_HUMAN,
  UNIT_CLASS_HUNTABLE,
  UNIT_CLASS_MELEE,
  UNIT_CLASS_MILITARY,
  UNIT_CLASS_MYTH,
  UNIT_CLASS_SET_ANIMAL,
  UNIT_CONDITION_FROZEN,
  UNIT_CONDITION_STONE,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_POLYPHEMUS,
  key: "greek-polyphemus",
  label: "Polyphemus",
  culture: CULTURE_GREEK,
  classes: UNIT_CLASS_HERO | UNIT_CLASS_MILITARY | UNIT_CLASS_MELEE,
  hero: {
    trainLimit: 1,
    relicCapacity: 1,
    relicPickupRange: 1,
    relicDropOffRange: 1,
  },
  maxHp: 540,
  lineOfSight: 20,
  movementSpeed: 3.5,
  armor: [0.4, 0.4, 0.99],
  attack: {
    kind: "melee",
    damage: [15, 0, 5],
    range: 0.1,
    aggroRange: 20,
    cooldownTicks: 20,
    bonuses: [
      { target: { kind: "classes", classes: UNIT_CLASS_MYTH }, multiplier: 5 },
      { target: { kind: "classes", classes: UNIT_CLASS_SET_ANIMAL }, multiplier: 3 },
    ],
    cycleVariants: [
      { actionTicks: 30, impactDelayTicks: 15 },
      { actionTicks: 40, impactDelayTicks: 25 },
    ],
  },
  specialAttack: {
    kind: "charged-melee",
    damage: [90, 0, 0],
    range: 0.1,
    bonuses: [{ target: { kind: "classes", classes: UNIT_CLASS_MYTH }, multiplier: 7 }],
    rechargeTicks: 18 * 20,
    actionTicks: 30,
    impactDelayTicks: 16,
    validTargets: [
      { kind: "classes", classes: UNIT_CLASS_HUMAN },
      { kind: "classes", classes: UNIT_CLASS_MYTH },
      { kind: "classes", classes: UNIT_CLASS_HUNTABLE },
    ],
    invalidTargetConditions: UNIT_CONDITION_FROZEN | UNIT_CONDITION_STONE,
    targetReaction: {
      kind: "thrown",
      randomDrawOrder: ["distance", "maxVelocity", "maxHeight", "bounces"],
      distanceBase: 8,
      distanceRandomRange: 2,
      maxVelocityBase: 12,
      maxVelocityRandomRange: 4,
      maxHeightBase: 6,
      maxHeightRandomRange: 2,
      bounceBase: 1,
      bounceRandomRange: 2,
    },
  },
  isStatic: false,
  resource: -1,
  bodyRadius: 0.99,
  collidesWithProjectiles: true,
  footprint: 0,
  costFood: 0,
  costWood: 0,
  costGold: 400,
  costFavor: 6,
  buildTicks: 27 * 20,
  populationCost: 4,
  popBonus: 0,
  trainExitOffset: 0,
  isDropsite: false,
  requiredAge: AGE_MYTHIC,
  requiredGod: GOD_POSEIDON,
  prerequisiteBuildings: [TYPE_GREEK_TEMPLE],
  trainedAt: [
    { type: TYPE_GREEK_TOWN_CENTER, commandSlot: 4 },
    { type: TYPE_GREEK_FORTRESS, commandSlot: 3 },
  ],
  builtBy: NO_TYPE_RELATIONSHIPS,
} as const satisfies UnitTypeStats;
