import { TICK_HZ } from "../../../clock";
import { AGE_HEROIC, GOD_DIONYSUS } from "../../../ecs/progression";
import { TYPE_GREEK_DOCK, TYPE_SCYLLA } from "../../unit-type-ids";
import {
  CULTURE_GREEK,
  MOVEMENT_DOMAIN_WATER,
  NO_PREREQUISITE_BUILDINGS,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_MELEE,
  UNIT_CLASS_MILITARY,
  UNIT_CLASS_MYTH,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_SCYLLA,
  key: "greek-scylla",
  label: "Scylla",
  culture: CULTURE_GREEK,
  classes: UNIT_CLASS_MYTH | UNIT_CLASS_MILITARY | UNIT_CLASS_MELEE,
  maxHp: 800,
  lineOfSight: 16,
  movementSpeed: 5.3,
  movementDomain: MOVEMENT_DOMAIN_WATER,
  armor: [0.4, 0.7, 0.99],
  attack: {
    kind: "melee",
    damage: [20, 0, 10],
    range: 0.1,
    aggroRange: 16,
    cooldownTicks: TICK_HZ,
    bonuses: [{ target: { kind: "classes", classes: UNIT_CLASS_MYTH }, multiplier: 2 }],
    cycleVariants: [
      { actionTicks: 30, impactDelayTicks: 12 },
      { actionTicks: 30, impactDelayTicks: 12 },
      { actionTicks: 30, impactDelayTicks: 12 },
      { actionTicks: 30, impactDelayTicks: 12 },
      { actionTicks: 30, impactDelayTicks: 12 },
    ],
    killScaling: {
      damageMultiplierPerKill: 1 / 6,
      maxKills: 12,
      killsPerVariant: 3,
    },
  },
  isStatic: false,
  resource: -1,
  bodyRadius: 0.99,
  collidesWithProjectiles: true,
  footprint: 0,
  costFood: 0,
  costWood: 0,
  costGold: 200,
  costFavor: 15,
  buildTicks: 100,
  populationCost: 5,
  popBonus: 0,
  trainExitOffset: 0,
  isDropsite: false,
  requiredAge: AGE_HEROIC,
  requiredGod: GOD_DIONYSUS,
  prerequisiteBuildings: NO_PREREQUISITE_BUILDINGS,
  trainedAt: [{ type: TYPE_GREEK_DOCK, commandSlot: 5 }],
  builtBy: NO_TYPE_RELATIONSHIPS,
} as const satisfies UnitTypeStats;
