import { TICK_HZ } from "../../../clock";
import { AGE_ARCHAIC, NO_GOD } from "../../../ecs/progression";
import { buildingArrowAttack } from "../../building-attacks";
import { TYPE_GREEK_TOWN_CENTER, TYPE_GREEK_VILLAGER, TYPE_SETTLEMENT } from "../../unit-type-ids";
import {
  CULTURE_GREEK,
  NO_PREREQUISITE_BUILDINGS,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_BUILDING,
  UNIT_CLASS_HUMAN,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_GREEK_TOWN_CENTER,
  key: "greek-town-center",
  label: "Town Center",
  culture: CULTURE_GREEK,
  classes: UNIT_CLASS_BUILDING,
  maxHp: 2400,
  lineOfSight: 24,
  movementSpeed: 0,
  armor: [0.55, 0.96, 0.1],
  attack: buildingArrowAttack({ damage: 12, range: 20, projectileCount: 2, trackRating: 10 }),
  garrison: {
    capacity: 25,
    enterRange: 10,
    validOccupants: [{ kind: "classes", classes: UNIT_CLASS_HUMAN }],
    attackMultiplierPerOccupant: 0.05,
    ejectOnDeath: true,
  },
  tradeSite: "town-center",
  isStatic: true,
  resource: -1,
  bodyRadius: 5,
  collidesWithProjectiles: true,
  footprint: 5,
  placementReplacementType: TYPE_SETTLEMENT,
  destructionReplacementType: TYPE_SETTLEMENT,
  costFood: 0,
  costWood: 300,
  costGold: 300,
  costFavor: 0,
  buildTicks: 90 * TICK_HZ,
  buildLimitByAge: [1, 1, 10, 10],
  populationCost: 0,
  popBonus: 15,
  trainExitOffset: 6.5,
  isDropsite: true,
  requiredAge: AGE_ARCHAIC,
  requiredGod: NO_GOD,
  prerequisiteBuildings: NO_PREREQUISITE_BUILDINGS,
  trainedAt: NO_TYPE_RELATIONSHIPS,
  builtBy: [{ type: TYPE_GREEK_VILLAGER, commandSlot: 3 }],
} as const satisfies UnitTypeStats;
