import { AGE_CLASSICAL, NO_GOD } from "../../../ecs/progression";
import { PROJECTILE_ARROW } from "../../../ecs/projectiles";
import { TYPE_GREEK_ARCHERY_RANGE, TYPE_TOXOTES } from "../../unit-type-ids";
import {
  CULTURE_GREEK,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_ARCHER,
  UNIT_CLASS_HUMAN,
  UNIT_CLASS_MILITARY,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_TOXOTES,
  key: "greek-toxotes",
  label: "Toxotes",
  culture: CULTURE_GREEK,
  classes: UNIT_CLASS_HUMAN | UNIT_CLASS_MILITARY | UNIT_CLASS_ARCHER,
  maxHp: 60,
  lineOfSight: 19,
  movementSpeed: 4,
  armor: [0.15, 0.15, 0.99],
  attack: {
    kind: "projectile",
    damage: [0, 6.5, 0],
    range: 15,
    aggroRange: 19,
    cooldownTicks: 20,
    bonuses: [{ target: { kind: "unit", key: "norse-raiding-cavalry" }, multiplier: 0.9 }],
    launchDelayTicks: 8,
    accuracy: 0.8,
    accuracyReductionFactor: 1.5,
    aimBonus: 15,
    spreadFactor: 0.25,
    maxSpread: 5,
    trackRating: 5,
    unintentionalDamageMultiplier: 0.3,
    projectile: {
      type: PROJECTILE_ARROW,
      speed: 30,
      lifespanTicks: 2 * 20,
      collisionRadius: 0.1,
    },
  },
  isStatic: false,
  resource: -1,
  bodyRadius: 0.49,
  collidesWithProjectiles: true,
  footprint: 0,
  costFood: 0,
  costWood: 55,
  costGold: 35,
  costFavor: 0,
  buildTicks: 15 * 20,
  populationCost: 2,
  popBonus: 0,
  trainExitOffset: 0,
  isDropsite: false,
  requiredAge: AGE_CLASSICAL,
  requiredGod: NO_GOD,
  prerequisiteBuildings: [TYPE_GREEK_ARCHERY_RANGE],
  trainedAt: [{ type: TYPE_GREEK_ARCHERY_RANGE, commandSlot: 0 }],
  builtBy: NO_TYPE_RELATIONSHIPS,
} as const satisfies UnitTypeStats;
