import { AGE_ARCHAIC, NO_GOD } from "../../../ecs/progression";
import { TYPE_GREEK_TOWN_CENTER, TYPE_GREEK_VILLAGER } from "../../unit-type-ids";
import {
  CULTURE_GREEK,
  NO_DAMAGE_BONUSES,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_HUMAN,
  UNIT_CLASS_MELEE,
  UNIT_CLASS_WORKER,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_GREEK_VILLAGER,
  key: "greek-villager",
  label: "Villager",
  culture: CULTURE_GREEK,
  classes: UNIT_CLASS_WORKER | UNIT_CLASS_HUMAN | UNIT_CLASS_MELEE,
  maxHp: 65,
  lineOfSight: 14,
  movementSpeed: 3.8,
  workRange: 1.2,
  armor: [0.25, 0.35, 0.99],
  attack: {
    kind: "melee",
    damage: [8, 0, 0],
    range: 0.1,
    aggroRange: 14,
    cooldownTicks: 20,
    bonuses: NO_DAMAGE_BONUSES,
  },
  isStatic: false,
  resource: -1,
  bodyRadius: 0.49,
  footprint: 0,
  costFood: 50,
  costWood: 0,
  costGold: 0,
  costFavor: 0,
  buildTicks: 100,
  populationCost: 1,
  popBonus: 0,
  trainExitOffset: 0,
  isDropsite: false,
  requiredAge: AGE_ARCHAIC,
  requiredGod: NO_GOD,
  prerequisiteBuildings: [TYPE_GREEK_TOWN_CENTER],
  trainedAt: [{ type: TYPE_GREEK_TOWN_CENTER, commandSlot: 0 }],
  builtBy: NO_TYPE_RELATIONSHIPS,
} as const satisfies UnitTypeStats;
