import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  UNIT_ROSTER,
  gateLabel,
  type UnitRosterEntry,
} from "../packages/sim/src/content/unit-roster";
import {
  TYPE_EGYPTIAN_DOCK,
  TYPE_EGYPTIAN_BARRACKS,
  TYPE_EGYPTIAN_MARKET,
  TYPE_EGYPTIAN_MIGDOL_STRONGHOLD,
  TYPE_EGYPTIAN_SIEGE_WORKS,
  TYPE_EGYPTIAN_TEMPLE,
  TYPE_EGYPTIAN_TOWN_CENTER,
  TYPE_GREEK_ARCHERY_RANGE,
  TYPE_GREEK_DOCK,
  TYPE_GREEK_FORTRESS,
  TYPE_GREEK_MARKET,
  TYPE_GREEK_MILITARY_ACADEMY,
  TYPE_GREEK_STABLE,
  TYPE_GREEK_TEMPLE,
  TYPE_GREEK_TOWN_CENTER,
} from "../packages/sim/src/content/unit-type-ids";
import { CULTURE_EGYPTIAN, CULTURE_GREEK } from "../packages/sim/src/content/unit-type-schema";

const outputPath = resolve(import.meta.dir, "../docs/UNIT_ROSTER_MANIFEST.md");
const checkOnly = process.argv.includes("--check");

const GOD_NAMES = [
  "Zeus",
  "Poseidon",
  "Hades",
  "Athena",
  "Hermes",
  "Ra",
  "Bast",
  "Ptah",
  "Ares",
  "Apollo",
  "Dionysus",
  "Aphrodite",
  "Artemis",
  "Hephaestus",
  "Hera",
  "Isis",
  "Set",
  "Anubis",
  "Thoth",
  "Sekhmet",
  "Hathor",
  "Nephthys",
  "Osiris",
  "Horus",
] as const;

const PRODUCER_NAMES: Readonly<Record<number, string>> = {
  [TYPE_GREEK_TOWN_CENTER]: "Greek Town Center",
  [TYPE_EGYPTIAN_TOWN_CENTER]: "Egyptian Town Center",
  [TYPE_EGYPTIAN_BARRACKS]: "Egyptian Barracks",
  [TYPE_GREEK_MILITARY_ACADEMY]: "Military Academy",
  [TYPE_GREEK_ARCHERY_RANGE]: "Archery Range",
  [TYPE_GREEK_STABLE]: "Stable",
  [TYPE_GREEK_FORTRESS]: "Fortress",
  [TYPE_GREEK_DOCK]: "Greek Dock",
  [TYPE_GREEK_MARKET]: "Greek Market",
  [TYPE_EGYPTIAN_TEMPLE]: "Egyptian Temple",
  [TYPE_EGYPTIAN_MIGDOL_STRONGHOLD]: "Migdol Stronghold",
  [TYPE_EGYPTIAN_SIEGE_WORKS]: "Siege Works",
  [TYPE_EGYPTIAN_DOCK]: "Egyptian Dock",
  [TYPE_EGYPTIAN_MARKET]: "Egyptian Market",
  [TYPE_GREEK_TEMPLE]: "Greek Temple",
};

const FAMILY_ORDER = [
  "ordinary-melee",
  "ordinary-projectile",
  "hero",
  "myth",
  "siege",
  "trade",
  "naval",
  "exceptional-lifecycle",
] as const;

function cultureName(culture: number): string {
  if (culture === CULTURE_GREEK) return "Greek";
  if (culture === CULTURE_EGYPTIAN) return "Egyptian";
  return `culture ${culture}`;
}

function requiredGodName(requiredGod: number): string {
  return requiredGod === 255 ? "Any" : (GOD_NAMES[requiredGod] ?? `god ${requiredGod}`);
}

function assignmentText(lane: UnitRosterEntry): string {
  if (lane.trainedAt === null) return "not frozen";
  if (lane.trainedAt.length === 0) return "not normally trainable";
  return lane.trainedAt
    .map(
      ({ type, commandSlot }) =>
        `${PRODUCER_NAMES[type] ?? `producer ${type}`} slot ${commandSlot}`,
    )
    .join("; ");
}

function wrappedLine(prefix: string, value: string, width = 100): readonly string[] {
  const words = value.split(/\s+/);
  const continuation = "    ";
  const lines: string[] = [];
  let line = prefix;
  let hasWord = false;
  for (const word of words) {
    if (hasWord && line.length + word.length + 1 > width) {
      lines.push(line);
      line = continuation + word;
      hasWord = true;
    } else {
      line += `${hasWord ? " " : ""}${word}`;
      hasWord = true;
    }
  }
  lines.push(line);
  return lines;
}

function laneLines(lane: UnitRosterEntry): readonly string[] {
  const lines = [
    `- \`${lane.lane}\` — id \`${lane.id}\`; ${cultureName(lane.culture)}; ${gateLabel(lane.gates)}; ${lane.status}.`,
    ...wrappedLine("  - Assignment: ", assignmentText(lane)),
    `  - Required god: ${requiredGodName(lane.requiredGod)}.`,
    ...wrappedLine("  - Foundation owners: ", lane.foundationLanes.join("; ")),
  ];
  if (lane.blocker !== null) lines.push(...wrappedLine("  - Blocker: ", lane.blocker));
  return lines;
}

function renderManifest(): string {
  const implemented = UNIT_ROSTER.filter((lane) => lane.status === "implemented").length;
  const ready = UNIT_ROSTER.filter((lane) => lane.status === "ready").length;
  const blocked = UNIT_ROSTER.length - implemented - ready;
  const lines = [
    "# Greek and Egyptian unit roster manifest",
    "",
    "This file is generated by `bun run generate:unit-roster-manifest`. The sole machine-readable",
    "source of truth is `packages/sim/src/content/unit-roster.ts`; edit the roster modules, not this",
    "document.",
    "",
    "Blocked assignments are dependency-planning inputs from the local Classic source audit. A lane",
    "is not launchable until its family audit freezes a complete candidate reference and marks it",
    "`ready`.",
    "",
    "## Summary",
    "",
    `- Total reserved unit workcells: **${UNIT_ROSTER.length}**`,
    `- Implemented: **${implemented}**`,
    `- Ready for fan-out: **${ready}**`,
    `- Blocked on shared foundations: **${blocked}**`,
    "",
  ];

  for (const family of FAMILY_ORDER) {
    const lanes = UNIT_ROSTER.filter((lane) => lane.family === family);
    if (lanes.length === 0) continue;
    lines.push(`## ${family} (${lanes.length})`, "");
    for (const lane of lanes) lines.push(...laneLines(lane), "");
  }

  return lines.join("\n").trimEnd() + "\n";
}

const generated = renderManifest();
if (checkOnly) {
  const current = readFileSync(outputPath, "utf8");
  if (current !== generated) {
    console.error("docs/UNIT_ROSTER_MANIFEST.md is stale; regenerate the roster manifest.");
    process.exit(1);
  }
} else {
  writeFileSync(outputPath, generated);
}
