import { AGE_CLASSICAL, GOD_ANUBIS } from "../../../ecs/progression";
import { TYPE_ANUBITE, TYPE_EGYPTIAN_TEMPLE } from "../../unit-type-ids";
import {
  AREA_DAMAGE_ENEMIES,
  CULTURE_EGYPTIAN,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_HERO,
  UNIT_CLASS_HUMAN,
  UNIT_CLASS_INFANTRY,
  UNIT_CLASS_MELEE,
  UNIT_CLASS_MILITARY,
  UNIT_CLASS_MYTH,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_ANUBITE,
  key: "egyptian-anubite",
  label: "Anubite",
  culture: CULTURE_EGYPTIAN,
  classes: UNIT_CLASS_MYTH | UNIT_CLASS_INFANTRY | UNIT_CLASS_MILITARY | UNIT_CLASS_MELEE,
  maxHp: 200,
  lineOfSight: 16,
  movementSpeed: 5.3,
  armor: [0.6, 0.55, 0.8],
  attack: {
    kind: "melee",
    damage: [13, 0, 0],
    range: 0.1,
    aggroRange: 16,
    cooldownTicks: 20,
    bonuses: [
      { target: { kind: "classes", classes: UNIT_CLASS_MYTH }, multiplier: 3 },
      { target: { kind: "classes", classes: UNIT_CLASS_HERO }, multiplier: 0.5 },
    ],
    cycleVariants: [
      { actionTicks: 15, impactDelayTicks: 7 },
      { actionTicks: 19, impactDelayTicks: 9 },
    ],
  },
  specialAttack: {
    kind: "charged-jump",
    delivery: "area",
    damage: [15, 0, 0],
    minimumRange: 4,
    range: 8,
    bonuses: [
      { target: { kind: "classes", classes: UNIT_CLASS_MYTH }, multiplier: 3 },
      { target: { kind: "classes", classes: UNIT_CLASS_HERO }, multiplier: 0.1 },
    ],
    rechargeTicks: 5 * 20,
    takeoffTicks: 13,
    flightTicks: 40,
    landingTicks: 20,
    actionTicks: 73,
    impactDelayTicks: 53,
    jumpHeight: 4,
    radius: 3,
    falloff: "constant",
    damageRelations: AREA_DAMAGE_ENEMIES,
    validTargets: [
      { kind: "classes", classes: UNIT_CLASS_HUMAN },
      { kind: "classes", classes: UNIT_CLASS_MYTH },
    ],
  },
  isStatic: false,
  resource: -1,
  bodyRadius: 0.49,
  collidesWithProjectiles: true,
  footprint: 0,
  costFood: 100,
  costWood: 0,
  costGold: 0,
  costFavor: 15,
  buildTicks: 9 * 20,
  populationCost: 3,
  popBonus: 0,
  trainExitOffset: 0,
  isDropsite: false,
  requiredAge: AGE_CLASSICAL,
  requiredGod: GOD_ANUBIS,
  prerequisiteBuildings: [TYPE_EGYPTIAN_TEMPLE],
  trainedAt: [{ type: TYPE_EGYPTIAN_TEMPLE, commandSlot: 1 }],
  builtBy: NO_TYPE_RELATIONSHIPS,
} as const satisfies UnitTypeStats;
