import { AGE_CLASSICAL, NO_GOD } from "../../../ecs/progression";
import { TYPE_AXEMAN, TYPE_EGYPTIAN_BARRACKS } from "../../unit-type-ids";
import {
  CULTURE_EGYPTIAN,
  CULTURE_NORSE,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_HERO,
  UNIT_CLASS_HUMAN,
  UNIT_CLASS_INFANTRY,
  UNIT_CLASS_MELEE,
  UNIT_CLASS_MILITARY,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_AXEMAN,
  key: "egyptian-axeman",
  label: "Axeman",
  culture: CULTURE_EGYPTIAN,
  classes: UNIT_CLASS_HUMAN | UNIT_CLASS_INFANTRY | UNIT_CLASS_MILITARY | UNIT_CLASS_MELEE,
  maxHp: 70,
  lineOfSight: 16,
  movementSpeed: 4.3,
  armor: [0.4, 0.05, 0.99],
  attack: {
    kind: "melee",
    damage: [5, 0, 0],
    range: 0.3,
    aggroRange: 16,
    cooldownTicks: 30,
    bonuses: [
      { requiredClasses: UNIT_CLASS_INFANTRY, multiplier: 4 },
      { requiredClasses: UNIT_CLASS_HERO, requiredCulture: CULTURE_NORSE, multiplier: 4 },
    ],
  },
  isStatic: false,
  resource: -1,
  bodyRadius: 0.49,
  collidesWithProjectiles: true,
  footprint: 0,
  costFood: 40,
  costWood: 0,
  costGold: 30,
  costFavor: 0,
  buildTicks: 10 * 20,
  populationCost: 2,
  popBonus: 0,
  trainExitOffset: 0,
  isDropsite: false,
  requiredAge: AGE_CLASSICAL,
  requiredGod: NO_GOD,
  prerequisiteBuildings: [TYPE_EGYPTIAN_BARRACKS],
  trainedAt: [{ type: TYPE_EGYPTIAN_BARRACKS, commandSlot: 1 }],
  builtBy: NO_TYPE_RELATIONSHIPS,
} as const satisfies UnitTypeStats;
