import { AGE_MYTHIC, NO_GOD } from "../../../ecs/progression";
import { PROJECTILE_CATAPULT_STONE } from "../../../ecs/projectiles";
import { TYPE_CATAPULT, TYPE_EGYPTIAN_SIEGE_WORKS } from "../../unit-type-ids";
import {
  CULTURE_EGYPTIAN,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_MILITARY,
  UNIT_CLASS_SHIP,
  UNIT_CLASS_SIEGE,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_CATAPULT,
  key: "egyptian-catapult",
  label: "Catapult",
  culture: CULTURE_EGYPTIAN,
  classes: UNIT_CLASS_MILITARY | UNIT_CLASS_SIEGE,
  maxHp: 115,
  lineOfSight: 40,
  movementSpeed: 2.4,
  armor: [0.3, 0.9, 0.9],
  attack: {
    kind: "projectile",
    damage: [0, 10, 50],
    range: 28,
    minimumRange: 10,
    aggroRange: 40,
    cooldownTicks: 4 * 20,
    bonuses: [{ target: { kind: "classes", classes: UNIT_CLASS_SHIP }, multiplier: 2.5 }],
    autoAcquireBuildings: true,
    launchDelayTicks: 6,
    accuracy: 0.9,
    accuracyReductionFactor: 3,
    aimBonus: 15,
    spreadFactor: 0.1,
    maxSpread: 5,
    trackRating: 2,
    unintentionalDamageMultiplier: 0.5,
    projectile: {
      type: PROJECTILE_CATAPULT_STONE,
      speed: 20,
      lifespanTicks: 2 * 20,
      collisionRadius: 0.1,
    },
  },
  isStatic: false,
  resource: -1,
  bodyRadius: 0.99,
  collidesWithProjectiles: true,
  footprint: 0,
  costFood: 0,
  costWood: 200,
  costGold: 200,
  costFavor: 0,
  buildTicks: 24 * 20,
  populationCost: 3,
  popBonus: 0,
  trainExitOffset: 0,
  isDropsite: false,
  requiredAge: AGE_MYTHIC,
  requiredGod: NO_GOD,
  prerequisiteBuildings: [TYPE_EGYPTIAN_SIEGE_WORKS],
  trainedAt: [{ type: TYPE_EGYPTIAN_SIEGE_WORKS, commandSlot: 1 }],
  builtBy: NO_TYPE_RELATIONSHIPS,
} as const satisfies UnitTypeStats;
