import { AGE_HEROIC, NO_GOD } from "../../../ecs/progression";
import { PROJECTILE_ARROW } from "../../../ecs/projectiles";
import { TYPE_CHARIOT_ARCHER, TYPE_EGYPTIAN_MIGDOL_STRONGHOLD } from "../../unit-type-ids";
import {
  CULTURE_EGYPTIAN,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_ARCHER,
  UNIT_CLASS_HUMAN,
  UNIT_CLASS_MILITARY,
  UNIT_CLASS_NON_GREEK_UNIT,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_CHARIOT_ARCHER,
  key: "egyptian-chariot-archer",
  label: "Chariot Archer",
  culture: CULTURE_EGYPTIAN,
  classes: UNIT_CLASS_HUMAN | UNIT_CLASS_MILITARY | UNIT_CLASS_ARCHER | UNIT_CLASS_NON_GREEK_UNIT,
  maxHp: 90,
  lineOfSight: 24,
  movementSpeed: 5.3,
  armor: [0.3, 0.2, 0.99],
  attack: {
    kind: "projectile",
    damage: [0, 8.5, 0],
    range: 20,
    aggroRange: 24,
    cooldownTicks: 30,
    bonuses: [],
    launchDelayTicks: 19,
    accuracy: 0.8,
    accuracyReductionFactor: 1.5,
    aimBonus: 15,
    spreadFactor: 0.25,
    maxSpread: 5,
    trackRating: 5,
    unintentionalDamageMultiplier: 0.3,
    projectile: {
      type: PROJECTILE_ARROW,
      speed: 30,
      lifespanTicks: 2 * 20,
      collisionRadius: 0.1,
    },
  },
  isStatic: false,
  resource: -1,
  bodyRadius: 0.7,
  collidesWithProjectiles: true,
  footprint: 0,
  costFood: 0,
  costWood: 100,
  costGold: 40,
  costFavor: 0,
  buildTicks: 6 * 20,
  populationCost: 3,
  popBonus: 0,
  trainExitOffset: 0,
  isDropsite: false,
  requiredAge: AGE_HEROIC,
  requiredGod: NO_GOD,
  prerequisiteBuildings: [TYPE_EGYPTIAN_MIGDOL_STRONGHOLD],
  trainedAt: [{ type: TYPE_EGYPTIAN_MIGDOL_STRONGHOLD, commandSlot: 0 }],
  builtBy: NO_TYPE_RELATIONSHIPS,
} as const satisfies UnitTypeStats;
