import { AGE_ARCHAIC, NO_GOD } from "../../../ecs/progression";
import { TYPE_EGYPTIAN_DOCK, TYPE_EGYPTIAN_FISHING_SHIP } from "../../unit-type-ids";
import {
  CULTURE_EGYPTIAN,
  MOVEMENT_DOMAIN_WATER,
  NO_PREREQUISITE_BUILDINGS,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_SHIP,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_EGYPTIAN_FISHING_SHIP,
  key: "egyptian-fishing-ship",
  label: "Fishing Ship",
  culture: CULTURE_EGYPTIAN,
  classes: UNIT_CLASS_SHIP,
  maxHp: 120,
  lineOfSight: 20,
  movementSpeed: 4.8,
  movementDomain: MOVEMENT_DOMAIN_WATER,
  workRange: 1,
  gather: { capacity: 25, ratePerSecond: 0.54 },
  construction: { range: 4, ratePerSecond: 0.28, baselineRatePerSecond: 0.99 },
  armor: [0.6, 0.5, 0.05],
  attack: null,
  isStatic: false,
  resource: -1,
  bodyRadius: 0.99,
  collidesWithProjectiles: true,
  footprint: 0,
  costFood: 0,
  costWood: 50,
  costGold: 0,
  costFavor: 0,
  buildTicks: 14 * 20,
  populationCost: 1,
  popBonus: 0,
  trainExitOffset: 0,
  isDropsite: false,
  requiredAge: AGE_ARCHAIC,
  requiredGod: NO_GOD,
  prerequisiteBuildings: NO_PREREQUISITE_BUILDINGS,
  trainedAt: [{ type: TYPE_EGYPTIAN_DOCK, commandSlot: 0 }],
  builtBy: NO_TYPE_RELATIONSHIPS,
} as const satisfies UnitTypeStats;
