import { AGE_ARCHAIC, NO_GOD } from "../../../ecs/progression";
import { TYPE_EGYPTIAN_HOUSE, TYPE_EGYPTIAN_LABORER } from "../../unit-type-ids";
import {
  CULTURE_EGYPTIAN,
  NO_PREREQUISITE_BUILDINGS,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_BUILDING,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_EGYPTIAN_HOUSE,
  key: "egyptian-house",
  label: "House",
  culture: CULTURE_EGYPTIAN,
  classes: UNIT_CLASS_BUILDING,
  maxHp: 450,
  lineOfSight: 9,
  movementSpeed: 0,
  armor: [0.3, 0.96, 0.05],
  attack: null,
  isStatic: true,
  resource: -1,
  bodyRadius: 2,
  collidesWithProjectiles: true,
  footprint: 2,
  costFood: 0,
  costWood: 0,
  costGold: 0,
  costFavor: 0,
  buildTicks: 15 * 20,
  buildLimit: 10,
  populationCost: 0,
  popBonus: 10,
  trainExitOffset: 0,
  isDropsite: false,
  requiredAge: AGE_ARCHAIC,
  requiredGod: NO_GOD,
  prerequisiteBuildings: NO_PREREQUISITE_BUILDINGS,
  trainedAt: NO_TYPE_RELATIONSHIPS,
  builtBy: [{ type: TYPE_EGYPTIAN_LABORER, commandSlot: 0 }],
} as const satisfies UnitTypeStats;
