import { AGE_CLASSICAL, NO_GOD } from "../../../ecs/progression";
import { PROJECTILE_ARROW } from "../../../ecs/projectiles";
import { TYPE_EGYPTIAN_DOCK, TYPE_KEBENIT } from "../../unit-type-ids";
import {
  CULTURE_EGYPTIAN,
  MOVEMENT_DOMAIN_WATER,
  NO_PREREQUISITE_BUILDINGS,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_MILITARY,
  UNIT_CLASS_SHIP,
  UNIT_CLASS_TRANSPORT_SHIP,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_KEBENIT,
  key: "egyptian-kebenit",
  label: "Kebenit",
  culture: CULTURE_EGYPTIAN,
  classes: UNIT_CLASS_MILITARY | UNIT_CLASS_SHIP,
  maxHp: 290,
  lineOfSight: 24,
  movementSpeed: 6,
  movementDomain: MOVEMENT_DOMAIN_WATER,
  armor: [0.3, 0.2, 0.1],
  attack: {
    kind: "projectile",
    damage: [0, 6, 0],
    range: 12,
    aggroRange: 24,
    cooldownTicks: 30,
    bonuses: [{ target: { kind: "classes", classes: UNIT_CLASS_TRANSPORT_SHIP }, multiplier: 3 }],
    launchDelayTicks: 12,
    accuracy: 0.8,
    accuracyReductionFactor: 2,
    aimBonus: 15,
    spreadFactor: 0.25,
    maxSpread: 5,
    trackRating: 10,
    unintentionalDamageMultiplier: 0.3,
    projectileCount: 3,
    projectile: { type: PROJECTILE_ARROW, speed: 30, lifespanTicks: 40, collisionRadius: 0.1 },
  },
  isStatic: false,
  resource: -1,
  bodyRadius: 0.99,
  collidesWithProjectiles: true,
  footprint: 0,
  costFood: 0,
  costWood: 100,
  costGold: 50,
  costFavor: 0,
  buildTicks: 280,
  populationCost: 2,
  popBonus: 0,
  trainExitOffset: 0,
  isDropsite: false,
  requiredAge: AGE_CLASSICAL,
  requiredGod: NO_GOD,
  prerequisiteBuildings: NO_PREREQUISITE_BUILDINGS,
  trainedAt: [{ type: TYPE_EGYPTIAN_DOCK, commandSlot: 2 }],
  builtBy: NO_TYPE_RELATIONSHIPS,
} as const satisfies UnitTypeStats;
