import { AGE_ARCHAIC, NO_GOD } from "../../../ecs/progression";
import {
  TYPE_EGYPTIAN_ARMORY,
  TYPE_EGYPTIAN_DOCK,
  TYPE_EGYPTIAN_FARM,
  TYPE_EGYPTIAN_GATE,
  TYPE_EGYPTIAN_GRANARY,
  TYPE_EGYPTIAN_HOUSE,
  TYPE_EGYPTIAN_LABORER,
  TYPE_EGYPTIAN_LIGHTHOUSE,
  TYPE_EGYPTIAN_LUMBER_CAMP,
  TYPE_EGYPTIAN_MARKET,
  TYPE_EGYPTIAN_MIGDOL_STRONGHOLD,
  TYPE_EGYPTIAN_MINING_CAMP,
  TYPE_EGYPTIAN_MONUMENT_TO_GODS,
  TYPE_EGYPTIAN_MONUMENT_TO_PHARAOHS,
  TYPE_EGYPTIAN_MONUMENT_TO_PRIESTS,
  TYPE_EGYPTIAN_MONUMENT_TO_SOLDIERS,
  TYPE_EGYPTIAN_MONUMENT_TO_VILLAGERS,
  TYPE_EGYPTIAN_SIEGE_WORKS,
  TYPE_EGYPTIAN_TOWER,
  TYPE_EGYPTIAN_TOWN_CENTER,
  TYPE_EGYPTIAN_WALL_CONNECTOR,
  TYPE_EGYPTIAN_WALL_LONG,
  TYPE_EGYPTIAN_WALL_MEDIUM,
  TYPE_EGYPTIAN_WALL_SHORT,
} from "../../unit-type-ids";
import {
  CULTURE_EGYPTIAN,
  NO_DAMAGE_BONUSES,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_HUMAN,
  UNIT_CLASS_MELEE,
  UNIT_CLASS_WORKER,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_EGYPTIAN_LABORER,
  key: "egyptian-laborer",
  label: "Laborer",
  culture: CULTURE_EGYPTIAN,
  classes: UNIT_CLASS_WORKER | UNIT_CLASS_HUMAN | UNIT_CLASS_MELEE,
  maxHp: 65,
  lineOfSight: 14,
  movementSpeed: 3.8,
  workRange: 1.2,
  armor: [0.25, 0.35, 0.99],
  attack: {
    kind: "melee",
    damage: [8, 0, 0],
    range: 0.1,
    aggroRange: 14,
    cooldownTicks: 20,
    bonuses: NO_DAMAGE_BONUSES,
  },
  construction: {
    range: 1.2,
    ratePerSecond: 0.83,
    baselineRatePerSecond: 1,
    targetRates: [
      { type: TYPE_EGYPTIAN_HOUSE, ratePerSecond: 0.55 },
      { type: TYPE_EGYPTIAN_LUMBER_CAMP, ratePerSecond: 0.55 },
      { type: TYPE_EGYPTIAN_GRANARY, ratePerSecond: 0.66 },
      { type: TYPE_EGYPTIAN_MINING_CAMP, ratePerSecond: 0.55 },
      { type: TYPE_EGYPTIAN_MIGDOL_STRONGHOLD, ratePerSecond: 0.61 },
      { type: TYPE_EGYPTIAN_ARMORY, ratePerSecond: 0.44 },
      { type: TYPE_EGYPTIAN_MARKET, ratePerSecond: 0.55 },
      { type: TYPE_EGYPTIAN_DOCK, ratePerSecond: 0.99 },
      { type: TYPE_EGYPTIAN_TOWER, ratePerSecond: 0.55 },
      { type: TYPE_EGYPTIAN_SIEGE_WORKS, ratePerSecond: 0.55 },
      { type: TYPE_EGYPTIAN_FARM, ratePerSecond: 1.1 },
      { type: TYPE_EGYPTIAN_WALL_CONNECTOR, ratePerSecond: 1.1 },
      { type: TYPE_EGYPTIAN_WALL_SHORT, ratePerSecond: 1.1 },
      { type: TYPE_EGYPTIAN_WALL_MEDIUM, ratePerSecond: 1.1 },
      { type: TYPE_EGYPTIAN_WALL_LONG, ratePerSecond: 1.1 },
      { type: TYPE_EGYPTIAN_GATE, ratePerSecond: 1.1 },
      { type: TYPE_EGYPTIAN_MONUMENT_TO_VILLAGERS, ratePerSecond: 0.55 },
      { type: TYPE_EGYPTIAN_MONUMENT_TO_SOLDIERS, ratePerSecond: 0.55 },
      { type: TYPE_EGYPTIAN_MONUMENT_TO_PRIESTS, ratePerSecond: 0.55 },
      { type: TYPE_EGYPTIAN_MONUMENT_TO_PHARAOHS, ratePerSecond: 0.55 },
      { type: TYPE_EGYPTIAN_MONUMENT_TO_GODS, ratePerSecond: 0.55 },
      { type: TYPE_EGYPTIAN_LIGHTHOUSE, ratePerSecond: 0.83 },
      { type: TYPE_EGYPTIAN_TOWN_CENTER, ratePerSecond: 0.83 },
    ],
  },
  isStatic: false,
  resource: -1,
  bodyRadius: 0.49,
  collidesWithProjectiles: true,
  footprint: 0,
  costFood: 50,
  costWood: 0,
  costGold: 0,
  costFavor: 0,
  buildTicks: 100,
  populationCost: 1,
  popBonus: 0,
  trainExitOffset: 0,
  isDropsite: false,
  requiredAge: AGE_ARCHAIC,
  requiredGod: NO_GOD,
  prerequisiteBuildings: [TYPE_EGYPTIAN_TOWN_CENTER],
  trainedAt: [{ type: TYPE_EGYPTIAN_TOWN_CENTER, commandSlot: 0 }],
  builtBy: NO_TYPE_RELATIONSHIPS,
} as const satisfies UnitTypeStats;
