import { AGE_MYTHIC, NO_GOD } from "../../../ecs/progression";
import { TYPE_EGYPTIAN_LABORER, TYPE_EGYPTIAN_LIGHTHOUSE } from "../../unit-type-ids";
import {
  CULTURE_EGYPTIAN,
  NO_PREREQUISITE_BUILDINGS,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_BUILDING,
  UNIT_CLASS_HUMAN,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_EGYPTIAN_LIGHTHOUSE,
  key: "egyptian-lighthouse",
  label: "Lighthouse",
  culture: CULTURE_EGYPTIAN,
  classes: UNIT_CLASS_BUILDING,
  maxHp: 1400,
  lineOfSight: 60,
  movementSpeed: 0,
  armor: [0.3, 0.9, 0.05],
  attack: null,
  garrison: {
    capacity: 10,
    enterRange: 1,
    validOccupants: [{ kind: "classes", classes: UNIT_CLASS_HUMAN }],
    attackMultiplierPerOccupant: 0,
    ejectOnDeath: true,
  },
  isStatic: true,
  resource: -1,
  bodyRadius: 3,
  collidesWithProjectiles: true,
  footprint: 3,
  costFood: 0,
  costWood: 0,
  costGold: 300,
  costFavor: 0,
  buildTicks: 120 * 20,
  buildLimit: 1,
  populationCost: 0,
  popBonus: 0,
  trainExitOffset: 4,
  isDropsite: false,
  requiredAge: AGE_MYTHIC,
  requiredGod: NO_GOD,
  prerequisiteBuildings: NO_PREREQUISITE_BUILDINGS,
  trainedAt: NO_TYPE_RELATIONSHIPS,
  builtBy: [{ type: TYPE_EGYPTIAN_LABORER, commandSlot: 19 }],
} as const satisfies UnitTypeStats;
