import { AGE_HEROIC, NO_GOD } from "../../../ecs/progression";
import { buildingArrowAttack } from "../../building-attacks";
import { TYPE_EGYPTIAN_LABORER, TYPE_EGYPTIAN_MIGDOL_STRONGHOLD } from "../../unit-type-ids";
import {
  CULTURE_EGYPTIAN,
  NO_PREREQUISITE_BUILDINGS,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_BUILDING,
  UNIT_CLASS_SHIP,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_EGYPTIAN_MIGDOL_STRONGHOLD,
  key: "egyptian-migdol-stronghold",
  label: "Migdol Stronghold",
  culture: CULTURE_EGYPTIAN,
  classes: UNIT_CLASS_BUILDING,
  maxHp: 2600,
  lineOfSight: 30,
  movementSpeed: 0,
  armor: [0.3, 0.96, 0.05],
  attack: buildingArrowAttack({
    damage: 12,
    range: 20,
    minimumRange: 4,
    projectileCount: 3,
    trackRating: 5,
    bonusShips: true,
  }),
  closeAttack: {
    kind: "melee",
    damage: [0, 12, 0],
    range: 4,
    aggroRange: 20,
    cooldownTicks: 20,
    bonuses: [{ target: { kind: "classes", classes: UNIT_CLASS_SHIP }, multiplier: 3 }],
  },
  isStatic: true,
  resource: -1,
  bodyRadius: 5,
  collidesWithProjectiles: true,
  footprint: 5,
  costFood: 0,
  costWood: 0,
  costGold: 400,
  costFavor: 10,
  buildTicks: 80 * 20,
  populationCost: 0,
  popBonus: 0,
  trainExitOffset: 6.5,
  isDropsite: false,
  requiredAge: AGE_HEROIC,
  requiredGod: NO_GOD,
  prerequisiteBuildings: NO_PREREQUISITE_BUILDINGS,
  trainedAt: NO_TYPE_RELATIONSHIPS,
  builtBy: [{ type: TYPE_EGYPTIAN_LABORER, commandSlot: 4 }],
} as const satisfies UnitTypeStats;
