import { AGE_ARCHAIC, NO_GOD } from "../../../ecs/progression";
import {
  TYPE_EGYPTIAN_LABORER,
  TYPE_EGYPTIAN_MONUMENT_TO_GODS,
  TYPE_EGYPTIAN_MONUMENT_TO_PHARAOHS,
} from "../../unit-type-ids";
import {
  CULTURE_EGYPTIAN,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_BUILDING,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_EGYPTIAN_MONUMENT_TO_GODS,
  key: "egyptian-monument-to-gods",
  label: "Monument to the Gods",
  culture: CULTURE_EGYPTIAN,
  classes: UNIT_CLASS_BUILDING,
  maxHp: 2400,
  lineOfSight: 9,
  movementSpeed: 0,
  armor: [0.3, 0.96, 0.05],
  attack: null,
  isStatic: true,
  resource: -1,
  bodyRadius: 3,
  collidesWithProjectiles: true,
  footprint: 3,
  costFood: 400,
  costWood: 0,
  costGold: 400,
  costFavor: 0,
  buildTicks: 80 * 20,
  buildLimit: 1,
  favorTricklePerSecond: 0.088,
  populationCost: 0,
  popBonus: 0,
  trainExitOffset: 0,
  isDropsite: false,
  requiredAge: AGE_ARCHAIC,
  requiredGod: NO_GOD,
  prerequisiteBuildings: [TYPE_EGYPTIAN_MONUMENT_TO_PHARAOHS],
  trainedAt: NO_TYPE_RELATIONSHIPS,
  builtBy: [{ type: TYPE_EGYPTIAN_LABORER, commandSlot: 18 }],
} as const satisfies UnitTypeStats;
