import { AGE_ARCHAIC, NO_GOD } from "../../../ecs/progression";
import {
  TYPE_EGYPTIAN_LABORER,
  TYPE_EGYPTIAN_MONUMENT_TO_SOLDIERS,
  TYPE_EGYPTIAN_MONUMENT_TO_VILLAGERS,
} from "../../unit-type-ids";
import {
  CULTURE_EGYPTIAN,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_BUILDING,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_EGYPTIAN_MONUMENT_TO_SOLDIERS,
  key: "egyptian-monument-to-soldiers",
  label: "Monument to Soldiers",
  culture: CULTURE_EGYPTIAN,
  classes: UNIT_CLASS_BUILDING,
  maxHp: 640,
  lineOfSight: 9,
  movementSpeed: 0,
  armor: [0.3, 0.96, 0.05],
  attack: null,
  isStatic: true,
  resource: -1,
  bodyRadius: 1,
  collidesWithProjectiles: true,
  footprint: 1,
  costFood: 100,
  costWood: 0,
  costGold: 100,
  costFavor: 0,
  buildTicks: 30 * 20,
  buildLimit: 1,
  favorTricklePerSecond: 0.077,
  populationCost: 0,
  popBonus: 0,
  trainExitOffset: 0,
  isDropsite: false,
  requiredAge: AGE_ARCHAIC,
  requiredGod: NO_GOD,
  prerequisiteBuildings: [TYPE_EGYPTIAN_MONUMENT_TO_VILLAGERS],
  trainedAt: NO_TYPE_RELATIONSHIPS,
  builtBy: [{ type: TYPE_EGYPTIAN_LABORER, commandSlot: 15 }],
} as const satisfies UnitTypeStats;
