import { TICK_HZ } from "../../../clock";
import { AGE_ARCHAIC, NO_GOD } from "../../../ecs/progression";
import { PROJECTILE_PRIEST } from "../../../ecs/projectiles";
import { TYPE_PHARAOH } from "../../unit-type-ids";
import {
  CULTURE_EGYPTIAN,
  NO_PREREQUISITE_BUILDINGS,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_HERO,
  UNIT_CLASS_MILITARY,
  UNIT_CLASS_NON_GREEK_UNIT,
  UNIT_CLASS_MYTH,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_PHARAOH,
  key: "egyptian-pharaoh",
  label: "Pharaoh",
  culture: CULTURE_EGYPTIAN,
  classes: UNIT_CLASS_HERO | UNIT_CLASS_MILITARY | UNIT_CLASS_NON_GREEK_UNIT,
  hero: { trainLimit: 1, relicCapacity: 1, relicPickupRange: 1, relicDropOffRange: 1 },
  maxHp: 100,
  lineOfSight: 10,
  movementSpeed: 4,
  armor: [0.15, 0.15, 0.99],
  attack: {
    kind: "projectile",
    damage: [0, 12, 0],
    range: 4,
    aggroRange: 10,
    cooldownTicks: 24,
    bonuses: [{ target: { kind: "classes", classes: UNIT_CLASS_MYTH }, multiplier: 5 }],
    launchDelayTicks: 10,
    accuracy: 1,
    accuracyReductionFactor: 0,
    aimBonus: 0,
    spreadFactor: 0,
    maxSpread: 0,
    trackRating: 5,
    unintentionalDamageMultiplier: 0.1,
    projectile: {
      type: PROJECTILE_PRIEST,
      speed: 30,
      lifespanTicks: 2 * TICK_HZ,
      collisionRadius: 0,
    },
  },
  heal: { range: 10, hitPointsPerSecond: 10, activeTargetMultiplier: 0.5 },
  empower: {
    range: 1,
    buildWorkMultiplier: 2,
    gatherYieldMultiplier: 1.2,
    trainWorkMultiplier: 1.3,
    attackIntervalMultiplier: 0.5,
  },
  ageProgression: {
    maxHpMultipliers: [1, 1, 1.1, 1.2],
    lineOfSight: [10, 16, 22, 24],
    attackRanges: [4, 12, 18, 20],
    attackDamageMultipliers: [0.3, 0.5, 0.7, 0.9],
  },
  isStatic: false,
  resource: -1,
  bodyRadius: 0.7,
  collidesWithProjectiles: true,
  footprint: 0,
  costFood: 0,
  costWood: 0,
  costGold: 0,
  costFavor: 0,
  buildTicks: 0,
  populationCost: 0,
  popBonus: 0,
  trainExitOffset: 0,
  isDropsite: false,
  requiredAge: AGE_ARCHAIC,
  requiredGod: NO_GOD,
  prerequisiteBuildings: NO_PREREQUISITE_BUILDINGS,
  trainedAt: NO_TYPE_RELATIONSHIPS,
  builtBy: NO_TYPE_RELATIONSHIPS,
} as const satisfies UnitTypeStats;
