import { TICK_HZ } from "../../../clock";
import { AGE_ARCHAIC, GOD_RA, GOD_SET, NO_GOD } from "../../../ecs/progression";
import { PROJECTILE_PRIEST } from "../../../ecs/projectiles";
import {
  TYPE_EGYPTIAN_TEMPLE,
  TYPE_EGYPTIAN_TOWN_CENTER,
  TYPE_PRIEST,
} from "../../unit-type-ids";
import {
  CULTURE_EGYPTIAN,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_HERO,
  UNIT_CLASS_MILITARY,
  UNIT_CLASS_MYTH,
  UNIT_CLASS_NON_GREEK_UNIT,
  UNIT_CLASS_SCOUT,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_PRIEST,
  key: "egyptian-priest",
  label: "Priest",
  culture: CULTURE_EGYPTIAN,
  classes:
    UNIT_CLASS_HERO | UNIT_CLASS_MILITARY | UNIT_CLASS_SCOUT | UNIT_CLASS_NON_GREEK_UNIT,
  hero: { relicCapacity: 0, relicPickupRange: 1, relicDropOffRange: 1 },
  maxHp: 90,
  lineOfSight: 8,
  movementSpeed: 3.6,
  armor: [0.1, 0, 0.99],
  attack: {
    kind: "projectile",
    damage: [0, 3, 0],
    range: 3,
    aggroRange: 8,
    cooldownTicks: TICK_HZ,
    bonuses: [{ target: { kind: "classes", classes: UNIT_CLASS_MYTH }, multiplier: 7 }],
    launchDelayTicks: 12,
    accuracy: 1,
    accuracyReductionFactor: 0,
    aimBonus: 0,
    spreadFactor: 0,
    maxSpread: 0,
    trackRating: 6,
    unintentionalDamageMultiplier: 0.1,
    projectile: {
      type: PROJECTILE_PRIEST,
      speed: 30,
      lifespanTicks: 2 * TICK_HZ,
      collisionRadius: 0,
    },
  },
  heal: { range: 10, hitPointsPerSecond: 7.5, activeTargetMultiplier: 0.5 },
  empower: {
    range: 1,
    buildWorkMultiplier: 1.3,
    gatherYieldMultiplier: 1.2,
    trainWorkMultiplier: 1.2,
    attackIntervalMultiplier: 0.5,
    requiredMajorGod: GOD_RA,
  },
  convert: { range: 10, baseTicks: 15 * TICK_HZ, requiredMajorGod: GOD_SET },
  ageProgression: {
    maxHpMultipliers: [1, 1, 1.1, 1.2],
    lineOfSight: [8, 16, 22, 24],
    attackRanges: [3, 12, 19, 22],
    attackDamageMultipliers: [0.5, 1, 1.1, 1.2],
  },
  isStatic: false,
  resource: -1,
  bodyRadius: 0.7,
  collidesWithProjectiles: true,
  footprint: 0,
  costFood: 0,
  costWood: 0,
  costGold: 100,
  costFavor: 0,
  buildTicks: 9 * TICK_HZ,
  populationCost: 2,
  popBonus: 0,
  trainExitOffset: 0,
  isDropsite: false,
  requiredAge: AGE_ARCHAIC,
  requiredGod: NO_GOD,
  prerequisiteBuildings: [TYPE_EGYPTIAN_TEMPLE],
  trainedAt: [
    { type: TYPE_EGYPTIAN_TEMPLE, commandSlot: 0 },
    { type: TYPE_EGYPTIAN_TOWN_CENTER, commandSlot: 1 },
  ],
  builtBy: NO_TYPE_RELATIONSHIPS,
} as const satisfies UnitTypeStats;
