import { AGE_HEROIC, NO_GOD } from "../../../ecs/progression";
import { TYPE_EGYPTIAN_DOCK, TYPE_RAMMING_GALLEY } from "../../unit-type-ids";
import {
  CULTURE_EGYPTIAN,
  MOVEMENT_DOMAIN_WATER,
  NO_DAMAGE_BONUSES,
  NO_PREREQUISITE_BUILDINGS,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_MELEE,
  UNIT_CLASS_MILITARY,
  UNIT_CLASS_SHIP,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_RAMMING_GALLEY,
  key: "egyptian-ramming-galley",
  label: "Ramming Galley",
  culture: CULTURE_EGYPTIAN,
  classes: UNIT_CLASS_MILITARY | UNIT_CLASS_MELEE | UNIT_CLASS_SHIP,
  maxHp: 240,
  lineOfSight: 16,
  movementSpeed: 7,
  movementDomain: MOVEMENT_DOMAIN_WATER,
  armor: [0.3, 0.15, 0.75],
  attack: {
    kind: "melee",
    damage: [20, 0, 0],
    range: 2,
    aggroRange: 16,
    cooldownTicks: 30,
    bonuses: NO_DAMAGE_BONUSES,
    cycleVariants: [{ actionTicks: 30, impactDelayTicks: 2 }],
  },
  isStatic: false,
  resource: -1,
  bodyRadius: 0.7,
  collidesWithProjectiles: true,
  footprint: 0,
  costFood: 0,
  costWood: 100,
  costGold: 50,
  costFavor: 0,
  buildTicks: 180,
  populationCost: 2,
  popBonus: 0,
  trainExitOffset: 0,
  isDropsite: false,
  requiredAge: AGE_HEROIC,
  requiredGod: NO_GOD,
  prerequisiteBuildings: NO_PREREQUISITE_BUILDINGS,
  trainedAt: [{ type: TYPE_EGYPTIAN_DOCK, commandSlot: 3 }],
  builtBy: NO_TYPE_RELATIONSHIPS,
} as const satisfies UnitTypeStats;
