import { AGE_HEROIC, NO_GOD } from "../../../ecs/progression";
import { PROJECTILE_ARROW } from "../../../ecs/projectiles";
import { TYPE_EGYPTIAN_SIEGE_WORKS, TYPE_SIEGE_TOWER } from "../../unit-type-ids";
import {
  CULTURE_EGYPTIAN,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_ARCHER,
  UNIT_CLASS_HERO,
  UNIT_CLASS_HUMAN,
  UNIT_CLASS_INFANTRY,
  UNIT_CLASS_MELEE,
  UNIT_CLASS_MILITARY,
  UNIT_CLASS_SIEGE,
  UNIT_CLASS_WORKER,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_SIEGE_TOWER,
  key: "egyptian-siege-tower",
  label: "Siege Tower",
  culture: CULTURE_EGYPTIAN,
  classes: UNIT_CLASS_MILITARY | UNIT_CLASS_SIEGE | UNIT_CLASS_MELEE,
  maxHp: 350,
  lineOfSight: 20,
  movementSpeed: 2.9,
  armor: [0.05, 0.96, 0.9],
  attack: {
    kind: "projectile",
    damage: [0, 5, 0],
    range: 12,
    aggroRange: 20,
    cooldownTicks: 20,
    bonuses: [],
    autoAcquireBuildings: true,
    launchDelayTicks: 8,
    accuracy: 0.8,
    accuracyReductionFactor: 1.5,
    aimBonus: 15,
    spreadFactor: 0.1,
    maxSpread: 50,
    trackRating: 5,
    unintentionalDamageMultiplier: 0.3,
    projectileCount: 3,
    projectile: { type: PROJECTILE_ARROW, speed: 30, lifespanTicks: 40, collisionRadius: 0.1 },
  },
  buildingAttack: {
    kind: "melee",
    damage: [0, 0, 50],
    range: 3,
    aggroRange: 20,
    cooldownTicks: 4 * 20,
    bonuses: [],
    cycleVariants: [{ actionTicks: 80, impactDelayTicks: 40 }],
  },
  garrison: {
    capacity: 5,
    enterRange: 4,
    validOccupants: [
      { kind: "classes", classes: UNIT_CLASS_WORKER },
      { kind: "classes", classes: UNIT_CLASS_HERO },
      { kind: "classes", classes: UNIT_CLASS_HUMAN | UNIT_CLASS_INFANTRY },
      { kind: "classes", classes: UNIT_CLASS_HUMAN | UNIT_CLASS_ARCHER },
      { kind: "unit", key: "egyptian-pharaoh" },
      { kind: "unit", key: "egyptian-priest" },
      { kind: "unit", key: "egyptian-son-of-osiris" },
    ],
    attackMultiplierPerOccupant: 0.05,
    speedMultiplierPerOccupant: 0.05,
    ejectOnDeath: true,
  },
  isStatic: false,
  resource: -1,
  bodyRadius: 0.99,
  collidesWithProjectiles: true,
  footprint: 0,
  costFood: 0,
  costWood: 200,
  costGold: 100,
  costFavor: 0,
  buildTicks: 22 * 20,
  populationCost: 3,
  popBonus: 0,
  trainExitOffset: 0,
  isDropsite: false,
  requiredAge: AGE_HEROIC,
  requiredGod: NO_GOD,
  prerequisiteBuildings: [TYPE_EGYPTIAN_SIEGE_WORKS],
  trainedAt: [{ type: TYPE_EGYPTIAN_SIEGE_WORKS, commandSlot: 0 }],
  builtBy: NO_TYPE_RELATIONSHIPS,
} as const satisfies UnitTypeStats;
