import { AGE_CLASSICAL, NO_GOD } from "../../../ecs/progression";
import { PROJECTILE_SLING_STONE } from "../../../ecs/projectiles";
import { TYPE_EGYPTIAN_BARRACKS, TYPE_SLINGER } from "../../unit-type-ids";
import {
  CULTURE_EGYPTIAN,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_ARCHER,
  UNIT_CLASS_HUMAN,
  UNIT_CLASS_MILITARY,
  UNIT_CLASS_NON_GREEK_UNIT,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_SLINGER,
  key: "egyptian-slinger",
  label: "Slinger",
  culture: CULTURE_EGYPTIAN,
  classes: UNIT_CLASS_HUMAN | UNIT_CLASS_MILITARY | UNIT_CLASS_ARCHER | UNIT_CLASS_NON_GREEK_UNIT,
  maxHp: 65,
  lineOfSight: 20,
  movementSpeed: 4,
  armor: [0.15, 0.2, 0.99],
  attack: {
    kind: "projectile",
    damage: [0, 3, 0],
    range: 16,
    aggroRange: 20,
    cooldownTicks: 20,
    bonuses: [
      { target: { kind: "classes", classes: UNIT_CLASS_ARCHER }, multiplier: 4 },
      { target: { kind: "unit", key: "norse-throwing-axeman" }, multiplier: 3 },
      { target: { kind: "unit", key: "greek-hypaspist" }, multiplier: 1.25 },
      { target: { kind: "unit", key: "egyptian-axeman" }, multiplier: 1.25 },
    ],
    launchDelayTicks: 8,
    accuracy: 0.8,
    accuracyReductionFactor: 1.5,
    aimBonus: 15,
    spreadFactor: 0.25,
    maxSpread: 5,
    trackRating: 5,
    unintentionalDamageMultiplier: 0.3,
    projectile: {
      type: PROJECTILE_SLING_STONE,
      speed: 30,
      lifespanTicks: 2 * 20,
      collisionRadius: 0.1,
    },
  },
  isStatic: false,
  resource: -1,
  bodyRadius: 0.49,
  collidesWithProjectiles: true,
  footprint: 0,
  costFood: 0,
  costWood: 60,
  costGold: 24,
  costFavor: 0,
  buildTicks: 14 * 20,
  populationCost: 2,
  popBonus: 0,
  trainExitOffset: 0,
  isDropsite: false,
  requiredAge: AGE_CLASSICAL,
  requiredGod: NO_GOD,
  prerequisiteBuildings: [TYPE_EGYPTIAN_BARRACKS],
  trainedAt: [{ type: TYPE_EGYPTIAN_BARRACKS, commandSlot: 2 }],
  builtBy: NO_TYPE_RELATIONSHIPS,
} as const satisfies UnitTypeStats;
