import { TICK_HZ } from "../../../clock";
import { AGE_MYTHIC, GOD_OSIRIS } from "../../../ecs/progression";
import { TYPE_SON_OF_OSIRIS } from "../../unit-type-ids";
import {
  CULTURE_EGYPTIAN,
  NO_PREREQUISITE_BUILDINGS,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_HERO,
  UNIT_CLASS_MILITARY,
  UNIT_CLASS_MYTH,
  UNIT_CLASS_NON_GREEK_UNIT,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_SON_OF_OSIRIS,
  key: "egyptian-son-of-osiris",
  label: "Son of Osiris",
  culture: CULTURE_EGYPTIAN,
  classes: UNIT_CLASS_HERO | UNIT_CLASS_MILITARY | UNIT_CLASS_NON_GREEK_UNIT,
  hero: { trainLimit: 1, relicCapacity: 1, relicPickupRange: 1, relicDropOffRange: 1 },
  maxHp: 420,
  lineOfSight: 25,
  movementSpeed: 3.6,
  armor: [0.3, 0.5, 0.99],
  attack: {
    kind: "beam",
    damage: [60, 0, 0],
    range: 18,
    aggroRange: 25,
    cooldownTicks: 3 * TICK_HZ,
    bonuses: [{ target: { kind: "classes", classes: UNIT_CLASS_MYTH }, multiplier: 5 }],
    impactDelayTicks: 33,
    chain: { maxTargets: 4, radius: 8, damageMultiplier: 1 },
  },
  heal: { range: 10, hitPointsPerSecond: 20, activeTargetMultiplier: 0.5 },
  empower: {
    range: 1,
    buildWorkMultiplier: 2,
    gatherYieldMultiplier: 1.2,
    trainWorkMultiplier: 1.3,
    attackIntervalMultiplier: 0.5,
  },
  healable: false,
  isStatic: false,
  resource: -1,
  bodyRadius: 0.7,
  collidesWithProjectiles: true,
  footprint: 0,
  costFood: 0,
  costWood: 0,
  costGold: 0,
  costFavor: 0,
  buildTicks: 0,
  populationCost: 0,
  popBonus: 0,
  trainExitOffset: 0,
  isDropsite: false,
  requiredAge: AGE_MYTHIC,
  requiredGod: GOD_OSIRIS,
  prerequisiteBuildings: NO_PREREQUISITE_BUILDINGS,
  trainedAt: NO_TYPE_RELATIONSHIPS,
  builtBy: NO_TYPE_RELATIONSHIPS,
} as const satisfies UnitTypeStats;
