import { AGE_ARCHAIC, NO_GOD } from "../../../ecs/progression";
import { TYPE_EGYPTIAN_LABORER, TYPE_EGYPTIAN_TEMPLE } from "../../unit-type-ids";
import {
  CULTURE_EGYPTIAN,
  NO_PREREQUISITE_BUILDINGS,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_BUILDING,
  UNIT_CLASS_TEMPLE,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_EGYPTIAN_TEMPLE,
  key: "egyptian-temple",
  label: "Temple",
  culture: CULTURE_EGYPTIAN,
  classes: UNIT_CLASS_BUILDING | UNIT_CLASS_TEMPLE,
  maxHp: 1200,
  lineOfSight: 9,
  movementSpeed: 0,
  armor: [0.3, 0.96, 0.05],
  attack: null,
  isStatic: true,
  resource: -1,
  bodyRadius: 5,
  collidesWithProjectiles: true,
  footprint: 5,
  costFood: 0,
  costWood: 0,
  costGold: 100,
  costFavor: 0,
  buildTicks: 800,
  populationCost: 0,
  popBonus: 0,
  trainExitOffset: 0,
  isDropsite: false,
  requiredAge: AGE_ARCHAIC,
  requiredGod: NO_GOD,
  prerequisiteBuildings: NO_PREREQUISITE_BUILDINGS,
  trainedAt: NO_TYPE_RELATIONSHIPS,
  builtBy: [{ type: TYPE_EGYPTIAN_LABORER, commandSlot: 2 }],
} as const satisfies UnitTypeStats;
