import { AGE_CLASSICAL, NO_GOD } from "../../../ecs/progression";
import { buildingArrowAttack } from "../../building-attacks";
import { TYPE_EGYPTIAN_LABORER, TYPE_EGYPTIAN_TOWER } from "../../unit-type-ids";
import {
  CULTURE_EGYPTIAN,
  NO_PREREQUISITE_BUILDINGS,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_BUILDING,
  UNIT_CLASS_HUMAN,
  UNIT_CLASS_SHIP,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_EGYPTIAN_TOWER,
  key: "egyptian-tower",
  label: "Sentry Tower",
  culture: CULTURE_EGYPTIAN,
  classes: UNIT_CLASS_BUILDING,
  maxHp: 550,
  lineOfSight: 24,
  movementSpeed: 0,
  armor: [0.3, 0.85, 0.05],
  attack: buildingArrowAttack({
    damage: 8,
    range: 20,
    minimumRange: 4,
    projectileCount: 2,
    trackRating: 5,
    bonusShips: true,
    bonusAir: true,
  }),
  closeAttack: {
    kind: "melee",
    damage: [0, 10, 0],
    range: 4,
    aggroRange: 20,
    cooldownTicks: 20,
    bonuses: [{ target: { kind: "classes", classes: UNIT_CLASS_SHIP }, multiplier: 3 }],
  },
  garrison: {
    capacity: 5,
    enterRange: 6,
    validOccupants: [{ kind: "classes", classes: UNIT_CLASS_HUMAN }],
    attackMultiplierPerOccupant: 0.1,
    ejectOnDeath: true,
  },
  isStatic: true,
  resource: -1,
  bodyRadius: 1,
  collidesWithProjectiles: true,
  footprint: 1,
  costFood: 0,
  costWood: 0,
  costGold: 200,
  costFavor: 0,
  buildTicks: 50 * 20,
  buildLimit: 30,
  populationCost: 0,
  popBonus: 0,
  trainExitOffset: 2,
  isDropsite: false,
  requiredAge: AGE_CLASSICAL,
  requiredGod: NO_GOD,
  prerequisiteBuildings: NO_PREREQUISITE_BUILDINGS,
  trainedAt: NO_TYPE_RELATIONSHIPS,
  builtBy: [{ type: TYPE_EGYPTIAN_LABORER, commandSlot: 13 }],
} as const satisfies UnitTypeStats;
