import { AGE_CLASSICAL, NO_GOD } from "../../../ecs/progression";
import { TYPE_EGYPTIAN_LABORER, TYPE_EGYPTIAN_TOWN_CENTER } from "../../unit-type-ids";
import {
  CULTURE_EGYPTIAN,
  NO_ARMOR,
  NO_PREREQUISITE_BUILDINGS,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_BUILDING,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_EGYPTIAN_TOWN_CENTER,
  key: "egyptian-town-center",
  label: "Town Center",
  culture: CULTURE_EGYPTIAN,
  classes: UNIT_CLASS_BUILDING,
  maxHp: 2400,
  lineOfSight: 14,
  movementSpeed: 0,
  armor: NO_ARMOR,
  attack: null,
  isStatic: true,
  resource: -1,
  bodyRadius: 2.9,
  collidesWithProjectiles: true,
  footprint: 4,
  costFood: 0,
  costWood: 300,
  costGold: 0,
  costFavor: 0,
  buildTicks: 300,
  populationCost: 0,
  popBonus: 15,
  trainExitOffset: 6.5,
  isDropsite: true,
  requiredAge: AGE_CLASSICAL,
  requiredGod: NO_GOD,
  prerequisiteBuildings: NO_PREREQUISITE_BUILDINGS,
  trainedAt: NO_TYPE_RELATIONSHIPS,
  builtBy: [{ type: TYPE_EGYPTIAN_LABORER, commandSlot: 3 }],
} as const satisfies UnitTypeStats;
