import { AGE_CLASSICAL, GOD_PTAH } from "../../../ecs/progression";
import { PROJECTILE_WADJET_SPIT } from "../../../ecs/projectiles";
import { TYPE_EGYPTIAN_TEMPLE, TYPE_WADJET } from "../../unit-type-ids";
import {
  CULTURE_EGYPTIAN,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_ARCHER,
  UNIT_CLASS_HERO,
  UNIT_CLASS_MILITARY,
  UNIT_CLASS_MYTH,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_WADJET,
  key: "egyptian-wadjet",
  label: "Wadjet",
  culture: CULTURE_EGYPTIAN,
  classes: UNIT_CLASS_MYTH | UNIT_CLASS_ARCHER | UNIT_CLASS_MILITARY,
  maxHp: 240,
  lineOfSight: 20,
  movementSpeed: 3.8,
  armor: [0.2, 0.3, 0.8],
  attack: {
    kind: "projectile",
    damage: [0, 16, 0],
    range: 18,
    aggroRange: 20,
    cooldownTicks: 20,
    bonuses: [
      { target: { kind: "classes", classes: UNIT_CLASS_MYTH }, multiplier: 3 },
      { target: { kind: "classes", classes: UNIT_CLASS_HERO }, multiplier: 0.25 },
    ],
    launchDelayTicks: 12,
    accuracy: 1,
    accuracyReductionFactor: 0,
    aimBonus: 0,
    spreadFactor: 0,
    maxSpread: 0,
    trackRating: 5,
    unintentionalDamageMultiplier: 1,
    projectile: {
      type: PROJECTILE_WADJET_SPIT,
      speed: 30,
      lifespanTicks: 40,
      collisionRadius: 0.1,
    },
  },
  isStatic: false,
  resource: -1,
  bodyRadius: 0.99,
  collidesWithProjectiles: true,
  footprint: 0,
  costFood: 0,
  costWood: 150,
  costGold: 0,
  costFavor: 15,
  buildTicks: 17 * 20,
  regenerationPerSecond: 1,
  populationCost: 3,
  popBonus: 0,
  trainExitOffset: 0,
  isDropsite: false,
  requiredAge: AGE_CLASSICAL,
  requiredGod: GOD_PTAH,
  prerequisiteBuildings: [TYPE_EGYPTIAN_TEMPLE],
  trainedAt: [{ type: TYPE_EGYPTIAN_TEMPLE, commandSlot: 1 }],
  builtBy: NO_TYPE_RELATIONSHIPS,
} as const satisfies UnitTypeStats;
