import { TICK_HZ } from "../../../clock";
import { AGE_MYTHIC, GOD_THOTH } from "../../../ecs/progression";
import { TYPE_EGYPTIAN_DOCK, TYPE_WAR_TURTLE } from "../../unit-type-ids";
import {
  AREA_DAMAGE_ENEMIES,
  CULTURE_EGYPTIAN,
  MOVEMENT_DOMAIN_WATER,
  NO_DAMAGE_BONUSES,
  NO_PREREQUISITE_BUILDINGS,
  NO_TYPE_RELATIONSHIPS,
  UNIT_CLASS_MELEE,
  UNIT_CLASS_MILITARY,
  UNIT_CLASS_MYTH,
  UNIT_CLASS_SHIP,
  type UnitTypeStats,
} from "../../unit-type-schema";

export const definition = {
  id: TYPE_WAR_TURTLE,
  key: "egyptian-war-turtle",
  label: "War Turtle",
  culture: CULTURE_EGYPTIAN,
  classes: UNIT_CLASS_MYTH | UNIT_CLASS_MILITARY | UNIT_CLASS_MELEE,
  maxHp: 960,
  lineOfSight: 22,
  movementSpeed: 5.3,
  movementDomain: MOVEMENT_DOMAIN_WATER,
  armor: [0.4, 0.7, 0.8],
  attack: {
    kind: "melee",
    damage: [25, 0, 20],
    range: 0.1,
    aggroRange: 22,
    cooldownTicks: TICK_HZ,
    bonuses: NO_DAMAGE_BONUSES,
    cycleVariants: [{ actionTicks: 33, impactDelayTicks: 18 }],
  },
  specialAttack: {
    kind: "charged-cone-throw",
    damage: [100, 0, 30],
    range: 3,
    radius: 7,
    coneHalfAngleDegrees: 45,
    damageRelations: AREA_DAMAGE_ENEMIES,
    bonuses: NO_DAMAGE_BONUSES,
    rechargeTicks: 15 * TICK_HZ,
    actionTicks: 30,
    impactDelayTicks: 18,
    validTargets: [{ kind: "classes", classes: UNIT_CLASS_SHIP }],
    targetReaction: {
      kind: "thrown",
      randomDrawOrder: ["maxVelocity", "maxHeight", "distance"],
      distanceBase: 5,
      distanceRandomRange: 1.5,
      maxVelocityBase: 14,
      maxVelocityRandomRange: 4,
      maxHeightBase: 6,
      maxHeightRandomRange: 2,
      bounceBase: 0,
      bounceRandomRange: 0,
    },
  },
  isStatic: false,
  resource: -1,
  bodyRadius: 0.99,
  collidesWithProjectiles: true,
  footprint: 0,
  costFood: 300,
  costWood: 0,
  costGold: 0,
  costFavor: 20,
  buildTicks: 9 * TICK_HZ,
  populationCost: 5,
  popBonus: 0,
  trainExitOffset: 0,
  isDropsite: false,
  requiredAge: AGE_MYTHIC,
  requiredGod: GOD_THOTH,
  prerequisiteBuildings: NO_PREREQUISITE_BUILDINGS,
  trainedAt: [{ type: TYPE_EGYPTIAN_DOCK, commandSlot: 6 }],
  builtBy: NO_TYPE_RELATIONSHIPS,
} as const satisfies UnitTypeStats;
